/*
 * TRText.java
 *
 * Created on April 4, 2007, 4:19 PM
 */

package clusterMaker.algorithms.autosome.view.view2d;



import clusterMaker.algorithms.autosome.mapping.som.*;
import java.util.*;
//import view.view3d.viewer3D;
import clusterMaker.algorithms.autosome.mapping.som.Node;
import clusterMaker.algorithms.autosome.cluststruct.*;
import clusterMaker.algorithms.autosome.launch.Settings;

/**
 *
 * @author  a_newman
 */
public class Text_List extends javax.swing.JFrame implements clusterMaker.algorithms.autosome.view.view2d.Text_Interface{
    
     /** Creates new form TRText */
    public Text_List(SOM SOM, boolean file, Settings s) {

        this.SOM = SOM;
        this.s = s;
        
        init();
        
        initComponents();        

        setSize();

        //jFrame1.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/icons/search.png")).getImage());

}
    
    public Text_List(Settings s){
        this.s = s;
        
        init();
        
        initComponents();        

        setSize();
    }
    
    public void init(){
        
        pic_Drawer pic = new pic_Drawer(s);
        pic.CreateTRImage(TRs, false);
        B = pic.rendImage;
        TP = new Text_JPanel(pic);
        
        
    }
    
    public void setSize(){
        this.setSize(400, 400);
        int wid  = (int)(java.awt.Toolkit.getDefaultToolkit().getScreenSize().getWidth()/2 + 225);
        if(wid + this.getWidth() >(int)(java.awt.Toolkit.getDefaultToolkit().getScreenSize().getWidth())) wid = (int)(java.awt.Toolkit.getDefaultToolkit().getScreenSize().getWidth()) - this.getWidth();
        else this.setLocation(wid, (int)(java.awt.Toolkit.getDefaultToolkit().getScreenSize().getHeight()/2-(this.getSize().getHeight()/2)));
    }
    
    
    public void add(String[] trs){
        this.trs = trs;
        convertData();
        if(choice > 1){
            add(d);
            return;
        }
        pic_Drawer pic = new pic_Drawer(s);

            for(int i = 0; i < trs.length; i++){
                String[] tokens = trs[i].split(",");
                trs[i] = tokens[0];
            }
        
        pic.CreateTRImage(trs, false);
        TP.update(pic);
        TP.repaint();
        
        if(jFrame1.isVisible()){
            jScrollPane2.repaint();
            jScrollPane2.setViewportView(TP);
            jScrollPane2.repaint();
        }else{
            jScrollPane1.repaint();
            jScrollPane1.setViewportView(TP);
            jScrollPane1.repaint();
        }
        B = pic.rendImage;
    }
    
    public void add(dataItem[] d){

        pic_Drawer pic = new pic_Drawer(s);
        
       
        
        if(choice >= 2 && choice <= 4) pic.createHeatMap(d, choice, scale, false, false, true,false,null, false, 0, 0);
        
        if(choice == 5) pic.createScatterPlot(d, scale, true, true,5,5,false, true);
        if(choice == 6) pic.createScatterPlot(d, scale, false, true,5,5,false, true);
        
        TP.update(pic);
        TP.repaint();
        
        if(jFrame1.isVisible()){
            jScrollPane2.repaint();
            jScrollPane2.setViewportView(TP);
            jScrollPane2.repaint();
        }else{
            jScrollPane1.repaint();
            jScrollPane1.setViewportView(TP);
            jScrollPane1.repaint();
        }
        B = pic.rendImage;
    }
    
    private void convertData(){
        d = new dataItem[TRs.length];
        for(int i = 0; i < d.length; i++){        
            String[] tokens = TRs[i].split(",");
            float[] data = new float[tokens.length-1];
            for(int j = 1; j < tokens.length; j++){
                data[j-1] = Float.valueOf(tokens[j]);
            }
            d[i] = new dataItem(data, tokens[0]);
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        javax.swing.SpinnerModel model = new javax.swing.SpinnerNumberModel(10, 0, 999, 1);
        jSpinner1 = new javax.swing.JSpinner(model);
        jScrollPane2 = new javax.swing.JScrollPane();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane(TP);
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        jFrame1.setTitle("TR Query");

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });

        jButton1.setText("Submit");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });

        jLabel1.setText("Show Top:");

        jMenu2.setText("Options");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jCheckBoxMenuItem2.setText("Color Query");
        jCheckBoxMenuItem2.setActionCommand("color query");
        jMenu2.add(jCheckBoxMenuItem2);

        jCheckBoxMenuItem1.setText("sort by period");
        jMenu2.add(jCheckBoxMenuItem1);

        jMenuItem4.setText("TR Info");
        jMenuItem4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem4MousePressed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenu3.setText("Block Diagram");

        jMenuItem5.setText("Selected TRs");
        jMenuItem5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem5MousePressed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuItem7.setText("All TRs");
        jMenuItem7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem7MousePressed(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        jMenu2.add(jMenu3);

        jMenu6.setText("Other Tools");

        jMenuItem11.setText("Seq Logo");
        jMenuItem11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem11MousePressed(evt);
            }
        });
        jMenu6.add(jMenuItem11);

        jMenuItem12.setText("Draw Tree");
        jMenuItem12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem12MousePressed(evt);
            }
        });
        jMenu6.add(jMenuItem12);

        jMenu2.add(jMenu6);

        jMenuItem6.setText("Save");
        jMenuItem6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem6MousePressed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuBar2.add(jMenu2);

        org.jdesktop.layout.GroupLayout jFrame1Layout = new org.jdesktop.layout.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                    .add(jTextField1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                    .add(jFrame1Layout.createSequentialGroup()
                        .add(jButton1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 40, Short.MAX_VALUE)
                        .add(jLabel1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jSpinner1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 44, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton1)
                    .add(jLabel1)
                    .add(jSpinner1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                .addContainerGap())
        );

        setTitle("Cluster Viewer");
        setAlwaysOnTop(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jScrollPane1.setBackground(java.awt.Color.BLACK);
        jScrollPane1.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jScrollPane1MouseWheelMoved(evt);
            }
        });

        jMenu1.setText("Options");

        jMenuItem3.setText("raw data");
        jMenuItem3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem3MousePressed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenu4.setText("heat map");

        jMenuItem1.setText("green red");
        jMenuItem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem1MousePressed(evt);
            }
        });
        jMenu4.add(jMenuItem1);

        jMenuItem8.setText("gray scale");
        jMenuItem8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem8MousePressed(evt);
            }
        });
        jMenu4.add(jMenuItem8);

        jMenuItem10.setText("blue white");
        jMenuItem10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem10MousePressed(evt);
            }
        });
        jMenu4.add(jMenuItem10);

        jMenu1.add(jMenu4);

        jMenu5.setText("signal plot");

        jMenuItem13.setText("rainbow");
        jMenuItem13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem13MousePressed(evt);
            }
        });
        jMenu5.add(jMenuItem13);

        jMenuItem9.setText("red");
        jMenuItem9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem9MousePressed(evt);
            }
        });
        jMenu5.add(jMenuItem9);

        jMenu1.add(jMenu5);

        jMenuItem2.setText("save");
        jMenuItem2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem2MousePressed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem12MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem12MousePressed
  
    }//GEN-LAST:event_jMenuItem12MousePressed

    private void jMenuItem11MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem11MousePressed
    
    }//GEN-LAST:event_jMenuItem11MousePressed

    private void jMenuItem7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem7MousePressed
      
    }//GEN-LAST:event_jMenuItem7MousePressed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
     
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
       
    }//GEN-LAST:event_jButton1MousePressed

    private void jMenuItem6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem6MousePressed

    }//GEN-LAST:event_jMenuItem6MousePressed

    private void jMenuItem5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem5MousePressed
      
    }//GEN-LAST:event_jMenuItem5MousePressed

    private void jMenuItem4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem4MousePressed
       
    }//GEN-LAST:event_jMenuItem4MousePressed

    private void jMenuItem2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem2MousePressed
      /*  fileio.File_Write.graphics = true;
        fileio.File_Write.b = B;
        fileio.File_Write.start("");*/
    }//GEN-LAST:event_jMenuItem2MousePressed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

    }//GEN-LAST:event_formWindowClosing

private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jMenu2ActionPerformed

private void jMenuItem1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem1MousePressed
    choice = 2;
    add(d);
}//GEN-LAST:event_jMenuItem1MousePressed

private void jMenuItem3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem3MousePressed
    choice = 1;
    add(TRs);
}//GEN-LAST:event_jMenuItem3MousePressed

private void jMenuItem8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem8MousePressed
    choice = 3;
    add(d);
}//GEN-LAST:event_jMenuItem8MousePressed

private void jMenuItem9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem9MousePressed
    choice = 5;
    add(d);
}//GEN-LAST:event_jMenuItem9MousePressed

private void jScrollPane1MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jScrollPane1MouseWheelMoved
    if(choice == 1) return;
    scale += evt.getWheelRotation();
    if(scale < 1) scale = 1;
    add(d);
}//GEN-LAST:event_jScrollPane1MouseWheelMoved

private void jMenuItem10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem10MousePressed
   choice = 4;
    add(d);
}//GEN-LAST:event_jMenuItem10MousePressed

private void jMenuItem13MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem13MousePressed
    choice = 6;
    add(d);
}//GEN-LAST:event_jMenuItem13MousePressed
   

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    public javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
    private Text_JPanel TP;
    public Text_List tt;
    public String[] TRs = {"TEST"};
    public String[] trs;
    public int[] TRids = new int[1];
    public String extraCond = new String();
    private java.awt.image.BufferedImage B;
//    public viewer3D view;
    private SOM SOM;
    public int[] order = null;
    public dataItem[] d;
    private int choice = 1; //1 = raw data, 2 = heat map, 3 = gray scale
    public static int scale = 10;
    private Settings s;
}
