# makefile for cytoscape.view package
#-------------------------------------------------------------------------
# $Revision$
# $Date$
# $Author$
#-------------------------------------------------------------------------

JC=javac

.SUFFIXES: .java .class
.java.class: 
	$(JC) $<

OBJS =  StraightLineMoveMode.class

default: objs 

objs: $(OBJS)

clean:
	- rm *.class 


