CompCom = g++

atg7: atg7.o func_init.o aonly.o aonly2.o aonly3.o aonly4.o aonlyes.o\
      starteli.o stopeli.o trsite6.o only.o patonly.o patonly2.o\
      patonly2m.o min_cds_len.o\
      eliatg.o\
      testvc.o alignment.o bun.o buns.o handget.o\
      nseqread.o strrout.o testt.o spsim.o narasen.o\
      freq_func.o patfreq.o wind.o ec_970506.o\
      trsite5.o icisl.o lkatgav.o junkget.o atcgcon.o utrcds_gc.o\
      cDNA_5utr_atg.o trterm.o\
      hfindpat.o pseudo_atg.o scan_2d.o scan_stem.o scan_bstem.o\
      scan_mstem.o sdwin.o cyaex.o palind.o palind2.o palind3.o palind4.o \
      cds_echo.o patfind.o colcal.o orfsearch.o rand_pro.o\
      idinuc_count.o dash3.o
	${CompCom} atg7.o func_init.o aonly.o aonly2.o aonly3.o aonly4.o\
         aonlyes.o\
         starteli.o stopeli.o trsite6.o  only.o patonly.o patonly2.o\
         patonly2m.o min_cds_len.o\
         eliatg.o testvc.o alignment.o bun.o buns.o\
         nseqread.o strrout.o testt.o handget.o spsim.o narasen.o\
         freq_func.o patfreq.o wind.o ec_970506.o\
         trsite5.o icisl.o lkatgav.o junkget.o atcgcon.o utrcds_gc.o\
         cDNA_5utr_atg.o\
         trterm.o hfindpat.o pseudo_atg.o scan_2d.o\
         scan_stem.o  scan_bstem.o scan_mstem.o sdwin.o cyaex.o\
         palind.o palind2.o palind3.o palind4.o cds_echo.o patfind.o\
         colcal.o orfsearch.o rand_pro.o\
         idinuc_count.o dash3.o -o atg7 -lm

atg7.o: atg7.c global_st.h atg_func.h
	${CompCom} -c atg7.c

func_init.o: func_init.c global_st.h atg_func.h
	${CompCom} -c func_init.c

nseqread.o: nseqread.c 
	${CompCom} -c nseqread.c 

strrout.o: strrout.c global_st.h
	${CompCom} -c strrout.c

alignment.o: alignment.c
	${CompCom} -c alignment.c

testvc.o: testvc.c
	${CompCom} -c testvc.c

bun.o: bun.c
	${CompCom} -c bun.c

buns.o: buns.c global_st.h
	${CompCom} -c buns.c

testt.o: testt.c global_st.h atg_func.h
	${CompCom} -c testt.c

handget.o: handget.c global_st.h atg_func.h
	${CompCom} -c handget.c

spsim.o: spsim.c global_st.h
	${CompCom} -c spsim.c

narasen.o: narasen.c global_st.h
	${CompCom} -c narasen.c

freq_func.o: freq_func.c global_st.h atg_func.h
	${CompCom} -c freq_func.c

patfreq.o: patfreq.c global_st.h atg_func.h
	${CompCom} -c patfreq.c

wind.o: wind.c global_st.h atg_func.h
	${CompCom} -c wind.c

ec_970506.o: ec_970506.c global_st.h atg_func.h
	${CompCom} -c ec_970506.c

aonly.o: aonly.c global_st.h atg_func.h
	${CompCom} -c aonly.c

aonly2.o: aonly2.c global_st.h atg_func.h
	${CompCom} -c aonly2.c

aonly3.o: aonly3.c global_st.h atg_func.h
	${CompCom} -c aonly3.c

aonlyes.o: aonlyes.c global_st.h atg_func.h
	${CompCom} -c aonlyes.c

aonly4.o: aonly4.c global_st.h atg_func.h
	${CompCom} -c aonly4.c

starteli.o: stopeli.c global_st.h atg_func.h
	${CompCom} -c starteli.c

stopeli.o: stopeli.c global_st.h atg_func.h
	${CompCom} -c stopeli.c

trsite6.o: trsite6.c global_st.h atg_func.h
	${CompCom} -c trsite6.c

only.o: only.c global_st.h atg_func.h
	${CompCom} -c only.c

patonly.o: patonly.c global_st.h atg_func.h
	${CompCom} -c patonly.c

patonly2.o: patonly2.c global_st.h atg_func.h
	${CompCom} -c patonly2.c

patonly2m.o: patonly2m.c global_st.h atg_func.h
	${CompCom} -c patonly2m.c

min_cds_len.o: min_cds_len.c global_st.h atg_func.h
	${CompCom} -c min_cds_len.c

eliatg.o: eliatg.c global_st.h atg_func.h
	${CompCom} -c eliatg.c

trsite5.o: trsite5.c global_st.h atg_func.h
	${CompCom} -c trsite5.c

icisl.o: icisl.c global_st.h atg_func.h
	${CompCom} -c icisl.c

lkatgav.o: lkatgav.c global_st.h atg_func.h
	${CompCom} -c lkatgav.c

junkget.o: junkget.c global_st.h atg_func.h
	${CompCom} -c junkget.c

atcgcon.o: atcgcon.c global_st.h atg_func.h
	${CompCom} -c atcgcon.c

utrcds_gc.o: utrcds_gc.c global_st.h atg_func.h
	${CompCom} -c utrcds_gc.c

cDNA_5utr_atg.o: cDNA_5utr_atg.c global_st.h atg_func.h
	${CompCom} -c cDNA_5utr_atg.c

trterm.o: trterm.c global_st.h atg_func.h
	${CompCom} -c trterm.c

hfindpat.o: hfindpat.c global_st.h atg_func.h
	${CompCom} -c hfindpat.c

pseudo_atg.o: pseudo_atg.c global_st.h atg_func.h
	${CompCom} -c pseudo_atg.c

scan_2d.o: scan_2d.c global_st.h atg_func.h
	${CompCom} -c scan_2d.c

scan_stem.o: scan_stem.c global_st.h atg_func.h
	${CompCom} -c scan_stem.c

scan_bstem.o: scan_bstem.c global_st.h atg_func.h
	${CompCom} -c scan_bstem.c

scan_mstem.o: scan_mstem.c global_st.h atg_func.h
	${CompCom} -c scan_mstem.c


sdwin.o: sdwin.c global_st.h atg_func.h
	${CompCom} -c sdwin.c

cyaex.o: cyaex.c global_st.h
	${CompCom} -c cyaex.c

palind.o: palind.c global_st.h atg_func.h
	${CompCom} -c palind.c

palind2.o: palind2.c global_st.h atg_func.h
	${CompCom} -c palind2.c

palind3.o: palind3.c global_st.h atg_func.h
	${CompCom} -c palind3.c

palind4.o: palind4.c global_st.h atg_func.h
	${CompCom} -c palind4.c

cds_echo.o: cds_echo.c global_st.h atg_func.h 
	${CompCom} -c cds_echo.c

patfind.o: patfind.c global_st.h atg_func.h
	${CompCom} -c patfind.c

colcal.o: colcal.c colcalh.c global_st.h atg_func.h
	${CompCom} -c colcal.c

orfsearch.o: orfsearch.c global_st.h atg_func.h
	${CompCom} -c orfsearch.c

rand_pro.o: rand_pro.c global_st.h atg_func.h
	${CompCom} -c rand_pro.c

idinuc_count.o: idinuc_count.c global_st.h atg_func.h
	${CompCom} -c idinuc_count.c

dash3.o: dash3.c global_st.h atg_func.h
	${CompCom} -c dash3.c

clean:
	rm *.o




