/*
 Copyright (c) 2006,2010 The Cytoscape Consortium (www.cytoscape.org)

 The Cytoscape Consortium is:
 - Institute for Systems Biology
 - University of California San Diego
 - Memorial Sloan-Kettering Cancer Center
 - Institut Pasteur
 - Agilent Technologies

 This library is free software; you can redistribute it and/or modify it
 under the terms of the GNU Lesser General Public License as published
 by the Free Software Foundation; either version 2.1 of the License, or
 any later version.

 This library is distributed in the hope that it will be useful, but
 WITHOUT ANY WARRANTY, WITHOUT EVEN THE IMPLIED WARRANTY OF
 MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.  The software and
 documentation provided hereunder is on an "as is" basis, and the
 Institute for Systems Biology and the Whitehead Institute
 have no obligations to provide maintenance, support,
 updates, enhancements or modifications.  In no event shall the
 Institute for Systems Biology and the Whitehead Institute
 be liable to any party for direct, indirect, special,
 incidental or consequential damages, including lost profits, arising
 out of the use of this software and its documentation, even if the
 Institute for Systems Biology and the Whitehead Institute
 have been advised of the possibility of such damage.  See
 the GNU Lesser General Public License for more details.

 You should have received a copy of the GNU Lesser General Public License
 along with this library; if not, write to the Free Software Foundation,
 Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA.
 */

package org.cytoscape.io.internal.write.session;

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.net.URISyntaxException;
import java.net.URLEncoder;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.zip.ZipEntry;
import java.util.zip.ZipOutputStream;

import javax.xml.bind.JAXBException;
import javax.xml.stream.XMLStreamException;

import org.cytoscape.io.CyFileFilter;
import org.cytoscape.io.write.CyNetworkViewWriterManager;
import org.cytoscape.io.write.CyPropertyWriterManager;
import org.cytoscape.io.write.CyTableWriterManager;
import org.cytoscape.io.write.CyWriter;
import org.cytoscape.model.CyNetwork;
import org.cytoscape.model.CyTable;
import org.cytoscape.property.session.Cysession;
import org.cytoscape.property.session.Cytopanels;
import org.cytoscape.property.session.Network;
import org.cytoscape.property.session.NetworkTree;
import org.cytoscape.property.session.Plugins;
import org.cytoscape.property.session.SessionState;
import org.cytoscape.session.CySession;
import org.cytoscape.view.model.CyNetworkView;
import org.cytoscape.work.AbstractTask;
import org.cytoscape.work.TaskMonitor;

/**
 * Write session states into files.<br>
 * Basic functions of this class are:<br>
 * <ul>
 * <li> 1. Create network files</li>
 * <li> 2. Create session state file</li>
 * <li> 3. Get properties file locations</li>
 * <li> 4. Zip them into one session file "*.cys" </li>
 * </ul>
 *
 * @version 1.0
 * @since 2.3
 * @see cytoscape.data.readers.XGMMLReader
 * @author kono
 *
 */
public class SessionWriterImpl extends AbstractTask implements CyWriter {

	// These values will be replaced.
	private static final char[] INVALID_CHAR = {'[', '\\', '/', ':', '*', '?', 
	                                            '"', '<', '>', '|', ']'};
	
	// cysession.xml document version
	private static final String cysessionVersion = "0.9";

	// Enumerate types (node & edge)
	public static final int NODE = 1;

	public static final int EDGE = 2;
	private static final String DEFAULT_VS_NAME = "default";

	// Number of Cytopanels. Currently, we have 3 panels.
	private static final int CYTOPANEL_COUNT = 3;

	// Number of setting files in the cys file.
	// For now, we have cysession.xml, vizmap.prop, cytoscape.prop, and
	// bookmarks.
	private static final int SETTING_FILE_COUNT = 4;

	// Name of CySession file.
	private static final String CYSESSION_FILE_NAME = "cysession.xml";
	private static final String VIZMAP_FILE = "session_vizmap.props";
	private static final String CYPROP_FILE = "session_cytoscape.props";
	private static final String BOOKMARKS_FILE = "session_bookmarks.xml";

	// Extension for the xgmml file
	private static final String XGMML_EXT = ".xgmml";

	// Package name generated by JAXB.
	// This file was created from "cysession.schema"
	private final String packageName = "org.cytoscape.io.internal.generated";

	// Root of the network tree
	private static final String TREE_ROOT = "root";

	// File name for the session
	private Map<String,Long> networkMap;
	private String sessionNote = "You can add note for this session here.";

	// The following are JAXB-generated objects defined in CySession.xml. 
//	private ObjectFactory factory;
	private Cysession cysession;
	private NetworkTree tree;
	private SessionState sState;
	private List<Network> netList;
	private Cytopanels cytoPanels;
	private Plugins plugins;

	private final String sessionDirName;
	private final String sessionDir;
	private ZipOutputStream zos; 
	private TaskMonitor taskMonitor;

	private final OutputStream outputStream;
	private final CySession session;
	private final CyNetworkViewWriterManager networkViewWriterMgr;
	private final CyPropertyWriterManager propertyWriterMgr;
	private final CyTableWriterManager tableWriterMgr;
	private final CyFileFilter xgmmlFilter;
	private final CyFileFilter bookmarksFilter;
	private final CyFileFilter cysessionFilter;
	private final CyFileFilter propertiesFilter;
	private final CyFileFilter tableFilter;

	public SessionWriterImpl(final OutputStream outputStream, 
	                         final CySession session, 
	                         final CyNetworkViewWriterManager networkViewWriterMgr, 
	                         final CyPropertyWriterManager propertyWriterMgr,
	                         final CyTableWriterManager tableWriterMgr,
	                         final CyFileFilter xgmmlFilter, 
	                         final CyFileFilter bookmarksFilter,
	                         final CyFileFilter cysessionFilter,
	                         final CyFileFilter propertiesFilter,
	                         final CyFileFilter tableFilter) {
		this.outputStream = outputStream;
		this.session = session;
		this.networkViewWriterMgr = networkViewWriterMgr;
		this.propertyWriterMgr = propertyWriterMgr;
		this.tableWriterMgr = tableWriterMgr;
		this.xgmmlFilter = xgmmlFilter;
		this.bookmarksFilter = bookmarksFilter;
		this.cysessionFilter = cysessionFilter;
		this.propertiesFilter = propertiesFilter;
		this.tableFilter = tableFilter;

		// For now, session ID is time and date
		final DateFormat df = new SimpleDateFormat("yyyy_MM_dd-HH_mm");
		sessionDirName = "CytoscapeSession-" + df.format(new Date()); 
		sessionDir = sessionDirName + "/"; 

		networkMap = new HashMap<String,Long>();
	}


	/**
	 * Write current session to a local .cys file.
	 *
	 * @throws Exception
	 */
	@Override
	public void run(TaskMonitor taskMonitor) throws Exception {
		this.taskMonitor = taskMonitor;
		
		zos = new ZipOutputStream(outputStream); 

		for (CyNetworkView netView : session.getNetworkViews())
			zipNetwork(netView);
		zipGlobalTables();
		zipCySession();
		zipVizmapProps();
		zipCytoscapeProps();
		zipBookmarks();
		zipFileListMap();

		zos.close();
	}


	/**
	 * Writes the vizmap.props file to the session zip.
	 */
	private void zipVizmapProps() throws Exception {

		zos.putNextEntry(new ZipEntry(sessionDir + VIZMAP_FILE) );

		CyWriter propertiesWriter = propertyWriterMgr.getWriter(session.getVizmapProperties(), propertiesFilter, zos );
		propertiesWriter.run(taskMonitor);

		zos.closeEntry();

		propertiesWriter = null;
	}

	/**
	 * Writes the cytoscape.props file to the session zip.
	 */
	private void zipCytoscapeProps() throws Exception {
	
		zos.putNextEntry(new ZipEntry(sessionDir + CYPROP_FILE) );

		CyWriter propertiesWriter = propertyWriterMgr.getWriter(session.getCytoscapeProperties(), propertiesFilter, zos );
		propertiesWriter.run(taskMonitor);

		zos.closeEntry();

		propertiesWriter = null;
	}

	/**
	 * Writes the bookmarks.xml file to the session zip.
	 */
	private void zipBookmarks() throws Exception {

		zos.putNextEntry(new ZipEntry(sessionDir + BOOKMARKS_FILE) );

		CyWriter bookmarksWriter = propertyWriterMgr.getWriter(session.getBookmarks(), bookmarksFilter, zos );
		bookmarksWriter.run(taskMonitor);

		zos.closeEntry();

		bookmarksWriter = null;
	}

	/**
	 * Writes a network file to the session zip. 
	 *
	 * @throws URISyntaxException
	 * @throws JAXBException
	 * @throws XMLStreamException
	 */
	private void zipNetwork(final CyNetworkView view) throws Exception {
		final CyNetwork network = view.getModel();

		String xgmmlFile = getValidFileName( network.getCyRow().get("name",String.class) + XGMML_EXT );
		zos.putNextEntry(new ZipEntry(sessionDir + xgmmlFile) );

		// Write the XGMML file *without* our graphics attributes
		// We'll let the Vizmapper handle those
		CyWriter xgmmlWriter = networkViewWriterMgr.getWriter(view, xgmmlFilter, zos );
		xgmmlWriter.run(taskMonitor);

		zos.closeEntry();

		xgmmlWriter = null;
	}

	/**
	 * Create cysession.xml file.
	 *
	 * @throws Exception
	 */
	private void zipCySession() throws Exception {
		zos.putNextEntry(new ZipEntry(sessionDir + CYSESSION_FILE_NAME) );

		CyWriter cysessionWriter = propertyWriterMgr.getWriter(session.getCysession(), cysessionFilter, zos );
		cysessionWriter.run(taskMonitor);

		zos.closeEntry();

		cysessionWriter = null;
	}

	/**
	 * Writes any files from plugins to the session file.
	 *
	 * @throws IOException
	 */
	private void zipFileListMap() throws IOException {

		// fire an event to tell plugins we're ready to save!
		Map<String, List<File>> pluginFileMap = session.getPluginFileListMap(); 

		// now write any files to the zip files
		if ((pluginFileMap != null) && (pluginFileMap.size() > 0)) {
			byte[] buf = new byte[5000];
			Set<String> pluginSet = pluginFileMap.keySet();
		
			for (String pluginName : pluginSet) {
				List<File> theFileList = (List<File>) pluginFileMap.get(pluginName);
		
				if ((theFileList == null) || (theFileList.size() == 0))
					continue;
	
				for (File theFile : theFileList) {
					if ((theFile == null) || (!theFile.exists()))
						continue;
	
					zos.putNextEntry(new ZipEntry( sessionDir + "plugins/" + pluginName + 
					                               "/" + theFile.getName() ) );

					// copy the file contents to the zip output stream
					FileInputStream fileIS = new FileInputStream(theFile);
					int numRead = 0;
			        while ((numRead = fileIS.read(buf)) > -1)
		            	zos.write(buf, 0, numRead);
					fileIS.close();

					zos.closeEntry();
				}
			}
		}
	}

	/**
	 * Utility to replace invalid chars in the XGMML file name.<br>
	 *
	 * @param fileName
	 *            Original file name directly taken from the title.
	 * @return Modified file name without invalid chars.
	 *
	 */
	private String getValidFileName(String fileName) {
		
		String newFileName = fileName;
		Integer i = 0;
		for(Character ch : INVALID_CHAR) 
			newFileName = newFileName.replace(ch.toString(), (i++).toString());
		
		return newFileName;
	}

	private void zipGlobalTables() throws Exception {
		Set<CyNetworkView> views = session.getNetworkViews();
		Set<Long> excluded = new HashSet<Long>();
		for (CyNetworkView view : views) {
			CyNetwork network = view.getModel();
			excluded.add(network.getDefaultNetworkTable().getSUID());
			excluded.add(network.getDefaultNodeTable().getSUID());
			excluded.add(network.getDefaultEdgeTable().getSUID());
		}
		Set<CyTable> tables = session.getTables();
		for (CyTable table : tables) {
			if (excluded.contains(table.getSUID())) {
				continue;
			}
			
			String fileName = String.format("%d|%s.table", table.getSUID(), URLEncoder.encode(table.getTitle(), "UTF-8"));
			zos.putNextEntry(new ZipEntry(sessionDir + fileName));
			try {
				CyWriter writer = tableWriterMgr.getWriter(table, tableFilter, zos);
				writer.run(taskMonitor);
			} finally {
				zos.closeEntry();
			}
		}
	}

}
