package org.eclipse.equinox.internal.provisional.p2.ui2.dialogs;

import javax.swing.JDialog;
import javax.swing.JLabel;

import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;

public class PropertiesDialog extends JDialog implements ActionListener, MouseListener {

	public PropertiesDialog(){
		initComponents();
		
		btnOK.addActionListener(this);
		btnCancel.addActionListener(this);
		
		lbCopyright.addMouseListener(this);
		lbGeneralInformation.addMouseListener(this);
		lbLicenseAgreement.addMouseListener(this);
		
		pnlCopyright.setVisible(true);
		pnlGeneralInformation.setVisible(false);
		pnlLicenseAgreement.setVisible(false);
		
	}
	
	// action listener
	public void actionPerformed(ActionEvent e){
		this.dispose();
	}
	
	// mouse listener
	public void mouseClicked(MouseEvent e) {
		if (e.getSource() instanceof JLabel){
			JLabel lb = (JLabel)e.getSource();
			if (lb == lbCopyright){
				System.out.println("lbCopyright is clicked");
				pnlCopyright.setVisible(true);
				pnlGeneralInformation.setVisible(false);
				pnlLicenseAgreement.setVisible(false);

			}
			else if (lb == lbGeneralInformation){
				System.out.println("lbGeneralInformation is clicked");
				pnlCopyright.setVisible(false);
				pnlGeneralInformation.setVisible(true);
				pnlLicenseAgreement.setVisible(false);

			}
			else if (lb == lbLicenseAgreement){
				System.out.println("lbLicenseAgreement is clicked");
				pnlCopyright.setVisible(false);
				pnlGeneralInformation.setVisible(false);
				pnlLicenseAgreement.setVisible(true);
				
			}
		}
	}
	
	public void mouseEntered(MouseEvent e) {}
	public void mouseExited(MouseEvent e) {}
	public void mousePressed(MouseEvent e) {}
	public void mouseReleased(MouseEvent e) {}

	
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">                          
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        lbCopyright = new javax.swing.JLabel();
        lbGeneralInformation = new javax.swing.JLabel();
        lbLicenseAgreement = new javax.swing.JLabel();
        lbPlaceHolder = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlCopyright = new javax.swing.JPanel();
        lbTitleCopyright = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taCopyright = new javax.swing.JTextArea();
        pnlGeneralInformation = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbName = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbIdentifier = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbVersion = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        pnlLicenseAgreement = new javax.swing.JPanel();
        lbTitleLicenseAgreement = new javax.swing.JLabel();
        taLicenseAgreement = new javax.swing.JTextArea();
        pnlButtons = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnOK = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        getContentPane().setLayout(new java.awt.GridBagLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(204, 204, 204)));
        lbCopyright.setText("Copyright");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 5, 10);
        jPanel1.add(lbCopyright, gridBagConstraints);

        lbGeneralInformation.setText("General Information");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 20);
        jPanel1.add(lbGeneralInformation, gridBagConstraints);

        lbLicenseAgreement.setText("License Agreement");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 20);
        jPanel1.add(lbLicenseAgreement, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(lbPlaceHolder, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 0, 5);
        getContentPane().add(jPanel1, gridBagConstraints);

        pnlCopyright.setLayout(new java.awt.GridBagLayout());

        lbTitleCopyright.setFont(new java.awt.Font("Tahoma", 1, 12));
        lbTitleCopyright.setText("Copyright");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 5, 5);
        pnlCopyright.add(lbTitleCopyright, gridBagConstraints);

        taCopyright.setColumns(20);
        taCopyright.setRows(5);
        taCopyright.setText("No copyright information has been provided");
        jScrollPane2.setViewportView(taCopyright);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        pnlCopyright.add(jScrollPane2, gridBagConstraints);

        jScrollPane1.setViewportView(pnlCopyright);

        pnlGeneralInformation.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel2.setText("General Information");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 20, 5);
        pnlGeneralInformation.add(jLabel2, gridBagConstraints);

        jLabel3.setText("Name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        pnlGeneralInformation.add(jLabel3, gridBagConstraints);

        lbName.setText("Cytoscape");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 5, 0);
        pnlGeneralInformation.add(lbName, gridBagConstraints);

        jLabel5.setText("Identifier:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        pnlGeneralInformation.add(jLabel5, gridBagConstraints);

        lbIdentifier.setText("org....product");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 5, 0);
        pnlGeneralInformation.add(lbIdentifier, gridBagConstraints);

        jLabel7.setText("Version:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        pnlGeneralInformation.add(jLabel7, gridBagConstraints);

        lbVersion.setText("3.0.0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        pnlGeneralInformation.add(lbVersion, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        pnlGeneralInformation.add(jLabel9, gridBagConstraints);

        jScrollPane1.setViewportView(pnlGeneralInformation);

        pnlLicenseAgreement.setLayout(new java.awt.GridBagLayout());

        lbTitleLicenseAgreement.setFont(new java.awt.Font("Tahoma", 1, 12));
        lbTitleLicenseAgreement.setText("License Agreement");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pnlLicenseAgreement.add(lbTitleLicenseAgreement, gridBagConstraints);

        taLicenseAgreement.setColumns(20);
        taLicenseAgreement.setRows(5);
        taLicenseAgreement.setText("No License information has ben provided.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
        pnlLicenseAgreement.add(taLicenseAgreement, gridBagConstraints);

        jScrollPane1.setViewportView(pnlLicenseAgreement);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 5);
        getContentPane().add(jScrollPane1, gridBagConstraints);

        pnlButtons.setLayout(new java.awt.GridBagLayout());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        pnlButtons.add(jLabel1, gridBagConstraints);

        btnOK.setText("OK");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 10);
        pnlButtons.add(btnOK, gridBagConstraints);

        btnCancel.setText("Cancel");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 10);
        pnlButtons.add(btnCancel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(pnlButtons, gridBagConstraints);

        pack();
    }// </editor-fold>                        
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PropertiesDialog().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify                     
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbCopyright;
    private javax.swing.JLabel lbGeneralInformation;
    private javax.swing.JLabel lbIdentifier;
    private javax.swing.JLabel lbLicenseAgreement;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbPlaceHolder;
    private javax.swing.JLabel lbTitleCopyright;
    private javax.swing.JLabel lbTitleLicenseAgreement;
    private javax.swing.JLabel lbVersion;
    private javax.swing.JPanel pnlButtons;
    private javax.swing.JPanel pnlCopyright;
    private javax.swing.JPanel pnlGeneralInformation;
    private javax.swing.JPanel pnlLicenseAgreement;
    private javax.swing.JTextArea taCopyright;
    private javax.swing.JTextArea taLicenseAgreement;
    // End of variables declaration                   
	
 
}
