package org.eclipse.equinox.internal.provisional.p2.ui2.dialogs;

import javax.swing.JDialog;
import javax.swing.JComponent;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.JButton;

public class RepositoryManipulationDialog extends JDialog implements ActionListener {

	
    /** Creates new form RepositoryManipulationPage */
    public RepositoryManipulationDialog(JComponent parent, boolean modal) {
        //super(parent, modal);
        initComponents();

        btnOK.addActionListener(this);
        btnCancel.addActionListener(this);
        
        btnAdd.addActionListener(this);
        btnRemove.addActionListener(this);
        btnTestConnection.addActionListener(this);
        btnEnable.addActionListener(this);
        btnExport.addActionListener(this);
        btnImport.addActionListener(this);

    }
    
    public void actionPerformed(ActionEvent e) {
    	if (e.getSource() instanceof JButton){
    		JButton btn = (JButton) e.getSource();
    		
    		if (btn == btnOK){
    			System.out.println("btnOK is pressed!");
    		}
    		else if (btn == btnCancel){
    			System.out.println("btnCancel is pressed!");
    			this.dispose();
    		}
    		else if (btn == btnAdd){
    			System.out.println("btnAdd is pressed!");
    		}
    		else if (btn == btnRemove){
    			System.out.println("btnRemove is pressed!");
    		}
    		else if (btn == btnTestConnection){
    			System.out.println("btntestConnection is pressed!");
    		}
    		else if (btn == btnEnable){
    			System.out.println("btnEnable is pressed!");
    		}
    		else if (btn == btnImport){
    			System.out.println("btnImport is pressed!");
    		}
    		else if (btn == btnExport){
    			System.out.println("btnExport is pressed!");
    		}
    		
    	}
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">                          
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lbTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSites = new javax.swing.JTable();
        pnlButton_right = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        btnTestConnection = new javax.swing.JButton();
        btnEnable = new javax.swing.JButton();
        btnImport = new javax.swing.JButton();
        btnExport = new javax.swing.JButton();
        pnlButton_bottom = new javax.swing.JPanel();
        btnOK = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        getContentPane().setLayout(new java.awt.GridBagLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        lbTitle.setFont(new java.awt.Font("Tahoma", 1, 14));
        lbTitle.setText("Available Software sites");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(20, 10, 20, 0);
        getContentPane().add(lbTitle, gridBagConstraints);

        tblSites.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name", "Location", "Enabled"
            }
        ));
        jScrollPane1.setViewportView(tblSites);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        getContentPane().add(jScrollPane1, gridBagConstraints);

        pnlButton_right.setLayout(new java.awt.GridBagLayout());

        btnAdd.setText("Add...");
        btnAdd.setPreferredSize(new java.awt.Dimension(113, 23));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pnlButton_right.add(btnAdd, gridBagConstraints);

        btnRemove.setText("Remove");
        btnRemove.setPreferredSize(new java.awt.Dimension(113, 23));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
        pnlButton_right.add(btnRemove, gridBagConstraints);

        btnTestConnection.setText("Test Connection");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
        pnlButton_right.add(btnTestConnection, gridBagConstraints);

        btnEnable.setText("Enable");
        btnEnable.setPreferredSize(new java.awt.Dimension(113, 23));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
        pnlButton_right.add(btnEnable, gridBagConstraints);

        btnImport.setText("Import");
        btnImport.setPreferredSize(new java.awt.Dimension(113, 23));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
        pnlButton_right.add(btnImport, gridBagConstraints);

        btnExport.setText("Export");
        btnExport.setPreferredSize(new java.awt.Dimension(113, 23));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 5;
        pnlButton_right.add(btnExport, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        getContentPane().add(pnlButton_right, gridBagConstraints);

        pnlButton_bottom.setLayout(new java.awt.GridBagLayout());

        btnOK.setText("OK");
        btnOK.setPreferredSize(new java.awt.Dimension(67, 23));
        pnlButton_bottom.add(btnOK, new java.awt.GridBagConstraints());

        btnCancel.setText("Cancel");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        pnlButton_bottom.add(btnCancel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        getContentPane().add(pnlButton_bottom, gridBagConstraints);

        pack();
    }// </editor-fold>                        
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RepositoryManipulationDialog(null, true).setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify                     
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnEnable;
    private javax.swing.JButton btnExport;
    private javax.swing.JButton btnImport;
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnTestConnection;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JPanel pnlButton_bottom;
    private javax.swing.JPanel pnlButton_right;
    private javax.swing.JTable tblSites;
    // End of variables declaration                   
    
	
}
