
package org.cytoscape.io.write;

import org.cytoscape.work.AbstractTask;
import org.cytoscape.work.TaskMonitor;
import org.cytoscape.work.Tunable;
import org.cytoscape.work.util.ListSingleSelection;
import org.cytoscape.io.CyFileFilter;
import java.io.File;

import java.util.Map;
import java.util.TreeMap;
import java.util.ArrayList;

/**
 * An abstract utility implementation of a Task that writes a user defined 
 * file to a file type determined by a provided writer manager.  This class
 * is meant to be extended for specific file types such that the appropriate
 * CyWriter can be identified.
 */
public abstract class AbstractCyWriter<T extends CyWriterManager> extends AbstractTask 
	implements CyWriter {

	private File outputFile;

	/**
	 * The method sets the file to be written.  This field should not
	 * be called directly, but rather handled by the {@link Tunable}
	 * processing. This method is the "setter" portion of a
	 * getter/setter tunable method pair.
	 * @param f The file to be written.
	 */
	public final void setOutputFile(File f) {
		if ( f != null )
			outputFile = f;
	}

	/**
	 * This method gets the file to be written.  This method should not
	 * be called directly, but rather handled by the {@link Tunable}
	 * processing. This method is the "getter" portion of a
	 * getter/setter tunable method pair.
	 * @return The file to be written.
	 */
	@Tunable(description="Select the output file name")
	public final File getOutputFile() {
		return outputFile;
	}

	/**
	 * The list of file type options generated by the file types
	 * available from the CyWriterManager.  This field should not
	 * be set directly, but rather handled by the {@link Tunable}
	 * processing.
	 */
	@Tunable(description = "Select the export file format")
	public final ListSingleSelection<String> options;

	private final Map<String,CyFileFilter> descriptionFilterMap;

	/**
	 * The CyWriterManager specified in the constructor.
	 */
	protected final T writerManager;

	/**
	 * @param writerManager The CyWriterManager to be used to determine which
	 * CyWriter to be used to write the file chosen by the user. 
	 */
	public AbstractCyWriter(T writerManager) {
		if ( writerManager == null )
			throw new NullPointerException("CyWriterManager is null");
		this.writerManager = writerManager;

		descriptionFilterMap = new TreeMap<String,CyFileFilter>();
		for ( CyFileFilter f : writerManager.getAvailableWriters() )
			descriptionFilterMap.put( f.getDescription(), f );
   
		options = new ListSingleSelection<String>( new ArrayList<String>( descriptionFilterMap.keySet() ) );
	}

	/**
	 * This method processes the chosesn input file and output type and attempts
	 * to write the file.
	 * @param tm The TaskMonitor provided by the TaskManager execution environment.
	 */
	public final void run(TaskMonitor tm) throws Exception {
		if ( outputFile == null )
			throw new NullPointerException("Output file has not be specified!");

		String desc = options.getSelectedValue();
		if ( desc == null )
			throw new NullPointerException("No file type has been specified!");

		CyFileFilter filter = descriptionFilterMap.get(desc);
		if ( filter == null )
			throw new NullPointerException("No file filter found for specified file type!");
		
		CyWriter writer = getWriter(filter,outputFile); 
		if ( writer == null )
			throw new NullPointerException("No CyWriter found for specified file type!");

		insertTasksAfterCurrentTask( writer );
	}

	/**
	 * Should return a CyWriter object for writing the specified file of the specified type.
	 * @param filter The specific type of file to be written.
	 * @param out The file that will be written.
	 */
	protected abstract CyWriter getWriter(CyFileFilter filter, File out) throws Exception;

}
