package org.cytoscape.io.write;

import java.io.IOException;

import org.cytoscape.io.FileIOFactory;
import org.cytoscape.model.CyTable;

/**
 * A specialization of CyWriterFactory that allows a CyTable to
 * be specified and written.
 */
public interface CyTableWriterFactory extends CyWriterFactory {

	/**
	 * Specifies the CyTable to be written by the CyWriter Task
	 * generated by this factory.  This method must be called 
	 * prior to calling the getWriter() method.
	 * @param table The CyTable to be written.
	 */
	void setTable(CyTable table);
}
