sif=network.sif
gml=network.gml
noa=age.noa
noa=commonName.noa
noa=frillycurtainlength.noa
noa=species.noa
eda=edgeancillaryname.eda
eda=edgeweight.eda
eda=interaction.eda
expr=yabba.mrna
dataServer=jar://privateServer
species=Saccharomyces cerevisiae
layout=frisbee
props=special.props
vprops=vspecial.props
canonicalizeNames=no
arg=more
arg=args
