package org.cytoscape.io.write;

import org.cytoscape.model.CyNetwork;
import org.cytoscape.view.model.CyNetworkView;

public interface CyNetworkViewWriterContext extends CyWriterContext {

	/**
	 * Specifies the {@link CyNetwork} to be written by the 
	 * {@link CyWriter} Task generated by this factory.  This method must be called 
	 * prior to calling the getWriter() method.
	 * @param view The {@link CyNetworkView} to be written.
	 */
	void setNetwork(CyNetwork network);

	CyNetwork getNetwork();

	/**
	 * Specifies the {@link CyNetworkView} to be written by the 
	 * {@link CyWriter} Task generated by this factory.  This method must be called 
	 * prior to calling the getWriter() method.
	 * @param view The {@link CyNetworkView} to be written.
	 */
	void setNetworkView(CyNetworkView view);

	CyNetworkView getNetworkView();

}
