Aa_test1: Aa_test1.c Assoc_array.o ../Usefuls/Assoc_array.h
	g++ Aa_test1.c Assoc_array.o -o Aa_test1

Assoc_array.o:
	g++ -c -DNOMAIN ../Usefuls/Assoc_array.c

clean:
	touch Assoc_array.o; rm Assoc_array.o; \
        touch Aa_test1; rm Aa_test1
