/* File: AttributeBasedIDMappingDialog.java

 Copyright (c) 2006, 2007, The Cytoscape Consortium (www.cytoscape.org)

 The Cytoscape Consortium is:
 - Institute for Systems Biology
 - University of California San Diego
 - Memorial Sloan-Kettering Cancer Center
 - Institut Pasteur
 - Agilent Technologies

 This library is free software; you can redistribute it and/or modify it
 under the terms of the GNU Lesser General Public License as published
 by the Free Software Foundation; either version 2.1 of the License, or
 any later version.

 This library is distributed in the hope that it will be useful, but
 WITHOUT ANY WARRANTY, WITHOUT EVEN THE IMPLIED WARRANTY OF
 MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.  The software and
 documentation provided hereunder is on an "as is" basis, and the
 Institute for Systems Biology and the Whitehead Institute
 have no obligations to provide maintenance, support,
 updates, enhancements or modifications.  In no event shall the
 Institute for Systems Biology and the Whitehead Institute
 be liable to any party for direct, indirect, special,
 incidental or consequential damages, including lost profits, arising
 out of the use of this software and its documentation, even if the
 Institute for Systems Biology and the Whitehead Institute
 have been advised of the possibility of such damage.  See
 the GNU Lesser General Public License for more details.

 You should have received a copy of the GNU Lesser General Public License
 along with this library; if not, write to the Free Software Foundation,
 Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA.
 */

package csplugins.id.mapping.ui;

import csplugins.id.mapping.model.AttributeBasedIDMappingData;
import csplugins.id.mapping.model.AttributeBasedIDMappingDataImpl;

import cytoscape.cythesaurus.service.CyThesaurusServiceClient;
import cytoscape.cythesaurus.service.CyThesaurusServiceMessageBasedClient;

import java.util.Map;
import java.util.Set;

import java.awt.Frame;

/**
 *
 * @author gjj
 */
public class AttributeBasedIDMappingDialog extends javax.swing.JDialog {

    /** Creates new form AttributeBasedIDMappingDialog */
    public AttributeBasedIDMappingDialog(java.awt.Frame parent,
                                boolean modal,
                                Map<String,Set<String>> selectedNetworkAttribute,
                                boolean isNode) {
        super(parent, modal);
        this.frame = parent;
        this.selectedNetworkAttribute = selectedNetworkAttribute;
        this.isNode = isNode;

        cancelled = true;

        idMapping = new AttributeBasedIDMappingDataImpl();

        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        idMappingPane = new javax.swing.JTabbedPane();
        optionPanel = new javax.swing.JPanel();
        optionButton = new javax.swing.JButton();
        previewButton = new javax.swing.JButton();
        javax.swing.JPanel okPanel = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ID Mapping");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        idMappingPane.setMinimumSize(new java.awt.Dimension(400, 200));
        idMappingPane.setPreferredSize(new java.awt.Dimension(600, 400));

        idMappingFilePanel = new csplugins.id.mapping.ui.AttributeBasedIDMappingPanel(frame,this,selectedNetworkAttribute,isNode);
        idMappingPane.addTab("From file", idMappingFilePanel);
        //idMappingPane.addTab("From database", new csplugins.id.mapping.ui.AttributeBasedIDMappingFilePanel(frame,this,selectedNetworkAttribute,isNode));
        //idMappingPane.addTab("From webservice", new csplugins.id.mapping.ui.AttributeBasedIDMappingFilePanel(frame,this,selectedNetworkAttribute,isNode));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(idMappingPane, gridBagConstraints);

        optionPanel.setLayout(new javax.swing.BoxLayout(optionPanel, javax.swing.BoxLayout.LINE_AXIS));

        //optionDialog = new NetworkMergeOptionDialog(frame,true);
        //optionDialog.pack();
        optionButton.setText("Configure ID Mapping Resources");
        optionButton.setToolTipText("Click to set up options");
        optionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionButtonActionPerformed(evt);
            }
        });
        optionPanel.add(optionButton);

        previewButton.setText("Preview");
        previewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previewButtonActionPerformed(evt);
            }
        });
        optionPanel.add(previewButton);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(optionPanel, gridBagConstraints);

        okPanel.setLayout(new javax.swing.BoxLayout(okPanel, javax.swing.BoxLayout.LINE_AXIS));

        okButton.setText("Close");
        okButton.setToolTipText("");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        okPanel.add(okButton);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(okPanel, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void optionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionButtonActionPerformed
            CyThesaurusServiceClient client = new CyThesaurusServiceMessageBasedClient("AdvancedNetworkMerge");
            if (!client.openMappingResourceConfigDialog()) {
                //javax.swing.JOptionPane.showMessageDialog(this, "Failed to open the configuration dialog.");
            } else {
                idMappingFilePanel.mappingResourcesChanged();
            }
    }//GEN-LAST:event_optionButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
            cancelled = false;
            setVisible(false);
    }//GEN-LAST:event_okButtonActionPerformed

    private void previewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previewButtonActionPerformed
            IDMappingPreviewDialog dialog = new IDMappingPreviewDialog(frame,true,idMapping);
            dialog.setLocationRelativeTo(this);
            dialog.setVisible(true);

//            setOKButtonEnable();
    }//GEN-LAST:event_previewButtonActionPerformed

public boolean isCancelled() {
    return cancelled;
}

public AttributeBasedIDMappingData getIDMapping() {
        return this.idMapping;
}

//void setOKButtonEnable() {
//        if (idMapping.isEmpty()) {
//                okButton.setEnabled(false);
//                okButton.setToolTipText("No ID mapping has been imported.");
//        } else {
//                okButton.setEnabled(true);
//                okButton.setToolTipText(null);
//        }
//}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane idMappingPane;
    private csplugins.id.mapping.ui.AttributeBasedIDMappingPanel idMappingFilePanel;
    private javax.swing.JButton okButton;
    private javax.swing.JButton optionButton;
    //private NetworkMergeOptionDialog optionDialog;
    private javax.swing.JPanel optionPanel;
    private javax.swing.JButton previewButton;
    // End of variables declaration//GEN-END:variables

        private boolean cancelled;
        private Frame frame;
        private Map<String,Set<String>> selectedNetworkAttribute;
        private AttributeBasedIDMappingData idMapping;
        private boolean isNode;
}
