
/*
 Copyright (c) 2006, 2007, The Cytoscape Consortium (www.cytoscape.org)

 The Cytoscape Consortium is:
 - Institute for Systems Biology
 - University of California San Diego
 - Memorial Sloan-Kettering Cancer Center
 - Institut Pasteur
 - Agilent Technologies

 This library is free software; you can redistribute it and/or modify it
 under the terms of the GNU Lesser General Public License as published
 by the Free Software Foundation; either version 2.1 of the License, or
 any later version.

 This library is distributed in the hope that it will be useful, but
 WITHOUT ANY WARRANTY, WITHOUT EVEN THE IMPLIED WARRANTY OF
 MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.  The software and
 documentation provided hereunder is on an "as is" basis, and the
 Institute for Systems Biology and the Whitehead Institute
 have no obligations to provide maintenance, support,
 updates, enhancements or modifications.  In no event shall the
 Institute for Systems Biology and the Whitehead Institute
 be liable to any party for direct, indirect, special,
 incidental or consequential damages, including lost profits, arising
 out of the use of this software and its documentation, even if the
 Institute for Systems Biology and the Whitehead Institute
 have been advised of the possibility of such damage.  See
 the GNU Lesser General Public License for more details.

 You should have received a copy of the GNU Lesser General Public License
 along with this library; if not, write to the Free Software Foundation,
 Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA.
*/

package cytoscape.visual.ui.editors.continuous;

import cytoscape.Cytoscape;


/**
 *
 * @author  kono
 */
public class MinMaxDialog extends javax.swing.JDialog {
	
	private static MinMaxDialog dialog;
	
	/** Creates new form MinMaxDialog */
	private MinMaxDialog(java.awt.Frame parent, boolean modal, Double min, Double max) {
		super(parent, modal);
		this.min = min;
		this.max = max;
		initComponents();
	}
	
	private Double min;
	private Double max;
	
	public static Double[] getMinMax(double min, double max) {
		Double[] minMax = new Double[2];
		dialog = new MinMaxDialog(Cytoscape.getDesktop(), true, min, max);
		dialog.setVisible(true);
		
		if(dialog.min == null || dialog.max == null)
			return null;

		minMax[0] = dialog.min;
		minMax[1] = dialog.max;
		return minMax;
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */

	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {
		titleLabel = new javax.swing.JLabel();
		titleSeparator = new javax.swing.JSeparator();
		minLabel = new javax.swing.JLabel();
		maxLabel = new javax.swing.JLabel();
		minTextField = new javax.swing.JTextField();
		maxTextField = new javax.swing.JTextField();
		okButton = new javax.swing.JButton();
		cancelButton = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		titleLabel.setFont(new java.awt.Font("SansSerif", 1, 14));
		titleLabel.setText("Set Min and Max");

		minLabel.setFont(new java.awt.Font("SansSerif", 1, 12));
		minLabel.setText("Min");

		maxLabel.setFont(new java.awt.Font("SansSerif", 1, 12));
		maxLabel.setText("Max");

		minTextField.setText(min.toString());
		minTextField.addActionListener(new java.awt.event.ActionListener() {
				public void actionPerformed(java.awt.event.ActionEvent evt) {
					minTextFieldActionPerformed(evt);
				}
			});

		maxTextField.setText(max.toString());

		okButton.setText("OK");
		okButton.setMargin(new java.awt.Insets(2, 2, 2, 2));
		okButton.addActionListener(new java.awt.event.ActionListener() {
				public void actionPerformed(java.awt.event.ActionEvent evt) {
					okButtonActionPerformed(evt);
				}
			});

		cancelButton.setText("Cancel");
		cancelButton.setMargin(new java.awt.Insets(2, 2, 2, 2));
		cancelButton.addActionListener(new java.awt.event.ActionListener() {
				public void actionPerformed(java.awt.event.ActionEvent evt) {
					cancelButtonActionPerformed(evt);
				}
			});

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
		                                .add(layout.createSequentialGroup().addContainerGap()
		                                           .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
		                                                      .add(titleSeparator,
		                                                           org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
		                                                           144, Short.MAX_VALUE)
		                                                      .add(titleLabel)
		                                                      .add(layout.createSequentialGroup()
		                                                                 .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING,
		                                                                                                 false)
		                                                                            .add(minLabel,
		                                                                                 org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
		                                                                                 org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
		                                                                                 Short.MAX_VALUE)
		                                                                            .add(maxLabel,
		                                                                                 org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
		                                                                                 org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
		                                                                                 Short.MAX_VALUE))
		                                                                 .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
		                                                                            .add(layout.createSequentialGroup()
		                                                                                       .add(12,
		                                                                                            12,
		                                                                                            12)
		                                                                                       .add(minTextField,
		                                                                                            org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
		                                                                                            107,
		                                                                                            Short.MAX_VALUE))
		                                                                            .add(layout.createSequentialGroup()
		                                                                                       .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
		                                                                                       .add(maxTextField,
		                                                                                            org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
		                                                                                            107,
		                                                                                            Short.MAX_VALUE))))
		                                                      .add(org.jdesktop.layout.GroupLayout.TRAILING,
		                                                           layout.createSequentialGroup()
		                                                                 .add(cancelButton)
		                                                                 .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
		                                                                 .add(okButton)))
		                                           .addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
		                              .add(layout.createSequentialGroup().addContainerGap()
		                                         .add(titleLabel)
		                                         .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
		                                         .add(titleSeparator,
		                                              org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
		                                              10,
		                                              org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
		                                         .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
		                                         .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
		                                                    .add(minLabel)
		                                                    .add(minTextField,
		                                                         org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
		                                                         org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
		                                                         org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
		                                         .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
		                                         .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
		                                                    .add(maxLabel)
		                                                    .add(maxTextField,
		                                                         org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
		                                                         org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
		                                                         org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
		                                         .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
		                                         .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
		                                                    .add(okButton).add(cancelButton))
		                                         .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
		                                                          Short.MAX_VALUE)));

		pack();
	} // </editor-fold>

	private void minTextFieldActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {
		try{
			min = Double.valueOf(minTextField.getText());
			max = Double.valueOf(maxTextField.getText());
		} catch(NumberFormatException e) {
			min = null;
			max = null;
		}
		dispose();
	}
	
	private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {
		min = null;
		max = null;
		dispose();
	}


	// Variables declaration - do not modify
	private javax.swing.JButton cancelButton;
	private javax.swing.JLabel maxLabel;
	private javax.swing.JTextField maxTextField;
	private javax.swing.JLabel minLabel;
	private javax.swing.JTextField minTextField;
	private javax.swing.JButton okButton;
	private javax.swing.JLabel titleLabel;
	private javax.swing.JSeparator titleSeparator;

	// End of variables declaration
}
