#!/usr/bin/env python
import os
import sys


verbose = False


def PrintUsage():
    print "usage: profiler [--verbose] maven_project_directory"
    exit(-1)


def ReadBaselineFile():
    return True


def RunMavenTest():
    # if os.system("mvn clean test") != 0:
    # 	return False
    return True


def ExtractTimingInfoFromSurefireReport():
    return {}

def SwapBundleVersionNumber():
    return True


def GenerateTimingReport(current_version, baseline_version):
    return


# Main program starts here:
if len(sys.argv) != 2 and len(sys.argv) != 3:
    PrintUsage()

if len(sys.argv) == 2:
    maven_project_directory = sys.argv[1]
else: # We have 3 arguments.
    if sys.argv[1] != "--verbose":
        PrintUsage()
    else:
        verbose = True
        maven_project_directory = sys.argv[2]

if not ReadBaselineFile():
    print "*** Failed to read baseline version from file!"
    exit(-2)

if not RunMavenTest():
    print "*** Failed to run Maven with the current version!"
    exit(-3)

timing_current_version = ExtractTimingInfoFromSurefireReport()

if not SwapBundleVersionNumber():
    print "*** Failed to replace the current version with the baseline version!"
    exit(-4)

if not RunMavenTest():
    print "*** Failed to run Maven with the baseline version!"
    exit(-6)

timing_baseline_version = ExtractTimingInfoFromSurefireReport()

GenerateTimingReport(timing_current_version, timing_baseline_version)
