package org.cytoscape.search.internal.ui;

import java.awt.Dimension;

import org.cytoscape.model.CyTableManager;
import org.cytoscape.session.CyApplicationManager;
import org.cytoscape.search.internal.*;
import org.cytoscape.work.swing.GUITaskManager;

public class EnhancedSearchPanel extends javax.swing.JPanel{
	
	private CyApplicationManager netmgr;
	private CyTableManager tableMgr;
	private EnhancedSearch searchMgr;
	private GUITaskManager taskMgr;
	
   /** Creates new form NewJPanel */
   public EnhancedSearchPanel(CyApplicationManager netmgr, CyTableManager tableMgr, 
		   EnhancedSearch searchMgr, GUITaskManager taskMgr) {
       initComponents();
       
       // Turn off this for now, we may need this later
       this.btnSearch.setVisible(false);
       this.lbSearch.setVisible(true);
       
       this.netmgr = netmgr;
       this.tableMgr = tableMgr;
       this.searchMgr = searchMgr;
       this.taskMgr= taskMgr;
   }

   private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {
	   doSearching();
   }

   private void tfSearchTextActionPerformed(java.awt.event.ActionEvent evt) {
	   doSearching();
   }

   // Do searching based on the query string inputed from user on text-field
   private void doSearching(){
	   System.out.println("\tEnhancedSearchPanel.doSearch()....");
	   if (this.netmgr.getCurrentNetworkView() != null){
		   String queryStr = this.tfSearchText.getText().trim();
		   
		   System.out.println("\t\tQueryStr = "+ queryStr+ "\n");
		   
		   SearchTaskFactory factory = new SearchTaskFactory(this.netmgr.getCurrentNetworkView(), 
				   searchMgr,tableMgr, queryStr);
		   this.taskMgr.execute(factory);		   
	   }
   }
   
   
   /** This method is called from within the constructor to
    * initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is
    * always regenerated by the Form Editor.
    */
   //@SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">
   private void initComponents() {

       lbSearch = new javax.swing.JLabel();
       tfSearchText = new javax.swing.JTextField();
       btnSearch = new javax.swing.JButton();

       lbSearch.setText("Search:");
       lbSearch.setName("lbSearch"); // NOI18N
       add(lbSearch);

       tfSearchText.setToolTipText("Enter search text");
       tfSearchText.setName("tfSearchText"); // NOI18N
       tfSearchText.setPreferredSize(new java.awt.Dimension(80, 25));
       tfSearchText.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               tfSearchTextActionPerformed(evt);
           }
       });
       add(tfSearchText);

       btnSearch.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
       btnSearch.setText("Search");
       btnSearch.setName("btnSearch"); // NOI18N
       btnSearch.setPreferredSize(new java.awt.Dimension(70, 23));
       btnSearch.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               btnSearchActionPerformed(evt);
           }
       });
       add(btnSearch);
   }// </editor-fold>

   // Variables declaration - do not modify
   private javax.swing.JButton btnSearch;
   private javax.swing.JLabel lbSearch;
   private javax.swing.JTextField tfSearchText;
   // End of variables declaration

}
