/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJDialog.java
 *
 * Created on 2009/06/29, 9:36:01
 */

package org.cytoscape.layer.internal.ui;

import java.awt.Frame;
import java.util.ArrayList;
import java.util.Enumeration;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

import javax.swing.BorderFactory;
import javax.swing.DefaultCellEditor;
import javax.swing.DefaultListModel;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;

import org.cytoscape.layer.MultiLayerNetworkBuilder;
import org.cytoscape.model.CyNetwork;
import org.cytoscape.session.CyNetworkManager;

/**
 * 
 * @author kozo
 */
public class LayerBuilderDialog extends JDialog {

	private static final String NETWORK_TITLE = "name";
	
	private static final String[] COLUMN_NAMES = {"Layer 1", "Layer 2", "Connector Networks"};

	/*
	 * Mandatory parameters
	 */
	private CyNetworkManager manager;
	MultiLayerNetworkBuilder builder;

	private DefaultListModel availableNetworkListModel;
	private DefaultListModel layeredNetworkListModel;

	private Map<String, Long> title2IdMap;
	
	private LayerConnectionTableModel layerConnectionTableModel;

	/**
	 * Creates new form NewJDialog
	 * 
	 * @param targetNetworks
	 */

	public LayerBuilderDialog(Frame parent, boolean modal,
			CyNetworkManager manager, Set<CyNetwork> targetNetworks,
			MultiLayerNetworkBuilder builder) {
		super(parent, modal);
		this.manager = manager;
		this.builder = builder;
		
		this.layerConnectionTableModel = new LayerConnectionTableModel(COLUMN_NAMES);

		title2IdMap = new HashMap<String, Long>();
		buildListModels();
		initComponents();

		this.availableNetworkList.setModel(availableNetworkListModel);
		this.layeredNetworkList.setModel(layeredNetworkListModel);
		
		this.layerConnectionTable.setModel(layerConnectionTableModel);
	}

	private void buildListModels() {
		this.availableNetworkListModel = new DefaultListModel();
		final Set<CyNetwork> availableNetworks = manager.getNetworkSet();

		String title = null;
		for (CyNetwork cyNetwork : availableNetworks) {
			title = cyNetwork.attrs().get(NETWORK_TITLE, String.class);
			availableNetworkListModel.addElement(title);
			title2IdMap.put(title, cyNetwork.getSUID());
		}

		layeredNetworkListModel = new DefaultListModel();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		titlePanel = new javax.swing.JPanel();
		titleLabel = new javax.swing.JLabel();
		defineLayerPanel = new javax.swing.JPanel();
		layeredNetworkPanel = new javax.swing.JPanel();
		layeredNetworkScrollPane = new javax.swing.JScrollPane();

		// layeredNetworkList = new javax.swing.JList();
		layeredNetworkList = new ReorderableJList();

		availableNetworkPanel = new javax.swing.JPanel();
		availableNetworkScrollPane = new javax.swing.JScrollPane();
		availableNetworkList = new javax.swing.JList();
		moveAllAvailableNetworkButton = new javax.swing.JButton();
		moveSelectedAvailableNetworkButton = new javax.swing.JButton();
		moveSelectedIntegratedNetworkButton = new javax.swing.JButton();
		moveAllIntegratedNetworkButton = new javax.swing.JButton();
		layerOrderPanel = new javax.swing.JPanel();
		layerOrderScrollPane = new javax.swing.JScrollPane();
		layerConnectionTable = new javax.swing.JTable();
		optionButton = new javax.swing.JButton();
		generateIntegratedNetworkButton = new javax.swing.JButton();
		cancelButton = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		titlePanel.setBackground(new java.awt.Color(255, 255, 255));

		titleLabel.setText("3D Layer Generator");

		org.jdesktop.layout.GroupLayout TitlePanelLayout = new org.jdesktop.layout.GroupLayout(
				titlePanel);
		titlePanel.setLayout(TitlePanelLayout);
		TitlePanelLayout
				.setHorizontalGroup(TitlePanelLayout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								TitlePanelLayout
										.createSequentialGroup()
										.addContainerGap()
										.add(
												titleLabel,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												303,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(250, Short.MAX_VALUE)));
		TitlePanelLayout.setVerticalGroup(TitlePanelLayout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(
				TitlePanelLayout.createSequentialGroup().addContainerGap().add(
						titleLabel,
						org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 39,
						Short.MAX_VALUE).addContainerGap()));

		defineLayerPanel.setBorder(javax.swing.BorderFactory
				.createTitledBorder("Define Layers"));

		layeredNetworkPanel.setBackground(new java.awt.Color(255, 255, 255));
		layeredNetworkPanel.setBorder(javax.swing.BorderFactory
				.createTitledBorder("Integrated Networks"));

		layeredNetworkList.setModel(new javax.swing.AbstractListModel() {
			String[] strings = {};

			public int getSize() {
				return strings.length;
			}

			public Object getElementAt(int i) {
				return strings[i];
			}
		});
		layeredNetworkScrollPane.setViewportView(layeredNetworkList);

		org.jdesktop.layout.GroupLayout IntegratedNetworkPanelLayout = new org.jdesktop.layout.GroupLayout(
				layeredNetworkPanel);
		layeredNetworkPanel.setLayout(IntegratedNetworkPanelLayout);
		IntegratedNetworkPanelLayout
				.setHorizontalGroup(IntegratedNetworkPanelLayout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								IntegratedNetworkPanelLayout
										.createSequentialGroup()
										.addContainerGap()
										.add(
												layeredNetworkScrollPane,
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												173, Short.MAX_VALUE)
										.addContainerGap()));
		IntegratedNetworkPanelLayout
				.setVerticalGroup(IntegratedNetworkPanelLayout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								IntegratedNetworkPanelLayout
										.createSequentialGroup()
										.add(
												layeredNetworkScrollPane,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												186,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(8, Short.MAX_VALUE)));

		availableNetworkPanel.setBackground(new java.awt.Color(255, 255, 255));
		availableNetworkPanel.setBorder(javax.swing.BorderFactory
				.createTitledBorder("Available Networks"));

		availableNetworkScrollPane.setViewportView(availableNetworkList);

		org.jdesktop.layout.GroupLayout AvailableNetworkPanelLayout = new org.jdesktop.layout.GroupLayout(
				availableNetworkPanel);
		availableNetworkPanel.setLayout(AvailableNetworkPanelLayout);
		AvailableNetworkPanelLayout
				.setHorizontalGroup(AvailableNetworkPanelLayout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								AvailableNetworkPanelLayout
										.createSequentialGroup()
										.addContainerGap()
										.add(
												availableNetworkScrollPane,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												159,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));
		AvailableNetworkPanelLayout
				.setVerticalGroup(AvailableNetworkPanelLayout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								AvailableNetworkPanelLayout
										.createSequentialGroup()
										.add(
												availableNetworkScrollPane,
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												181, Short.MAX_VALUE)
										.addContainerGap()));

		moveAllAvailableNetworkButton.setText(">>");
		moveAllAvailableNetworkButton
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						moveAllAvailableNetworkButtonActionPerformed(evt);
					}
				});

		moveSelectedAvailableNetworkButton.setText(">");
		moveSelectedAvailableNetworkButton
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						addSelectedAvailableNetworkButtonActionPerformed(evt);
					}
				});

		moveSelectedIntegratedNetworkButton.setText("<");
		moveSelectedIntegratedNetworkButton
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						removeSelectedIntegratedNetworkButtonActionPerformed(evt);
					}
				});

		moveAllIntegratedNetworkButton.setText("<<");
		moveAllIntegratedNetworkButton
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						moveAllIntegratedNetworkButtonActionPerformed(evt);
					}
				});

		org.jdesktop.layout.GroupLayout DefineLayerPanelLayout = new org.jdesktop.layout.GroupLayout(
				defineLayerPanel);
		defineLayerPanel.setLayout(DefineLayerPanelLayout);
		DefineLayerPanelLayout
				.setHorizontalGroup(DefineLayerPanelLayout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								DefineLayerPanelLayout
										.createSequentialGroup()
										.add(231, 231, 231)
										.add(
												DefineLayerPanelLayout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.TRAILING)
														.add(
																moveAllAvailableNetworkButton,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																77,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
														.add(
																moveSelectedAvailableNetworkButton,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																77,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
														.add(
																moveSelectedIntegratedNetworkButton,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																77,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
														.add(
																moveAllIntegratedNetworkButton,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																77,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
										.add(18, 18, 18)
										.add(
												layeredNetworkPanel,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(22, Short.MAX_VALUE))
						.add(
								DefineLayerPanelLayout
										.createParallelGroup(
												org.jdesktop.layout.GroupLayout.LEADING)
										.add(
												DefineLayerPanelLayout
														.createSequentialGroup()
														.add(22, 22, 22)
														.add(
																availableNetworkPanel,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
														.addContainerGap(340,
																Short.MAX_VALUE))));
		DefineLayerPanelLayout
				.setVerticalGroup(DefineLayerPanelLayout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								DefineLayerPanelLayout
										.createSequentialGroup()
										.add(
												DefineLayerPanelLayout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING)
														.add(
																DefineLayerPanelLayout
																		.createSequentialGroup()
																		.add(
																				48,
																				48,
																				48)
																		.add(
																				moveAllAvailableNetworkButton)
																		.addPreferredGap(
																				org.jdesktop.layout.LayoutStyle.RELATED)
																		.add(
																				moveSelectedAvailableNetworkButton)
																		.add(
																				43,
																				43,
																				43)
																		.add(
																				moveSelectedIntegratedNetworkButton)
																		.addPreferredGap(
																				org.jdesktop.layout.LayoutStyle.RELATED)
																		.add(
																				moveAllIntegratedNetworkButton))
														.add(
																DefineLayerPanelLayout
																		.createSequentialGroup()
																		.add(
																				11,
																				11,
																				11)
																		.add(
																				layeredNetworkPanel,
																				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																				218,
																				Short.MAX_VALUE)))
										.addContainerGap())
						.add(
								DefineLayerPanelLayout
										.createParallelGroup(
												org.jdesktop.layout.GroupLayout.LEADING)
										.add(
												DefineLayerPanelLayout
														.createSequentialGroup()
														.addContainerGap()
														.add(
																availableNetworkPanel,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
														.addContainerGap(
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE))));

		layerOrderPanel.setBorder(javax.swing.BorderFactory
				.createTitledBorder("Define Layer Order"));


		DefaultCellEditor cellEditor = new DefaultCellEditor(
				new ComboCellRenderer(layeredNetworkListModel));
		// ComboCellRenderer layerOrderTableRenderer = new ComboCellRenderer();
		// layerOrderTable.getColumnModel().getColumn(0).setCellRenderer(
		// layerOrderTableRenderer);

		layerOrderScrollPane.setViewportView(layerConnectionTable);

		org.jdesktop.layout.GroupLayout LayerOrderPanelLayout = new org.jdesktop.layout.GroupLayout(
				layerOrderPanel);
		layerOrderPanel.setLayout(LayerOrderPanelLayout);
		LayerOrderPanelLayout
				.setHorizontalGroup(LayerOrderPanelLayout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								LayerOrderPanelLayout
										.createSequentialGroup()
										.addContainerGap()
										.add(
												layerOrderScrollPane,
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												531, Short.MAX_VALUE)
										.addContainerGap()));
		LayerOrderPanelLayout.setVerticalGroup(LayerOrderPanelLayout
				.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(
						LayerOrderPanelLayout.createSequentialGroup().add(
								layerOrderScrollPane,
								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
								99,
								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(14, Short.MAX_VALUE)));

		optionButton.setText("Options");
		optionButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				optionButtonActionPerformed(evt);
			}
		});

		generateIntegratedNetworkButton.setText("Generate");
		generateIntegratedNetworkButton
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						generateIntegratedNetworkButtonActionPerformed(evt);
					}
				});

		cancelButton.setText("Cancel");
		cancelButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				cancelButtonActionPerformed(evt);
			}
		});

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(titlePanel,
				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.add(defineLayerPanel,
						org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
						org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE).add(layerOrderPanel,
						org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
						org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE).add(
						layout.createSequentialGroup().add(20, 20, 20).add(
								optionButton).addPreferredGap(
								org.jdesktop.layout.LayoutStyle.RELATED, 226,
								Short.MAX_VALUE).add(
								generateIntegratedNetworkButton)
								.add(32, 32, 32).add(cancelButton).add(39, 39,
										39)));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								layout
										.createSequentialGroup()
										.add(
												titlePanel,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.RELATED)
										.add(
												defineLayerPanel,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.UNRELATED)
										.add(
												layerOrderPanel,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.RELATED,
												13, Short.MAX_VALUE)
										.add(
												layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.BASELINE)
														.add(optionButton)
														.add(
																generateIntegratedNetworkButton)
														.add(cancelButton))
										.addContainerGap()));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_CancelButtonActionPerformed
		this.dispose();
	}// GEN-LAST:event_CancelButtonActionPerformed

	private void generateIntegratedNetworkButtonActionPerformed(
			java.awt.event.ActionEvent evt) {// GEN-FIRST:event_GenerateIntegratedNetworkButtonActionPerformed

		List<CyNetwork> layers = new ArrayList<CyNetwork>();
		List<CyNetwork> connectors = new ArrayList<CyNetwork>();

		// System.out.println(title2IdMap.get(layeredNetworkListModel
		// .getElementAt(0)));
		// System.out.println(title2IdMap.get(layeredNetworkListModel
		// .getElementAt(1)));
		// System.out.println(title2IdMap.get(layeredNetworkListModel
		// .getElementAt(2)));

		// System.out.println(manager.getNetwork(title2IdMap
		// .get(layeredNetworkListModel.getElementAt(0))));
		// System.out.println(manager.getNetwork(title2IdMap
		// .get(layeredNetworkListModel.getElementAt(1))));
		// System.out.println(manager.getNetwork(title2IdMap
		// .get(layeredNetworkListModel.getElementAt(2))));

		layers.add(manager.getNetwork(title2IdMap.get(layeredNetworkListModel
				.getElementAt(0))));

		connectors.add(manager.getNetwork(title2IdMap
				.get(layeredNetworkListModel.getElementAt(1))));

		layers.add(manager.getNetwork(title2IdMap.get(layeredNetworkListModel
				.getElementAt(2))));

		// Setup
		builder.setSourceNetworks(layers, connectors);
		manager.addNetwork(builder.buildLayeredNetwork());

		// for (CyNode cyNode : builder.buildLayeredNetwork().getNodeList()) {
		// System.out.println(cyNode.attrs().get("name", String.class));
		// }

		//
		// if (builder.buildLayeredNetwork() != null) {
		// System.out.println(builder.buildLayeredNetwork().getEdgeCount());
		// System.out.println(builder.buildLayeredNetwork().getNodeCount());
		// }

		// System.out.println(builder.buildLayeredNetwork());

		// manager.addNetwork(builder.buildLayeredNetwork());

		// BuildMultilayerNetworkTask task = new BuildMultilayerNetworkTask(
		// manager, builder);

		// Run

	}// GEN-LAST:event_GenerateIntegratedNetworkButtonActionPerformed

	private void optionButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_OptionButtonActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_OptionButtonActionPerformed

	private void moveAllAvailableNetworkButtonActionPerformed(
			java.awt.event.ActionEvent evt) {// GEN-FIRST:event_MoveAllAvailableNetworkButtonActionPerformed

		// move list content
		Enumeration<?> availableNetworks = availableNetworkListModel.elements();

		while (availableNetworks.hasMoreElements()) {
			layeredNetworkListModel.addElement(availableNetworks.nextElement());
		}

		availableNetworkListModel.clear();

		// sync list content and table column
		JComboBox layerCb = new JComboBox(layeredNetworkListModel.toArray());
		JComboBox connecterCb = new JComboBox(availableNetworkListModel
				.toArray());
		layerCb.setBorder(BorderFactory.createEmptyBorder());
		connecterCb.setBorder(BorderFactory.createEmptyBorder());
		TableColumn layerCol = layerConnectionTable.getColumnModel().getColumn(0);
		// TableColumn connectorCol = layerOrderTable.getColumnModel()
		// .getColumn(1);
		// layerCol.setCellEditor(new DefaultCellEditor(layerCb));
		// connectorCol.setCellEditor(new DefaultCellEditor(connecterCb));

	}// GEN-LAST:event_MoveAllAvailableNetworkButtonActionPerformed

	private void addSelectedAvailableNetworkButtonActionPerformed(
			java.awt.event.ActionEvent evt) {// GEN-FIRST:event_MoveSelectedAvailableNetworkButtonActionPerformed

		// move list content
		int[] index = availableNetworkList.getSelectedIndices();

		for (int i = 0; i < index.length; i++) {
			layeredNetworkListModel.addElement(availableNetworkListModel
					.getElementAt(index[i]));
			// availableNetworkListModel.removeElementAt(index[i]);
		}

		for (int i = index.length - 1; i >= 0; i--) {
			availableNetworkListModel.removeElementAt(index[i]);
		}

		availableNetworkList.clearSelection();

		Long[] row = {1l,  2l, 3l};
		layerConnectionTableModel.addRow(row);
		layerConnectionTable.repaint();
		
		
		// sync list content and table column
		JComboBox layerCb = new JComboBox(layeredNetworkListModel.toArray());
		JComboBox connecterCb = new JComboBox(availableNetworkListModel
				.toArray());
		layerCb.setBorder(BorderFactory.createEmptyBorder());
		connecterCb.setBorder(BorderFactory.createEmptyBorder());
		TableColumn layerCol = layerConnectionTable.getColumnModel().getColumn(0);
		// TableColumn connectorCol = layerOrderTable.getColumnModel()
		// .getColumn(1);
		// layerCol.setCellEditor(new DefaultCellEditor(layerCb));
		// connectorCol.setCellEditor(new DefaultCellEditor(connecterCb));

	}// GEN-LAST:event_MoveSelectedAvailableNetworkButtonActionPerformed

	private void removeSelectedIntegratedNetworkButtonActionPerformed(
			java.awt.event.ActionEvent evt) {// GEN-FIRST:event_MoveSelectedIntegratedNetworkButtonActionPerformed

		// move list content
		int[] index = layeredNetworkList.getSelectedIndices();
		for (int i = 0; i < index.length; i++) {
			availableNetworkListModel.addElement(layeredNetworkListModel
					.getElementAt(index[i]));
			// layeredNetworkListModel.removeElementAt(index[i]);
		}

		for (int i = index.length - 1; i >= 0; i--) {
			layeredNetworkListModel.removeElementAt(index[i]);
		}

		layeredNetworkList.clearSelection();

		// sync list content and table column
		JComboBox layerCb = new JComboBox(layeredNetworkListModel.toArray());
		JComboBox connecterCb = new JComboBox(availableNetworkListModel
				.toArray());
		layerCb.setBorder(BorderFactory.createEmptyBorder());
		connecterCb.setBorder(BorderFactory.createEmptyBorder());
		TableColumn layerCol = layerConnectionTable.getColumnModel().getColumn(0);
		
		
		// TableColumn connectorCol = layerOrderTable.getColumnModel()
		// .getColumn(1);
		// layerCol.setCellEditor(new DefaultCellEditor(layerCb));
		// connectorCol.setCellEditor(new DefaultCellEditor(connecterCb));

	}// GEN-LAST:event_MoveSelectedIntegratedNetworkButtonActionPerformed

	private void moveAllIntegratedNetworkButtonActionPerformed(
			java.awt.event.ActionEvent evt) {// GEN-FIRST:event_MoveAllIntegratedNetworkButtonActionPerformed

		Enumeration<?> layeredNetworks = layeredNetworkListModel.elements();

		while (layeredNetworks.hasMoreElements()) {
			availableNetworkListModel.addElement(layeredNetworks.nextElement());
		}

		layeredNetworkListModel.clear();

		// sync list content and table column
		JComboBox layerCb = new JComboBox(layeredNetworkListModel.toArray());
		JComboBox connecterCb = new JComboBox(availableNetworkListModel
				.toArray());
		layerCb.setBorder(BorderFactory.createEmptyBorder());
		connecterCb.setBorder(BorderFactory.createEmptyBorder());
		TableColumn layerCol = layerConnectionTable.getColumnModel().getColumn(0);
		// TableColumn connectorCol = layerOrderTable.getColumnModel()
		// .getColumn(1);
		// layerCol.setCellEditor(new DefaultCellEditor(layerCb));
		// connectorCol.setCellEditor(new DefaultCellEditor(connecterCb));

	}// GEN-LAST:event_MoveAllIntegratedNetworkButtonActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JList availableNetworkList;
	private javax.swing.JPanel availableNetworkPanel;
	private javax.swing.JScrollPane availableNetworkScrollPane;
	private javax.swing.JButton cancelButton;
	private javax.swing.JPanel defineLayerPanel;
	private javax.swing.JButton generateIntegratedNetworkButton;

	// private javax.swing.JList layeredNetworkList;
	private ReorderableJList layeredNetworkList;

	private javax.swing.JPanel layeredNetworkPanel;
	private javax.swing.JScrollPane layeredNetworkScrollPane;
	private javax.swing.JPanel layerOrderPanel;
	private javax.swing.JScrollPane layerOrderScrollPane;
	private javax.swing.JTable layerConnectionTable;
	private javax.swing.JButton moveAllAvailableNetworkButton;
	private javax.swing.JButton moveAllIntegratedNetworkButton;
	private javax.swing.JButton moveSelectedAvailableNetworkButton;
	private javax.swing.JButton moveSelectedIntegratedNetworkButton;
	private javax.swing.JButton optionButton;
	private javax.swing.JLabel titleLabel;
	private javax.swing.JPanel titlePanel;

	// End of variables declaration//GEN-END:variables

}
