package org.cytoscape.webservice.cpdb;

import javax.swing.JPanel;

import soap.cpdb.CPDB;
import cytoscape.Cytoscape;
import cytoscape.data.CyAttributes;
import cytoscape.data.webservice.CyWebServiceEvent;
import cytoscape.data.webservice.CyWebServiceException;
import cytoscape.data.webservice.NetworkImportWebServiceClient;
import cytoscape.data.webservice.WebServiceClient;
import cytoscape.data.webservice.WebServiceClientImplWithGUI;
import cytoscape.data.webservice.WebServiceClientManager.ClientType;
import cytoscape.layout.Tunable;
import cytoscape.util.ModulePropertiesImpl;
import cytoscape.visual.VisualStyle;

/*
 Copyright (c) 2006, 2007, The Cytoscape Consortium (www.cytoscape.org)

 The Cytoscape Consortium is:
 - Institute for Systems Biology
 - University of California San Diego
 - Memorial Sloan-Kettering Cancer Center
 - Institut Pasteur
 - Agilent Technologies

 This library is free software; you can redistribute it and/or modify it
 under the terms of the GNU Lesser General Public License as published
 by the Free Software Foundation; either version 2.1 of the License, or
 any later version.

 This library is distributed in the hope that it will be useful, but
 WITHOUT ANY WARRANTY, WITHOUT EVEN THE IMPLIED WARRANTY OF
 MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.  The software and
 documentation provided hereunder is on an "as is" basis, and the
 Institute for Systems Biology and the Whitehead Institute
 have no obligations to provide maintenance, support,
 updates, enhancements or modifications.  In no event shall the
 Institute for Systems Biology and the Whitehead Institute
 be liable to any party for direct, indirect, special,
 incidental or consequential damages, including lost profits, arising
 out of the use of this software and its documentation, even if the
 Institute for Systems Biology and the Whitehead Institute
 have been advised of the possibility of such damage.  See
 the GNU Lesser General Public License for more details.

 You should have received a copy of the GNU Lesser General Public License
 along with this library; if not, write to the Free Software Foundation,
 Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA.
 */

/**
 * CPDB web service client.
 * 
 * @author atanas, kono
 * @version 0.1
 * @since Cytoscape 2.6.3
 * 
 */
public class CPDBClient extends WebServiceClientImplWithGUI<CPDB, JPanel>
		implements NetworkImportWebServiceClient {

	// Display name of this client.
	private static final String DISPLAY_NAME = "IntAct Web Service Client";

	// Client ID. This should be unique.
	private static final String CLIENT_ID = "intact";

	// Instance of this client. This is a singleton.
	private static WebServiceClient<CPDB> client = new CPDBClient();

	// Visual Style name for the networks generated by this client.
	private static final String DEF_VS_NAME = "CPDB Style";
	private VisualStyle defaultVS = null;

	// Attributes.
	private final CyAttributes nodeAttr = Cytoscape.getNodeAttributes();
	private final CyAttributes edgeAttr = Cytoscape.getEdgeAttributes();

	private void setDescription() {
		description = "Test";
	}

	/**
	 * Return instance of this client.
	 * 
	 * @return
	 */
	public static WebServiceClient<CPDB> getClient() {
		return client;
	}

	/**
	 * Creates a new IntactClient object.
	 */
	private CPDBClient() {
		super(CLIENT_ID, DISPLAY_NAME, new ClientType[] { ClientType.NETWORK },
				null, new CPDB(), null);
		setDescription();
		// Set properties for this client.
		setProperty();
	}

	/**
	 * Set props for this client.
	 */
	private void setProperty() {
		props = new ModulePropertiesImpl(clientID, "wsc");

		props.add(new Tunable("max_interactions", "Maximum number of records",
				Tunable.INTEGER, new Integer(50000)));

		props.add(new Tunable("timeout", "Timeout (sec.)", Tunable.INTEGER,
				new Integer(1200)));
		// props.add(new Tunable("select_interaction",
		// "Import only selected interactions",
		// Tunable.BOOLEAN, new Boolean(false)));
	}

	@Override
	public void executeService(CyWebServiceEvent arg0)
			throws CyWebServiceException {
		// TODO Auto-generated method stub

	}

	public VisualStyle getDefaultVisualStyle() {
		// TODO Auto-generated method stub
		return null;
	}

}
