package org.cytoscape.app.internal.ui;

import java.awt.Desktop;
import java.awt.Font;
import java.awt.event.ComponentEvent;
import java.awt.event.ComponentListener;
import java.io.File;
import java.io.IOException;
import java.net.URISyntaxException;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.RowSorter;
import javax.swing.ScrollPaneConstants;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.event.HyperlinkEvent;
import javax.swing.event.HyperlinkEvent.EventType;
import javax.swing.event.HyperlinkListener;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.event.TableModelListener;
import javax.swing.event.TreeExpansionEvent;
import javax.swing.event.TreeExpansionListener;
import javax.swing.event.TreeSelectionEvent;
import javax.swing.event.TreeSelectionListener;
import javax.swing.filechooser.FileFilter;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.text.html.HTMLDocument;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreeModel;
import javax.swing.tree.TreeNode;
import javax.swing.tree.TreePath;

import org.cytoscape.app.internal.exception.AppMoveException;
import org.cytoscape.app.internal.exception.AppParsingException;
import org.cytoscape.app.internal.manager.App;
import org.cytoscape.app.internal.manager.AppManager;
import org.cytoscape.app.internal.manager.AppParser;
import org.cytoscape.app.internal.net.WebApp;
import org.cytoscape.app.internal.net.WebQuerier;

/**
 * This class represents the panel in the App Manager dialog's tab used for installing new apps.
 * Its UI setup code is generated by the Netbeans 7 GUI builder.
 */
public class InstallFromStorePanel extends javax.swing.JPanel {
	
	/** Long serial version identifier required by the Serializable class */
	private static final long serialVersionUID = -1208176142084829272L;
	
    private javax.swing.JScrollPane descriptionScrollPane;
    private javax.swing.JTextPane descriptionTextPane;
    private javax.swing.JButton installSelectedButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane resultsScrollPane;
    private javax.swing.JSplitPane resultsSplitPane;
    private javax.swing.JTree resultsTree;
    private javax.swing.JLabel searchAppsLabel;
    private javax.swing.JComboBox searchComboBox;
    private javax.swing.JCheckBox showCompatibleCheckBox;
	
	private JFileChooser fileChooser;
	
	private AppManager appManager;
	
    public InstallFromStorePanel(AppManager appManager) {
        this.appManager = appManager;
    	initComponents();
        
        setupDescriptionListener();
        setupHyperlinkListener();
        
        populateTree();
    }

    private void initComponents() {

        searchComboBox = new javax.swing.JComboBox();
        installSelectedButton = new javax.swing.JButton();
        searchAppsLabel = new javax.swing.JLabel();
        resultsSplitPane = new javax.swing.JSplitPane();
        resultsScrollPane = new javax.swing.JScrollPane();
        resultsTree = new javax.swing.JTree();
        descriptionScrollPane = new javax.swing.JScrollPane();
        descriptionTextPane = new javax.swing.JTextPane();
        showCompatibleCheckBox = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();

        searchComboBox.setEditable(true);

        installSelectedButton.setText("Install Selected");
        installSelectedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                installSelectedButtonActionPerformed(evt);
            }
        });

        searchAppsLabel.setText("Filter Apps:");

        resultsSplitPane.setDividerLocation(215);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("JTree");
        resultsTree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        resultsScrollPane.setViewportView(resultsTree);

        resultsSplitPane.setLeftComponent(resultsScrollPane);

        descriptionTextPane.setContentType("text/html");
        descriptionTextPane.setEditable(false);
        
        // Make the JTextPane render HTML using the default UI font
        Font font = UIManager.getFont("Label.font");
        String bodyRule = "body { font-family: " + font.getFamily() + "; " +
                "font-size: " + font.getSize() + "pt; }";
        ((HTMLDocument) descriptionTextPane.getDocument()).getStyleSheet().addRule(bodyRule);
        
        descriptionTextPane.setText("<html>   <head>    </head>   <body>     <p style=\"margin-top: 0\"> App information is displayed here. <a href=\"http://www.w3schools.com/\">Test link</a>          </p>   </body> </html> ");
        descriptionTextPane.setText("");
        descriptionScrollPane.setViewportView(descriptionTextPane);

        resultsSplitPane.setRightComponent(descriptionScrollPane);

        showCompatibleCheckBox.setText("Show only compatible apps");

        jButton1.setText("Browse File");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(installSelectedButton)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jButton1))
                            .add(searchAppsLabel)
                            .add(layout.createSequentialGroup()
                                .add(searchComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 269, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(showCompatibleCheckBox)))
                        .add(0, 55, Short.MAX_VALUE))
                    .add(resultsSplitPane))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(searchAppsLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(searchComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(showCompatibleCheckBox))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(resultsSplitPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE, false)
                    .add(installSelectedButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jButton1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void installSelectedButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        // TODO add your handling code here:
    }                                                     

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void viewOnWebStoreButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }
    
    /**
     * Populate the current tree of results with the available apps from the web store.
     */
    private void populateTree() {
    	WebQuerier webQuerier = appManager.getWebQuerier();
    	
    	DefaultMutableTreeNode root = new DefaultMutableTreeNode("Available Apps (" + webQuerier.getAllApps().size() + ")");
    	
    	// Obtain available tags
    	Set<WebQuerier.AppTag> availableTags = webQuerier.getAllTags();
    	
    	for (WebQuerier.AppTag appTag : availableTags) {
    		DefaultMutableTreeNode tagNode = new DefaultMutableTreeNode(appTag.getFullName() + " (" + appTag.getCount() + ")");
    		
    		// Obtain apps for the current tag
    		System.out.println("Getting apps for tag: " + appTag.getName());
    		Set<WebApp> tagApps = webQuerier.getAppsByTag(appTag.getName());
    		
    		for (WebApp tagApp : tagApps) {
    			tagNode.add(new DefaultMutableTreeNode(tagApp));
    		}
    		
    		root.add(tagNode);
    	}
    	
    	resultsTree.setModel(new DefaultTreeModel(root));
    }
    
    /**
     * Obtain the set of {@link WebApp} objects corresponding to currently selected entries in the tree of apps
     * @return A set of {@link WebApp} objects corresponding to selected apps in the tree
     */
    private Set<WebApp> getSelectedApps() {
    	TreePath[] selectedPaths = resultsTree.getSelectionPaths();
    	Set<WebApp> selectedApps = new HashSet<WebApp>();
    	
    	for (int index = 0; index < selectedPaths.length; index++) {
    		TreePath selectedPath = selectedPaths[index];
    		
    		DefaultMutableTreeNode selectedNode = (DefaultMutableTreeNode) selectedPath.getLastPathComponent();
    		Object selectedUserObject = selectedNode.getUserObject();
    		
    		// Selecting tag category nodes are also added to the set of selected paths; avoid
    		// adding them as selected apps by making this check
    		if (selectedUserObject instanceof WebApp) {
    			selectedApps.add((WebApp) selectedUserObject);
    		}
    	}
    	
    	return selectedApps;
    }
    
    /**
     * Setup and register a listener to the tree to listen for selection changed events in order to update the
     * app description box
     */
    private void setupDescriptionListener() {
    	resultsTree.addTreeSelectionListener(new TreeSelectionListener() {
			
			@Override
			public void valueChanged(TreeSelectionEvent event) {
				updateDescriptionBox();
			}
		});
    }
    
    private void setupHyperlinkListener() {
    	descriptionTextPane.addHyperlinkListener(new HyperlinkListener() {
			
			@Override
			public void hyperlinkUpdate(HyperlinkEvent event) {
				if (Desktop.isDesktopSupported() && event.getEventType() == EventType.ACTIVATED) {
					Desktop desktop = Desktop.getDesktop();
					
					try {
						desktop.browse(event.getURL().toURI());
					} catch (IOException e) {
						// TODO Auto-generated catch block
						e.printStackTrace();
					} catch (URISyntaxException e) {
						// TODO Auto-generated catch block
						e.printStackTrace();
					}
				}
			}
		});
    }
    
    private void updateDescriptionBox() {
    	Set<WebApp> selectedApps = getSelectedApps();
    	int numSelected = selectedApps.size();
    	
    	// If no apps are selected, clear the description box
    	if (numSelected == 0) {
            descriptionTextPane.setText("<html> <head> TestHeader </head> <body>" +
            		"<p style=\"margin-top: 0\"> App information is displayed here. </p> </body> </html> ");    
            descriptionTextPane.setText("");
    	// If a single app is selected, show its app description
    	} else if (numSelected == 1){
    		WebApp selectedApp = selectedApps.iterator().next();
    		
    		String text = "<html><b>" + selectedApp.getFullName() + "</b></html>";
    		text += "\n\n";
    		text += selectedApp.getDescription();
    		
    		text = "";
    		text += "<html> <head> </head> <body>";
    		text += "<p style=\"margin-top: 0\"> <a href=\"" + selectedApp.getAppStoreUrl() + "\">" + selectedApp.getAppStoreUrl() + "</a> </p>";
    		text += "<p> <b>" + selectedApp.getFullName() + "</b> </p>";
    		text += "<p>" + selectedApp.getDescription() + "</p>";
    		text += "</body> </html>";
    		descriptionTextPane.setText(text);
    	} else {
    		String text = "<html> <head> </head> <body> <p style=\"margin-top: 0\">";
    		text += numSelected + " apps selected: <br />";
    		
    		for (WebApp webApp : selectedApps) {
    			text += "<br />" + webApp.getFullName();
    		};
    		text += "</p>";
    		text += "</body> </html>";
    		descriptionTextPane.setText(text);
    	}
    }
}
