package cytoscape.coreplugins.biopax.ui;

import org.biopax.paxtools.controller.ConversionScore;
import org.biopax.paxtools.model.BioPAXElement;
import org.biopax.paxtools.model.level2.physicalEntityParticipant;

import cytoscape.coreplugins.biopax.mapping.MapBioPaxToCytoscape;
import cytoscape.coreplugins.biopax.style.BioPaxVisualStyleUtil;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;

import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.awt.event.*;

import cytoscape.coreplugins.biopax.util.BioPaxUtil;
import cytoscape.data.CyAttributes;
import cytoscape.CyNode;
import cytoscape.Cytoscape;

public class IntegrateBioPAXDetailsDialog extends JDialog {
    private JPanel contentPane;
    private JButton buttonOK;
    private JTable matchTable;
    private JLabel cScore;
    private JLabel convName2;
    private JLabel convName1;

    public IntegrateBioPAXDetailsDialog(ConversionScore convScore) {
        setContentPane(contentPane);
        setModal(true);
        getRootPane().setDefaultButton(buttonOK);

        buttonOK.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                onOK();
            }
        });

// call onCancel() when cross is clicked
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                onCancel();
            }
        });

// call onCancel() on ESCAPE
        contentPane.registerKeyboardAction(
        		new ActionListener() {
        			public void actionPerformed(ActionEvent e) {
        				onCancel();
        			}
        		}, 
        		KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), 
        		JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);

        convName1.setText(BioPaxUtil.getNodeName(convScore.getConversion1()));
        convName2.setText(BioPaxUtil.getNodeName(convScore.getConversion2()));
        cScore.setText("" + convScore.getScore());

        String[] tableHeader = {"First Reaction Component", "->", "Second Reaction Component"};
        String[][] tableData = new String[convScore.getMatchedPEPs().size()][];

        int count = 0;
        for (physicalEntityParticipant pep : convScore.getMatchedPEPs()) {
            String nodeId1 = addNode(pep);
            String nodeId2 = addNode(convScore.getMatch(pep));

            CyAttributes nodeAttributes = Cytoscape.getNodeAttributes();
            String name1 =
                    nodeAttributes.getStringAttribute(nodeId1, BioPaxVisualStyleUtil.BIOPAX_NODE_LABEL),
                    name2 =
                            nodeAttributes.getStringAttribute(nodeId2, BioPaxVisualStyleUtil.BIOPAX_NODE_LABEL);
            String[] tableRow = {name1, "->", name2};
            tableData[count++] = tableRow;
        }

        matchTable.setModel(new DefaultTableModel(tableData, tableHeader) {
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        });

        matchTable.getColumnModel().getColumn(1).setWidth(5);

    }

    private String addNode(BioPAXElement bpe) {
    	String nodeID = BioPaxUtil.getLocalPartRdfId(bpe);
		CyNode node = Cytoscape.getCyNode(nodeID, true);
		MapBioPaxToCytoscape.setBasicNodeAttributes(node, bpe, null);
		MapBioPaxToCytoscape.mapNodeAttribute(bpe, nodeID);
        return node.getIdentifier();
    }
    
    
    private void onOK() {
        dispose();
    }

    private void onCancel() {
        dispose();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new GridBagLayout());
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        contentPane.add(panel1, gbc);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        panel1.add(panel2, gbc);
        buttonOK = new JButton();
        buttonOK.setText("OK");
        buttonOK.setMnemonic('O');
        buttonOK.setDisplayedMnemonicIndex(0);
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel2.add(buttonOK, gbc);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        contentPane.add(panel3, gbc);
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        panel3.add(panel4, gbc);
        panel4.setBorder(BorderFactory.createTitledBorder("Matched Components"));
        final JScrollPane scrollPane1 = new JScrollPane();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        panel4.add(scrollPane1, gbc);
        matchTable = new JTable();
        //matchTable.setFillsViewportHeight(true);
        matchTable.setPreferredScrollableViewportSize(new Dimension(500, 200));
        scrollPane1.setViewportView(matchTable);
        final JLabel label1 = new JLabel();
        label1.setFont(new Font(label1.getFont().getName(), label1.getFont().getStyle(), 11));
        label1.setText("Below is the list of matched reaction components");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.EAST;
        panel4.add(label1, gbc);
        final JPanel panel5 = new JPanel();
        panel5.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.VERTICAL;
        contentPane.add(panel5, gbc);
        panel5.setBorder(BorderFactory.createTitledBorder("Details"));
        final JLabel label2 = new JLabel();
        label2.setFont(new Font(label2.getFont().getName(), Font.BOLD, label2.getFont().getSize()));
        label2.setText("Second Reaction:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.EAST;
        panel5.add(label2, gbc);
        final JLabel label3 = new JLabel();
        label3.setFont(new Font(label3.getFont().getName(), Font.BOLD, label3.getFont().getSize()));
        label3.setText("Score:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.EAST;
        panel5.add(label3, gbc);
        final JLabel label4 = new JLabel();
        label4.setFont(new Font(label4.getFont().getName(), Font.BOLD, label4.getFont().getSize()));
        label4.setText("First Reaction:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.EAST;
        panel5.add(label4, gbc);
        convName2 = new JLabel();
        convName2.setText("Name2");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 10, 0, 0);
        panel5.add(convName2, gbc);
        cScore = new JLabel();
        cScore.setText("Score");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 10, 0, 0);
        panel5.add(cScore, gbc);
        convName1 = new JLabel();
        convName1.setText("Name1");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 10, 0, 0);
        panel5.add(convName1, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }
}
