/*
 Copyright (c) 2006, 2007, The Cytoscape Consortium (www.cytoscape.org)

 The Cytoscape Consortium is:
 - Institute for Systems Biology
 - University of California San Diego
 - Memorial Sloan-Kettering Cancer Center
 - Institut Pasteur
 - Agilent Technologies

 This library is free software; you can redistribute it and/or modify it
 under the terms of the GNU Lesser General Public License as published
 by the Free Software Foundation; either version 2.1 of the License, or
 any later version.

 This library is distributed in the hope that it will be useful, but
 WITHOUT ANY WARRANTY, WITHOUT EVEN THE IMPLIED WARRANTY OF
 MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.  The software and
 documentation provided hereunder is on an "as is" basis, and the
 Institute for Systems Biology and the Whitehead Institute
 have no obligations to provide maintenance, support,
 updates, enhancements or modifications.  In no event shall the
 Institute for Systems Biology and the Whitehead Institute
 be liable to any party for direct, indirect, special,
 incidental or consequential damages, including lost profits, arising
 out of the use of this software and its documentation, even if the
 Institute for Systems Biology and the Whitehead Institute
 have been advised of the possibility of such damage.  See
 the GNU Lesser General Public License for more details.

 You should have received a copy of the GNU Lesser General Public License
 along with this library; if not, write to the Free Software Foundation,
 Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA.
*/
package cytoscape.data.webservice.ui;

import cytoscape.Cytoscape;

import cytoscape.data.webservice.WebServiceClient;
import cytoscape.data.webservice.WebServiceClientManager;
import cytoscape.data.webservice.WebServiceClientManager.ClientType;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.swing.JDialog;


/**
 *
 * @author  kono
 */
public class WSNetworkImportDialog extends javax.swing.JDialog {
	private final static long serialVersionUID = 1202339872463169L;
	private static final WSNetworkImportDialog dialog;

	// Key is display name, value is actual service name.
	private Map<String, String> clientNames;

	static {
		dialog = new WSNetworkImportDialog(Cytoscape.getDesktop(), false);
	}

	/**
	 *  DOCUMENT ME!
	 */
	public static void showDialog() {
		dialog.setVisible(true);
	}

	/** Creates new form NetworkImportDialog */
	private WSNetworkImportDialog(java.awt.Frame parent, boolean modal) {
		super(parent, modal);

		clientNames = new HashMap<String, String>();

		initComponents();
		setDatasource();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */

	// <editor-fold defaultstate="collapsed" desc=" Generated Code">                          
	private void initComponents() {
		this.setTitle("Import Network via Web Services");

		mainPanel = new javax.swing.JPanel();
		titleLabel = new javax.swing.JLabel();
		datasourceLabel = new javax.swing.JLabel();
		datasourceComboBox = new javax.swing.JComboBox();
		searchTermScrollPane = new javax.swing.JScrollPane();
		searchTermTextPane = new javax.swing.JTextPane();
		searchButton = new javax.swing.JButton();
		cancelButton = new javax.swing.JButton();
		resetButton = new javax.swing.JButton();
		optionButton = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setBackground(new java.awt.Color(255, 255, 255));
		mainPanel.setBackground(new java.awt.Color(255, 255, 255));
		titleLabel.setBackground(new java.awt.Color(255, 255, 255));
		titleLabel.setFont(new java.awt.Font("SansSerif", 1, 18));
		titleLabel.setIcon(new javax.swing.ImageIcon("/cellar/users/kono/workspace/FRESH4/images/ximian/network.png"));
		titleLabel.setText("Import Network from Web Service");

		datasourceLabel.setText("Datasource:");

		datasourceComboBox.addActionListener(new java.awt.event.ActionListener() {
				public void actionPerformed(java.awt.event.ActionEvent evt) {
					datasourceComboBoxActionPerformed(evt);
				}
			});

		searchTermTextPane.setFont(new java.awt.Font("SansSerif", 0, 12));
		searchTermTextPane.setText("Please enter search terms...");
		searchTermScrollPane.setViewportView(searchTermTextPane);

		searchButton.setText("Search");
		searchButton.addActionListener(new java.awt.event.ActionListener() {
				public void actionPerformed(java.awt.event.ActionEvent evt) {
					searchButtonActionPerformed(evt);
				}
			});

		cancelButton.setText("Cancel");
		cancelButton.addActionListener(new java.awt.event.ActionListener() {
				public void actionPerformed(java.awt.event.ActionEvent evt) {
					cancelButtonActionPerformed(evt);
				}
			});

		resetButton.setText("Reset");
		resetButton.addActionListener(new java.awt.event.ActionListener() {
				public void actionPerformed(java.awt.event.ActionEvent evt) {
					resetButtonActionPerformed(evt);
				}
			});

		optionButton.setText("Options");
		optionButton.addActionListener(new java.awt.event.ActionListener() {
				public void actionPerformed(java.awt.event.ActionEvent evt) {
					optionButtonActionPerformed(evt);
				}
			});

		org.jdesktop.layout.GroupLayout mainPanelLayout = new org.jdesktop.layout.GroupLayout(mainPanel);
		mainPanel.setLayout(mainPanelLayout);
		mainPanelLayout.setHorizontalGroup(mainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
		                                                  .add(org.jdesktop.layout.GroupLayout.TRAILING,
		                                                       mainPanelLayout.createSequentialGroup()
		                                                                      .addContainerGap()
		                                                                      .add(mainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
		                                                                                          .add(org.jdesktop.layout.GroupLayout.LEADING,
		                                                                                               searchTermScrollPane,
		                                                                                               org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
		                                                                                               561,
		                                                                                               Short.MAX_VALUE)
		                                                                                          .add(org.jdesktop.layout.GroupLayout.LEADING,
		                                                                                               titleLabel)
		                                                                                          .add(mainPanelLayout.createSequentialGroup()
		                                                                                                              .add(resetButton)
		                                                                                                              .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
		                                                                                                              .add(optionButton)
		                                                                                                              .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED,
		                                                                                                                               248,
		                                                                                                                               Short.MAX_VALUE)
		                                                                                                              .add(cancelButton)
		                                                                                                              .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
		                                                                                                              .add(searchButton))
		                                                                                          .add(org.jdesktop.layout.GroupLayout.LEADING,
		                                                                                               mainPanelLayout.createSequentialGroup()
		                                                                                                              .add(datasourceLabel)
		                                                                                                              .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
		                                                                                                              .add(datasourceComboBox,
		                                                                                                                   0,
		                                                                                                                   476,
		                                                                                                                   Short.MAX_VALUE)))
		                                                                      .addContainerGap()));
		mainPanelLayout.setVerticalGroup(mainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
		                                                .add(mainPanelLayout.createSequentialGroup()
		                                                                    .addContainerGap()
		                                                                    .add(titleLabel)
		                                                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
		                                                                    .add(mainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
		                                                                                        .add(datasourceLabel)
		                                                                                        .add(datasourceComboBox,
		                                                                                             org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
		                                                                                             org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
		                                                                                             org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
		                                                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
		                                                                    .add(searchTermScrollPane,
		                                                                         org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
		                                                                         259,
		                                                                         Short.MAX_VALUE)
		                                                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
		                                                                    .add(mainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
		                                                                                        .add(searchButton)
		                                                                                        .add(cancelButton)
		                                                                                        .add(resetButton)
		                                                                                        .add(optionButton))
		                                                                    .addContainerGap()));

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
		                                .add(mainPanel,
		                                     org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
		                                     org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
		                                     Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
		                              .add(mainPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
		                                   org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
		                                   Short.MAX_VALUE));
		pack();
	} // </editor-fold>                        

	private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {
		Cytoscape.getPropertyChangeSupport()
		         .firePropertyChange("SEARCH_NETWORK", this.searchTermTextPane.getText(),
		                             clientNames.get(datasourceComboBox.getSelectedItem()));
	}

	private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {
		dispose();
	}

	private void optionButtonActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void datasourceComboBoxActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void setDatasource() {
		List<WebServiceClient> clients = WebServiceClientManager.getAllClients();

		for (WebServiceClient client : clients) {
			if (client.getClientType().equals(ClientType.NETWORK)) {
				this.datasourceComboBox.addItem(client.getDisplayName());
				this.clientNames.put(client.getDisplayName(), client.getClientID());
			}
		}
	}

	// Variables declaration - do not modify                     
	private javax.swing.JButton cancelButton;
	private javax.swing.JComboBox datasourceComboBox;
	private javax.swing.JLabel datasourceLabel;
	private javax.swing.JPanel mainPanel;
	private javax.swing.JButton optionButton;
	private javax.swing.JButton resetButton;
	private javax.swing.JButton searchButton;
	private javax.swing.JScrollPane searchTermScrollPane;
	private javax.swing.JTextPane searchTermTextPane;
	private javax.swing.JLabel titleLabel;

	// End of variables declaration                   
}
