/*
 * LogLikelihoodPanel.java
 *
 * Created on May 11, 2006, 5:14 PM
 */

package NetworkBLAST.panels.scoreModelPanels;

/**
 *
 * @author  slotia
 */
public class LogLikelihoodPanel extends javax.swing.JPanel {
    
    /**
     * Creates new form LogLikelihoodPanel
     */
    public LogLikelihoodPanel() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        truthFactorTextField = new javax.swing.JTextField();
        truthModelTextField = new javax.swing.JTextField();
        bkgndProbTextField = new javax.swing.JTextField();
        truthFactorWarningLabel = new javax.swing.JLabel();
        truthFactorWarningLabel.setVisible(false);
        truthModelWarningLabel = new javax.swing.JLabel();
        truthModelWarningLabel.setVisible(false);
        bkgndProbWarningLabel = new javax.swing.JLabel();
        bkgndProbWarningLabel.setVisible(false);
        jButton1 = new javax.swing.JButton();

        jLabel1.setText("Truth Factor:");

        jLabel2.setText("Truth Model:");

        jLabel3.setText("Background Probability:");

        truthFactorTextField.setText("2.5");
        truthFactorTextField.setToolTipText("The factor used to consider the background truth distribution.");
        truthFactorTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                truthFactorActionPerformed(evt);
            }
        });
        truthFactorTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                truthFactorFocusLost(evt);
            }
        });

        truthModelTextField.setText("0.8");
        truthModelTextField.setToolTipText("Truth for the model. Must be between 0 and 1.");
        truthModelTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                truthModelActionPerformed(evt);
            }
        });
        truthModelTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                truthModelFocusLost(evt);
            }
        });

        bkgndProbTextField.setText("1e-10");
        bkgndProbTextField.setToolTipText("");
        bkgndProbTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkgndProbActionPerformed(evt);
            }
        });
        bkgndProbTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                bkgndProbFocusLost(evt);
            }
        });

        truthFactorWarningLabel.setFont(new java.awt.Font("Dialog", 0, 10));
        truthFactorWarningLabel.setForeground(new java.awt.Color(204, 51, 0));
        truthFactorWarningLabel.setText("Warning: Truth Factor must be a number.");

        truthModelWarningLabel.setFont(new java.awt.Font("Dialog", 0, 10));
        truthModelWarningLabel.setForeground(new java.awt.Color(204, 51, 0));
        truthModelWarningLabel.setText("Warning: Truth Model must be a number between 0 and 1.");

        bkgndProbWarningLabel.setFont(new java.awt.Font("Dialog", 0, 10));
        bkgndProbWarningLabel.setForeground(new java.awt.Color(204, 51, 0));
        bkgndProbWarningLabel.setText("Warning: Background Probability must be a number.");

        jButton1.setText("Restore Defaults");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restoreDefaults(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel1)
                            .add(jLabel2)
                            .add(jLabel3))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(truthModelTextField)
                            .add(truthFactorTextField)
                            .add(bkgndProbTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 64, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(truthFactorWarningLabel)
                            .add(truthModelWarningLabel)
                            .add(bkgndProbWarningLabel)))
                    .add(jButton1))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(truthFactorTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(truthFactorWarningLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(truthModelTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(truthModelWarningLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(bkgndProbTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel3)
                    .add(bkgndProbWarningLabel))
                .add(47, 47, 47)
                .add(jButton1)
                .addContainerGap(76, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bkgndProbFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bkgndProbFocusLost
        checkBkgndProbInput();
    }//GEN-LAST:event_bkgndProbFocusLost

    private void bkgndProbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkgndProbActionPerformed
        checkBkgndProbInput();
    }//GEN-LAST:event_bkgndProbActionPerformed

    private void truthModelFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_truthModelFocusLost
        checkTruthModelInput();
    }//GEN-LAST:event_truthModelFocusLost

    private void truthModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_truthModelActionPerformed
        checkTruthModelInput();
    }//GEN-LAST:event_truthModelActionPerformed

    private void truthFactorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_truthFactorFocusLost
        checkTruthFactorInput();
    }//GEN-LAST:event_truthFactorFocusLost

    private void truthFactorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_truthFactorActionPerformed
        checkTruthFactorInput();
    }//GEN-LAST:event_truthFactorActionPerformed

    private void restoreDefaults(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restoreDefaults
        truthFactorTextField.setText("2.5");
        truthModelTextField.setText("0.8");
        bkgndProbTextField.setText("1e-10");
        
        truthFactorWarningLabel.setVisible(false);
        truthModelWarningLabel.setVisible(false);
        bkgndProbWarningLabel.setVisible(false);
    }//GEN-LAST:event_restoreDefaults

    private void checkTruthFactorInput() {
        try
        {
            Double.parseDouble(this.truthFactorTextField.getText());
        }
        catch (NumberFormatException e)
        {
            this.truthFactorWarningLabel.setVisible(true);
            return;
        }
        this.truthFactorWarningLabel.setVisible(false);
    }
    
    private void checkTruthModelInput() {
        try
        {
            double v = Double.parseDouble(this.truthModelTextField.getText());
            if ( !( 0.0 <= v && v <= 1.0 ) )
                throw new NumberFormatException();
        }
        catch (NumberFormatException e)
        {
            this.truthModelWarningLabel.setVisible(true);
            return;
        }
        
        this.truthModelWarningLabel.setVisible(false);
    }
    
    private void checkBkgndProbInput() {
        try
        {
            Double.parseDouble(this.bkgndProbTextField.getText());
        }
        catch (NumberFormatException e)
        {
            this.bkgndProbWarningLabel.setVisible(true);
            return;
        }
        
        this.bkgndProbWarningLabel.setVisible(false);
    }
    
    public javax.swing.JTextField getBkgndProbTextField()
    {
        return this.bkgndProbTextField;
    }
    
    public javax.swing.JTextField getTruthFactorTextField()
    {
        return this.truthFactorTextField;
    }
    
    public javax.swing.JTextField getTruthModelTextField()
    {
        return this.truthModelTextField;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bkgndProbTextField;
    private javax.swing.JLabel bkgndProbWarningLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField truthFactorTextField;
    private javax.swing.JLabel truthFactorWarningLabel;
    private javax.swing.JLabel truthFactorWarningLabel1;
    private javax.swing.JTextField truthModelTextField;
    private javax.swing.JLabel truthModelWarningLabel;
    private javax.swing.JLabel warningLabel2;
    // End of variables declaration//GEN-END:variables
    
}
