cp ./Neg_atg/h_sap_atgs3.ps .
cp ./Neg_atg/m_mus_atgs3.ps .
cp ./Neg_atg/d_mel_atgs3.ps .
cp ./Neg_atg/c_ele_atgs3.ps .
cp ./Neg_atg/s_cer_atgs3.ps .
cp ./Neg_atg/a_tha_atgs3.ps .
cp ./Neg_atg/ecoli_atgs3.ps .
cp ./Neg_atg/hi.se_atgs3.ps .
cp ./Neg_atg/bsub.atgs3.ps .
cp ./Neg_atg/synec_atgs3.ps .
cp ./Neg_atg/mp.se_atgs3.ps .
cp ./Neg_atg/mg.se_atgs3.ps .
cp ./Neg_atg/atgdist.ps .
