<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html>
<head>
<meta name="generator" content="HTML Tidy, see www.w3.org">
<meta http-equiv="content-type" content=
"text/html; charset=ISO-8859-1">
<title>Cytoscape Online Tutorial</title>
<link rel="stylesheet" type="text/css" media="screen" href=
"../css/cytoscape.css">
<meta http-equiv="CONTENT-TYPE" content="text/html; charset=utf-8">
<meta name="AUTHOR" content="Melissa Cline">
<style type="text/css">
  <!--
    @page { size: 8.27in 11.69in; margin-right: 1.25in; margin-top: 1in; margin-bottom: 1in }
    P { margin-bottom: 0.08in; direction: ltr; color: #000000; widows: 0; orphans: 0 }
    P.western { font-family: "Nimbus Roman No9 L", "Times New Roman", serif; font-size: 12pt; so-language: en-US }
    P.cjk { font-family: "Times New Roman", serif; font-size: 12pt }
    P.ctl { font-family: "Times New Roman", serif; font-size: 10pt }
  -->
  
</style>
</head>
<body lang="en-US" text="#000000">
<table id="feature" border="0" cellpadding="0" cellspacing="0"
summary="">
<tr>
<td width="10"></td>
<td valign="center">
<h1>Cytoscape Online Tutorial</h1>
</td>
</tr>
</table>

<? include "nav.php"; ?>
<? include "nav_tut.php"; ?>
<div id="indent">
<center>
<h2>Using the Agilent Literature Search plugin</h2>
</center>

<p>In cases where there are few measured interactions, text mining
can be a useful mechanism for inferring network data. The Agilent
Literature Search plugin in Cytoscape provides a flexible,
interactive platform for mining text, and assessing the results in
a network context. Here we shall explore the use of this
plugin.</p>

<p>This plugin searches public literature repositories such as
PubMed for articles matching user-specified queries, and then
builds a network based on putative associations suggested in the
text of the artices. Putative associations are sentences of two or
more gene or protein names, and verbs that suggest interaction such
as "catalyzes", "is repressed by", or "regulates". For
a description of the algorithm, see the following <a href=
"http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=pubmed&amp;dopt=Abstract&amp;list_uids=15608051&amp;query_hl=1&amp;itool=pubmed_docsum">
article</a></p>

<p>If you have completed the basic Cytoscape tutorials, in this
tutorial you will</p>

<ul>
<li>Learn how to apply the Agilent Literature Search plugin to
build a network of putative molecular associations from a set of
literature search terms</li>

<li>Explore the associations generated by the plugin, and learn how
to remove any that you judge to be in error.</li>

<li>Learn how to refine your search by using context
information.</li>
</ul>

This tutorial and accompanying lectures were delivered at <a href=
"http://www.csc.fi/suomi/info/index.phtml.en">CSC</a>, the Finnish
IT center for science. The lecture slides of background material
are available <a href="litsearch.ppt">here</a> and an accompanying
video presentation is available <a href=
"http://rm.tv.funet.fi:8080/ramgen/fi/csc/kurssit/2005/cytoscape/_cytos03.rm">
here</a> courtesy of CSC. 

<p><b><i>Important:</i></b> Public literature repositories such as
PubMed are always changing. The illustrations shown here are based
on the public literature databases as they existed when this
document was written. At another time, after more papers have been
published, the composition of the databases will change, and the
exact search results will change. Consequently, <b>your own search
results will probably not look exactly like the ones shown
here</b>.</p>

<p><br>
</p>

<p>If you have not already done so, download and install Cytoscape
on your local computer, following the instructions given in the
Cytoscape manual.</p>

<p>Download and install the Agilent Literature Search plugin, as
follows:</p>

<ol>
<li>Go to the <a href=
"http://www.agilent.com/labs/research/mtl/projects/sysbio/sysinformatics/downloadv2.html">
plugin license page</a></li>

<li>Read the license agreement and fill out the short form below,
clicking the checkbox to accept the terms of the agreement.</li>

<li>Click on the <b>Proceed to Download</b> button, proceeding from
there to the plugin download page.</li>

<li>Select the installer for your platform (Windows, Mac OS X, or
Linux), click on the appropriate download link, and follow the
installation instructions provided via the adjacent <b>View</b>
link.</li>

<li>If you are currently running Cytoscape, exit.</li>
</ol>

<br>
<br>
 

<h3>Basic operation</h3>

<ol>
<li>
Start up Cytoscape. Under the <b>Plugins</b> menu, select
<b>Agilent Literature Search</b>. The following window should
appear.

<p><img src="litsearch/Fig1.jpg" width="40%"></p>
</li>

<li>
In the <b>Terms</b> window, enter <b>P53</b>. The term "P53""
should appear in the <b>Query Editor</b>, and the forward arrow
just below should turn blue to indicate it is available. Click on
the forward arrow to begin searching.
</li>

<li>
After a brief interval, the search results should appear in two
places:

<ol>
<li>
Under <b>Query Matches</b>, there should appear a numbered list
of articles labeled <b>Results</b>, as shown below. A slider at the
right side of the window allows you to scroll through the list of
selected articles. Each article should be listed along with a URL,
and a hyperlink for jumping directly to that URL.</p>
Since the number of matches was set to ten, then up to ten
articles will be displayed. In general, these are the most recent
articles that match your search terms. If you bring up a web browser
and search PubMed on the same search
term (P53) you should see exactly the same matches.
</li>

<p><img src="litsearch/Fig2.jpg" width="40%"></p>

<li>
A network should appear on the Cytoscape canvas as illustrated
below, showing interactions inferred from sentences in the selected
articles.
</li>

<img src="litsearch/Fig3.jpg" width="40%"></p>
</OL>

<LI>
In this case, the canvas shows tp53 at the center of a network
of eight nodes, with a disjoint network of two nodes (e2f1 and
prkr) at the side.
How did an interaction between e2f1 and prkr get into a
network generated by a search on P53? This is a consequence of the
two-step process used by the Literature Search plugin:
</li>

<ol>
<li>
First, it selects articles according to your query terms. In
general, this retrieves articles based on comparing the search term
to the abstract and keywords.
</li>

<li>
Second, it scans the <b>complete</b> text of the articles for sentences describing
putative interactions between genes or proteins. It then
adds <b>all</b> putative
interactions to the network, whether or not they involve any of the
search terms. Why? If a putative interaction appeared in an article
that relates to the search tems, then it's expected that it relates
to the search terms in some way.
</li>

<li>
In consequence, when you
perform a literature search, you will typically get a network with
many genes or proteins that you did not search for specifically. In
some cases, the genes or proteins that you did search for might not
appear in your network. This is not a bug or a usage error: it
simply reflects what putative interactions were found in the
articles retrieved. You can usually avoid this by increasing the
number of matches.
</OL>
</OL>
<P>
<H3>Validating, refining, and saving your search results</H3>
You can explore the sentences that were selected as evidence of
interaction between these nodes, as follows:
<OL>
<LI>Go to your Cytoscape canvas and
click on some edge with your right mouse button. A menu
should appear listing the interaction and listing a sub-menu
labeled <b>Evidence from Literature</b> This sub-menu should have 
two options,
labeled <b>Show Sentences from the Literature</b> and
<b>Gather Evidence from the
Literature</b>
</li>

<li>
Select <b>Show Sentences from the Literature</b>. A window
should appear, listing a number of sentences as shown:
</li>

<P><img src="litsearch/Fig4.jpg" width="90%">


<li>
Recall that each of these sentences is <i>predicted</i> to
represent an interaction between these two proteins. What if you
disagree with one of these predictions? Right click on the
sentence, and a button should appear saying <b>Delete Sentence</b>.
Click on the button to delete the sentence, or click elsewhere to
keep it.
</li>

<li>
Delete all the sentences for these two nodes. When you are done,
notice that the canvas has changed: the edge between these nodes
has been removed. Since this leaves the two nodes with no
connections, the nodes are also deleted.
</li>
</ol>


<p>In addition to exploring individual sentences, you can explore
the evidence from entire articles, as follows:</p>

<ol>
<li>
Return to the <b>Query Matches</b> section of the <b>Agilent
Literature Search</b> window.
</li>

<li>
Right-click on the first match.
</li>

<li>
A popup menu should appear with the options <b>Delete Match</b>
and <b>Highlight Match</b>. Click <b>Delete Match</b>.
</li>

<li>
The match to the first article will now be removed, along with
any interactions supported by that article only. After deleting the
first match, any nodes are edges that are supported by only that
article will be deleted.
</li>

<p><img src="litsearch/Fig5.jpg" width="40%"></p>


<li>
Now, highlight the matches from your new first article.
Right-click on the match, and select "Highlight Match. On your
Cytoscape canvas, the matches derived from this article should be
highlighted. The nodes should turn yellow, and the edges between
them should turn red.
</li>
<LI>
Go to the <b>Agilent Literature Search</b> window. Under the
<b>File</b> menu,
you will see options labeled <b>Load Search Results</b> and 
<b>Save Search Results.</b>If you want to save a set of
search results for later analysis, these options will allow you to
do so.
</OL>
<P>
<H3> Refining your search</H3>
Under the Agilent Literature Search window, there are a number
of basic search controls, as described here.

<ol>
<li>
There is a pull-down menu to select an organism.
</li>

<li>
There is a threshold on the maximum number of matches per search
engine. <B><I>Out of courtesy to the public search engines, always
try to use a low threshold!</I></B>
If you are experimenting with the use of the plugin, or have just
started a new line of analysis, always with a small number of matches
and increase that gradually as needed.
</li>

<li>
Under <b>Extraction Controls</b>, there is a menu labeled
Interaction Lexicon with a choice of <b>limited</b> and
<b>relaxed</b>. This controls the set of verbs that identify
putative protein interaction sentences: <b>limited</b> selects a
high-confidence set of verbs (such as "activate",
"methylate" and "cleave"), while <b>relaxed</b> selects a
more-permissive set (including "join", "augment", and
"induce").
<P>
Repeat your search on P53 with the Interaction Lexicon set to
<b>relaxed</b>. How has the network changed? Can you identify any
new edges? Compare the sentences associated with the old and the
new edges.
</li>

<li>
Under the <b>View</b> menu of the <b>Agilent Literature
Search</b> window, you will find the option <b>Engine
Selections</b>. When you click on <b>Engine Selections</b>, you
should see the following menu:
</li>

<p><img src="litsearch/Fig6.jpg" width="10%"></p>

<P>
Repeat your query with OMIM and USPTO selected in addition. How
does the network change?  
Return to this menu, and turn off querying OMIM and USPTO for
the moment.
</li>

<li>
Under <b>Query Controls</b>, there is a button labeled <b>Use
Aliases</b>. Click on this button, and in the <b>Query Editor</b>
you should see your search term of "p53" change to "(p53 OR
trp53 OR tp53)". This is a very useful option, because gene names
have many aliases. The only time when it is not valuable is when
you believe that the aliases really identify two distinct
macromolecules. In such cases, you can still edit your query under
the <b>Query Editor</b> to remove any alias you do not wish to
use.</p>

<ol type="i">
<li>
Repeat the search using aliases. How did your network
change?
</li>

<li>
In the <b>Query Editor</b>, modify the query so that it reads
"(p53 OR tp53)" and repeat your search. How did the network
change this time?
</li>
</ol>
</li>

<li>
You can specify multiple search terms.
Under Terms, under P53, add the oncogenes BCLX and SRC.
<b><i>Note that each term should be on a separate line.</i></b>
Your query window should appear as follows:
</li>


<p><img src="litsearch/Fig7.jpg" width="50%">
<P>
When you performing a query, you should see up to ten matches per
search term returned, and a larger network on the canvas such as the 
one shown:</p>
</li>

<P><img src="litsearch/Fig8.jpg" width="40%"></p>

<li>
Specifying a context provides a valuable way to refine your
search. This can yield a network that is more specific to your
biological question, and potentially just as large, as shown:

<ol type="i">
<li>
Set your list of terms to P53.
</li>

<li>
In the <b>Context</b> window, enter "Cancer".
</li>

<li>
Click on the <b>Use Context</b> button.
</li>

<li>
Your search window should appear as follows:
</li>

<p><img src="litsearch/Fig9.jpg"  width="50%"></p>

<li>
Notice that in your query window, your query specifies <b>P53
AND Cancer</b>.  In other words, the context acts as a filter.
</li>

<li>
Experiment with adding some additional search and context terms
(one per line) to see how the query changes. Note that you can also
enter or modify your query under the <b>Query Editor</b>.
</li>

<li>
Perform a search on <B>P53 AND Cancer</B>. You should get back ten
query matches, and a network such as the one below:
</li>

<p><img src="litsearch/Fig10.jpg" width="40%"></p>

<li>
Enter a new search on P53, this time with the context "dna
repair". <b><i>Note: when a search term consists of two or more
consecutive words, the term should be quoted.</i></b> This should
produce a different set of ten articles, as illustrated below:
</li>

<p><img src="litsearch/Fig11.jpg" width="40%"></p>
</Ol>

<li>
Context searching can also be used to control such search
parameters as what specific journals are searched. Suppose you are
interested in P53 in cancer, but only as published in the journals
<I>Science</I> or <I>Nature</I>.  You can do this search as follows:
<OL type="i">
<LI>Add the following lines to your context list:
<UL>
<LI>Science[ta]</LI>
<LI>Nature[ta]</LI>
</UL

Your query in the query editor should now read <B>(P53) AND (Cancer
OR Science[ta] OR Nature[ta])</B>. 
<LI>This is not quite
what we want: instead of returning articles on P53 and cancer
published in the selected journals, it would return articles on P53
that either involved cancer or were published in the selected
journals. So in your query editor, revise the query to read 
<B>(P53) AND Cancer AND (Science[ta] OR Nature[ta])</B>

<li>
Issue your query, and explore the query results as outlined above. 
</li>

<li>
The search context can be used in similar ways to limit PubMed
searches by MeSH term, publication date, and other attributes. For
more information, see <a href="http://www.ncbi.nlm.nih.gov/books/bv.fcgi?rid=helppubmed.box.pubmedhelp.Box_1_Search_Field_D">
the following</a> PubMed help document.
</li>
</ol>
<H3>Gathering Supporting Evidence</H3>
In addition to mining the literature for associations, you can
use the Agilent Literature Search plugin to verify other interactions
against the literature.  This section illustrates how.
<ol>
<li> Download the file <A HREF="litsearch/BINDHumanSubset.sif">
BINDHumanSubset.sif</A> to your local computer.  This is a sample
set of interactions from the <A HREF="http://bind.ca/"BIND</A> database.
<li> <B>Important:</B> this functionality relies on parameters 
defined in the last use of the Literature Search plugin, in this 
session of Cytoscape.  <EM>If you have taken a break since the 
previous steps, and have just started a new Cytoscape session, then
before continuing, you must do a literature search with Human selected
as the species</EM>
<li> Load the network <B>BINDHumanSubset.sf</B>.  Lay out the network with
the <b>yFiles Organic</B> layout.  Your Cytoscape canvas should 
appear as shown:
<P><IMG SRC="litsearch/Fig13.jpg" WIDTH="50%" BORDER=1>
<li> Select by name the node Sp1, and zoom in to get a closer
look of the other nodes that interact with it.  Your canvas should 
appear as shown:
<P><IMG SRC="litsearch/Fig14.jpg" WIDTH="50%" BORDER=1>
<li> Select the edge between Sp1 and Myc.
<li> Right-click on the edge.  You should see the menu shown below, 
with the option <B>Evidence from Literature</B>.  This item should 
take you to another menu, with the option <B>Gather Evidence from the
Literature</B>.  Select this option.
<P><IMG src="litsearch/Fig15.jpg" WIDTH="20%" BORDER=1>
<li> A literature search will be executed.  When it is done, a 
message will appear at the bottom of the Cytoscape Desktop indicating
if any new evidence was found.
<li> Go to the <B>Edge Attribute Browser</B> and click on the 
<B>Select Attributes</B> button.  You should see several new 
attributes, as follows:
<UL>
<li><B>HasTSI</B>: Indicates if the interaction is supported by
literature searching 
<li><B>NumberOfSources</B>: Indicates the number of distinct articles
supporting the interaction
<li><B>nbrSentences</B>: Indicates the number of distinct sentences
supporting the interaction
</UL> 
<li>How much support is there for this interaction?
<li> Go back to the Cytoscape Desktop, and right-click on the edge
between Myc and Sd1.  If any evidence was found in the literature for
this interaction, then under <B>Evidence from Literature</B>, there 
should be a new option: <B>Show Sentences from the Literature</B>.
Selecting this option will bring up a window listing the supporting
sentences, as shown below.
<P><IMG SRC="litsearch/Fig16.jpg" WIDTH="70%">
<li>Exactly what was the search that generated these results?  The
<B>Gather Evidence</B> function performs a search of ten articles per
search term, using the two nodes as search terms and using the species
and interaction lexicon used in the last full literature search.  For
example, if your last full literature search was done on mouse with a 
relaxed interaction lexicon, then the <B>Gather Evidence</B> function 
would search for the two nodes in mouse, and using a relaxed interaction
lexicon.
<li>You can also gather evidence on all the edges for a give
<li>Select the node YY1.
<li>Right-click on this node.
<li>In the right-click menu, select <B>Gather Evidence from the Literature</B>.
This will perform a literature search on all the edges of the node.
</ol>
</ol>

</ol>

<p><b>Congratulations!</b> You have not only completed one more
tutorial, but you"ve also learned how to use a powerful tool is
also fun to play with!</p>
</div>

<? include "tut.footer.php"; ?>
<? include "../footer.php"; ?>
</p>

</body>
</html>

