#!/bin/bash

# -html generate HTML
# -run  run R code
# -mtd NUMBER (set min telomere distance cutoff)
# -image [ps|pdf|png]
# -network write SIF file

if [ -z "$1" ]; then
    OPTS="-html -run -image png" #default options, #
else
    OPTS=$1
fi

#allProbes.txt.withSize
RUN_HARBISON=
RUN_BOYER=
RUN_SIMON=
RUN_WORKMAN=
RUN_YEAST_ANNOTATION=
RUN_GASCH=
RUN_HUGHES=
RUN_GIAEVER=
RUN_TAN=1

echo "### OPTS = $OPTS"

# Harbison
test $RUN_HARBISON  && {
HARBISON=/Users/cmak/Desktop/ChIP-papers/Harbison
mkdir output/harbison_YPD
mkdir output/harbison_YPD_noY
mkdir output/harbison_Other
mkdir output/harbison_Other_noY
./cpos.pl $OPTS -bkgdFile ~/data/all-SGD-ORFs.loc -mtd 30000 -featureType sgd -org sc  output/harbison_YPD $HARBISON/Harbison2004_9.2_forpaper_YPD.1e-3.ORFlists 

./cpos.pl $OPTS -bkgdFile ~/data/all-SGD-ORFs.loc -mtd 30000 -featureType sgd -org sc  output/harbison_YPD_noY $HARBISON/Harbison2004_9.2_forpaper_YPD.1e-3.noY-element.ORFlists 

./cpos.pl $OPTS -bkgdFile ~/data/all-SGD-ORFs.loc -mtd 30000 -featureType sgd -org sc  output/harbison_Other $HARBISON/Harbison2004_9.2_forpaper_Other.1e-3.ORFlists 

./cpos.pl $OPTS -bkgdFile ~/data/all-SGD-ORFs.loc -mtd 30000 -featureType sgd -org sc  output/harbison_Other_noY $HARBISON/Harbison2004_9.2_forpaper_Other.1e-3.noY-element.ORFlists 
}

# Boyer
test $RUN_BOYER && {
BOYER=/Users/cmak/Desktop/ChIP-papers/Boyer-2005-HumanES
./cpos.pl  $OPTS -featureType boyer -mtd 300000 -featureFile $BOYER/Oct4-TableS1.txt -org hs  output/boyer_EShuman  \
     $BOYER/Oct4-TableS1.txt \
     $BOYER/Nanog-TableS4.txt \
     $BOYER/Sox2-TableS3.txt \
     $BOYER/E2F4-TableS6.txt
}

# Simon
test $RUN_SIMON && {
SIMON=/Users/cmak/Desktop/ChIP-papers/Simon-2001
mkdir output/simon
./cpos.pl $OPTS -bkgdFile ~/data/all-SGD-ORFs.loc -featureType sgd -mtd 30000 -org sc  output/simon  $SIMON/Simon.p001.ORFlists
}

# Gasch ESR
test $RUN_GASCH && {
GASCH=/Users/cmak/Desktop/ChIP-papers/Gasch-ESR
mkdir output/gasch-esr
./cpos.pl $OPTS -bkgdFile ~/data/all-SGD-ORFs.loc -featureType sgd -mtd 30000 -org sc  output/gasch-esr  $GASCH/ESR_Gasch2000.ORFlists
}


# Hughes Compendium
test $RUN_HUGHES && {
HUGHES=/Users/cmak/Desktop/ChIP-papers/Hughes-rosetta
mkdir output/hughes-rosetta
./cpos.pl $OPTS -bkgdFile ~/data/all-SGD-ORFs.loc -featureType sgd -mtd 30000 -org sc  output/hughes-rosetta  $HUGHES/data_expts1-300_geneerr.p01.ORFlists
}


# Workman
test $RUN_WORKMAN  && {
WORKMAN=/Users/cmak/Desktop/ChIP-papers/Workman
mkdir output/workman_BLA
mkdir output/workman_BUF
mkdir output/workman_EXP_KOs
mkdir output/workman_BLA_MMSonly
mkdir output/workman_BLA_YPDonly
mkdir output/workman_EXP_WT

PARAMS=" $OPTS -bkgdFile ~/data/all-SGD-ORFs.loc -featureType sgd -org sc -mtd 30000"

./cpos.pl $PARAMS  output/workman_BLA $WORKMAN/YPD_0.001_MMS_0.001_t_0.1436_t_sq_0.000144.ORFlists
./cpos.pl $PARAMS output/workman_BUF $WORKMAN/BUF_KOs.005.ORFlists
#./cpos.pl $PARAMS output/workman_EXP_KOs $WORKMAN/EXP_KOs.const_betas.logratios.pvalues
./cpos.pl $PARAMS output/workman_BLA_MMSonly $WORKMAN/BLA_MMS_only.1e-3.TPM.ORFlists
./cpos.pl $PARAMS output/workman_BLA_YPDonly $WORKMAN/BLA_YPD_only.1e-3.TPM.ORFlists
./cpos.pl $PARAMS output/workman_EXP_WT $WORKMAN/EXP_Fisher_top514.ORFlists
}

test $RUN_YEAST_ANNOTATION && {
YA=/Users/cmak/Desktop/ChIP-papers/YeastAnnotation
mkdir output/MIPS_complexes
mkdir output/MIPS_subcell
mkdir output/MIPS_funcat
mkdir output/MIPS_phenotype
mkdir output/MIPS_protein_classes
mkdir output/SGDbiochem_pathway
mkdir output/KEGG_metabolic
mkdir output/GO_process
mkdir output/GO_function
mkdir output/GO_component


PARAMS=" $OPTS -bkgdFile ~/data/all-SGD-ORFs.loc -featureType sgd -org sc -mtd 30000"
./cpos.pl $PARAMS output/MIPS_complexes $YA/MIPS_complexes.ORFlists
./cpos.pl $PARAMS output/MIPS_subcell $YA/MIPS_subcell.ORFlists
./cpos.pl $PARAMS output/MIPS_funcat $YA/MIPS_funcat.ORFlists
./cpos.pl $PARAMS output/MIPS_protein_classes $YA/MIPS_protein_classes.ORFlists
./cpos.pl $PARAMS output/MIPS_phenotype $YA/MIPS_phenotype.ORFlists
./cpos.pl $PARAMS output/KEGG_metabolic $YA/KEGGmetabolic.ORFlists
./cpos.pl $PARAMS output/GO_process $YA/GOprocess.ORFlists
./cpos.pl $PARAMS output/GO_component $YA/GOcomponent.ORFlists
./cpos.pl $PARAMS output/GO_function $YA/GOfunction.ORFlists
./cpos.pl $PARAMS output/SGDbiochem_pathway $YA/SGDbiochem_pathway.ORFlists
}

# Giaever yeast knockout collection phenotyping
test $RUN_GIAEVER && {
GIAEVER=/Users/cmak/Desktop/ChIP-papers/Giaever-YKO
mkdir output/giaever-YKO
./cpos.pl $OPTS -ks two.sided -bkgdFile $GIAEVER/YKO-ORFs.loc -featureType sgd -featureFile $GIAEVER/YKO-SGD_features.tab -mtd 30000 -org sc  output/giaever-YKO  $GIAEVER/YKO-100.ORFlists
}


# Kai's YAP data
test $RUN_TAN && {
TAN=/Users/cmak/Desktop/ChIP-papers/Tan-YAP
TAN_OUT=output/tan-YAP
mkdir $TAN_OUT
./cpos.pl $OPTS -bkgdFile ~/data/all-SGD-ORFs.loc -featureType sgd -mtd 30000 -org sc  $TAN_OUT  $TAN/KT-YAP-NT.chip-regulon.ORFlists
}


./buildIndex.pl output > output/index.html
