source("ProbeDist.R")
png(file="Harbison2004_9.2_forpaper_YPD.1e-3.ORFlists.bkgd.png", width=300, height=300)

dat <- read.table(file="all-SGD-ORFs.loc", header=T)
all.results <- plot.hist2(dat, main="All ORFs",ylim=c(0,800))
bkgd.max <-  all.results$h$mids[which.max(all.results$h$counts)]
abline(v=bkgd.max, col="red", lty=2)
dev.off()
D.list <- list()
png(filename="output/ABF1.loc.png", width=300, height=300)
dat <- read.table(file="output/ABF1.loc", header=T)
results <- plot.hist.modular(dat, main="ABF1", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="ABF1", D=results$D)))
dev.off()

png(filename="output/ACA1.loc.png", width=300, height=300)
dat <- read.table(file="output/ACA1.loc", header=T)
results <- plot.hist.modular(dat, main="ACA1", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="ACA1", D=results$D)))
dev.off()

png(filename="output/ACE2.loc.png", width=300, height=300)
dat <- read.table(file="output/ACE2.loc", header=T)
results <- plot.hist.modular(dat, main="ACE2", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="ACE2", D=results$D)))
dev.off()

png(filename="output/ADR1.loc.png", width=300, height=300)
dat <- read.table(file="output/ADR1.loc", header=T)
results <- plot.hist.modular(dat, main="ADR1", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="ADR1", D=results$D)))
dev.off()

png(filename="output/AFT2.loc.png", width=300, height=300)
dat <- read.table(file="output/AFT2.loc", header=T)
results <- plot.hist.modular(dat, main="AFT2", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="AFT2", D=results$D)))
dev.off()

png(filename="output/ARG80.loc.png", width=300, height=300)
dat <- read.table(file="output/ARG80.loc", header=T)
results <- plot.hist.modular(dat, main="ARG80", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="ARG80", D=results$D)))
dev.off()

png(filename="output/ARG81.loc.png", width=300, height=300)
dat <- read.table(file="output/ARG81.loc", header=T)
results <- plot.hist.modular(dat, main="ARG81", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="ARG81", D=results$D)))
dev.off()

png(filename="output/ARO80.loc.png", width=300, height=300)
dat <- read.table(file="output/ARO80.loc", header=T)
results <- plot.hist.modular(dat, main="ARO80", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="ARO80", D=results$D)))
dev.off()

png(filename="output/ARR1.loc.png", width=300, height=300)
dat <- read.table(file="output/ARR1.loc", header=T)
results <- plot.hist.modular(dat, main="ARR1", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="ARR1", D=results$D)))
dev.off()

png(filename="output/ASK10.loc.png", width=300, height=300)
dat <- read.table(file="output/ASK10.loc", header=T)
results <- plot.hist.modular(dat, main="ASK10", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="ASK10", D=results$D)))
dev.off()

png(filename="output/AZF1.loc.png", width=300, height=300)
dat <- read.table(file="output/AZF1.loc", header=T)
results <- plot.hist.modular(dat, main="AZF1", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="AZF1", D=results$D)))
dev.off()

png(filename="output/BAS1.loc.png", width=300, height=300)
dat <- read.table(file="output/BAS1.loc", header=T)
results <- plot.hist.modular(dat, main="BAS1", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="BAS1", D=results$D)))
dev.off()

png(filename="output/CAD1.loc.png", width=300, height=300)
dat <- read.table(file="output/CAD1.loc", header=T)
results <- plot.hist.modular(dat, main="CAD1", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="CAD1", D=results$D)))
dev.off()

png(filename="output/CBF1.loc.png", width=300, height=300)
dat <- read.table(file="output/CBF1.loc", header=T)
results <- plot.hist.modular(dat, main="CBF1", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="CBF1", D=results$D)))
dev.off()

png(filename="output/CHA4.loc.png", width=300, height=300)
dat <- read.table(file="output/CHA4.loc", header=T)
results <- plot.hist.modular(dat, main="CHA4", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="CHA4", D=results$D)))
dev.off()

png(filename="output/CIN5.loc.png", width=300, height=300)
dat <- read.table(file="output/CIN5.loc", header=T)
results <- plot.hist.modular(dat, main="CIN5", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="CIN5", D=results$D)))
dev.off()

png(filename="output/CST6.loc.png", width=300, height=300)
dat <- read.table(file="output/CST6.loc", header=T)
results <- plot.hist.modular(dat, main="CST6", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="CST6", D=results$D)))
dev.off()

png(filename="output/CUP9.loc.png", width=300, height=300)
dat <- read.table(file="output/CUP9.loc", header=T)
results <- plot.hist.modular(dat, main="CUP9", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="CUP9", D=results$D)))
dev.off()

png(filename="output/DAL80.loc.png", width=300, height=300)
dat <- read.table(file="output/DAL80.loc", header=T)
results <- plot.hist.modular(dat, main="DAL80", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="DAL80", D=results$D)))
dev.off()

png(filename="output/DAL81.loc.png", width=300, height=300)
dat <- read.table(file="output/DAL81.loc", header=T)
results <- plot.hist.modular(dat, main="DAL81", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="DAL81", D=results$D)))
dev.off()

png(filename="output/DAL82.loc.png", width=300, height=300)
dat <- read.table(file="output/DAL82.loc", header=T)
results <- plot.hist.modular(dat, main="DAL82", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="DAL82", D=results$D)))
dev.off()

png(filename="output/DAT1.loc.png", width=300, height=300)
dat <- read.table(file="output/DAT1.loc", header=T)
results <- plot.hist.modular(dat, main="DAT1", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="DAT1", D=results$D)))
dev.off()

png(filename="output/DIG1.loc.png", width=300, height=300)
dat <- read.table(file="output/DIG1.loc", header=T)
results <- plot.hist.modular(dat, main="DIG1", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="DIG1", D=results$D)))
dev.off()

png(filename="output/EDS1.loc.png", width=300, height=300)
dat <- read.table(file="output/EDS1.loc", header=T)
results <- plot.hist.modular(dat, main="EDS1", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="EDS1", D=results$D)))
dev.off()

png(filename="output/FHL1.loc.png", width=300, height=300)
dat <- read.table(file="output/FHL1.loc", header=T)
results <- plot.hist.modular(dat, main="FHL1", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="FHL1", D=results$D)))
dev.off()

png(filename="output/FKH1.loc.png", width=300, height=300)
dat <- read.table(file="output/FKH1.loc", header=T)
results <- plot.hist.modular(dat, main="FKH1", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="FKH1", D=results$D)))
dev.off()

png(filename="output/FKH2.loc.png", width=300, height=300)
dat <- read.table(file="output/FKH2.loc", header=T)
results <- plot.hist.modular(dat, main="FKH2", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="FKH2", D=results$D)))
dev.off()

png(filename="output/FZF1.loc.png", width=300, height=300)
dat <- read.table(file="output/FZF1.loc", header=T)
results <- plot.hist.modular(dat, main="FZF1", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="FZF1", D=results$D)))
dev.off()

png(filename="output/GAL3.loc.png", width=300, height=300)
dat <- read.table(file="output/GAL3.loc", header=T)
results <- plot.hist.modular(dat, main="GAL3", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="GAL3", D=results$D)))
dev.off()

png(filename="output/GAL4.loc.png", width=300, height=300)
dat <- read.table(file="output/GAL4.loc", header=T)
results <- plot.hist.modular(dat, main="GAL4", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="GAL4", D=results$D)))
dev.off()

png(filename="output/GAL80.loc.png", width=300, height=300)
dat <- read.table(file="output/GAL80.loc", header=T)
results <- plot.hist.modular(dat, main="GAL80", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="GAL80", D=results$D)))
dev.off()

png(filename="output/GAT1.loc.png", width=300, height=300)
dat <- read.table(file="output/GAT1.loc", header=T)
results <- plot.hist.modular(dat, main="GAT1", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="GAT1", D=results$D)))
dev.off()

png(filename="output/GAT3.loc.png", width=300, height=300)
dat <- read.table(file="output/GAT3.loc", header=T)
results <- plot.hist.modular(dat, main="GAT3", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="GAT3", D=results$D)))
dev.off()

png(filename="output/GCN4.loc.png", width=300, height=300)
dat <- read.table(file="output/GCN4.loc", header=T)
results <- plot.hist.modular(dat, main="GCN4", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="GCN4", D=results$D)))
dev.off()

png(filename="output/GCR1.loc.png", width=300, height=300)
dat <- read.table(file="output/GCR1.loc", header=T)
results <- plot.hist.modular(dat, main="GCR1", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="GCR1", D=results$D)))
dev.off()

png(filename="output/GCR2.loc.png", width=300, height=300)
dat <- read.table(file="output/GCR2.loc", header=T)
results <- plot.hist.modular(dat, main="GCR2", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="GCR2", D=results$D)))
dev.off()

png(filename="output/GLN3.loc.png", width=300, height=300)
dat <- read.table(file="output/GLN3.loc", header=T)
results <- plot.hist.modular(dat, main="GLN3", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="GLN3", D=results$D)))
dev.off()

png(filename="output/GTS1.loc.png", width=300, height=300)
dat <- read.table(file="output/GTS1.loc", header=T)
results <- plot.hist.modular(dat, main="GTS1", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="GTS1", D=results$D)))
dev.off()

png(filename="output/GZF3.loc.png", width=300, height=300)
dat <- read.table(file="output/GZF3.loc", header=T)
results <- plot.hist.modular(dat, main="GZF3", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="GZF3", D=results$D)))
dev.off()

png(filename="output/HAC1.loc.png", width=300, height=300)
dat <- read.table(file="output/HAC1.loc", header=T)
results <- plot.hist.modular(dat, main="HAC1", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="HAC1", D=results$D)))
dev.off()

png(filename="output/HAL9.loc.png", width=300, height=300)
dat <- read.table(file="output/HAL9.loc", header=T)
results <- plot.hist.modular(dat, main="HAL9", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="HAL9", D=results$D)))
dev.off()

png(filename="output/HAP1.loc.png", width=300, height=300)
dat <- read.table(file="output/HAP1.loc", header=T)
results <- plot.hist.modular(dat, main="HAP1", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="HAP1", D=results$D)))
dev.off()

png(filename="output/HAP2.loc.png", width=300, height=300)
dat <- read.table(file="output/HAP2.loc", header=T)
results <- plot.hist.modular(dat, main="HAP2", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="HAP2", D=results$D)))
dev.off()

png(filename="output/HAP3.loc.png", width=300, height=300)
dat <- read.table(file="output/HAP3.loc", header=T)
results <- plot.hist.modular(dat, main="HAP3", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="HAP3", D=results$D)))
dev.off()

png(filename="output/HAP4.loc.png", width=300, height=300)
dat <- read.table(file="output/HAP4.loc", header=T)
results <- plot.hist.modular(dat, main="HAP4", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="HAP4", D=results$D)))
dev.off()

png(filename="output/HAP5.loc.png", width=300, height=300)
dat <- read.table(file="output/HAP5.loc", header=T)
results <- plot.hist.modular(dat, main="HAP5", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="HAP5", D=results$D)))
dev.off()

png(filename="output/HIR1.loc.png", width=300, height=300)
dat <- read.table(file="output/HIR1.loc", header=T)
results <- plot.hist.modular(dat, main="HIR1", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="HIR1", D=results$D)))
dev.off()

png(filename="output/HIR2.loc.png", width=300, height=300)
dat <- read.table(file="output/HIR2.loc", header=T)
results <- plot.hist.modular(dat, main="HIR2", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="HIR2", D=results$D)))
dev.off()

png(filename="output/HIR3.loc.png", width=300, height=300)
dat <- read.table(file="output/HIR3.loc", header=T)
results <- plot.hist.modular(dat, main="HIR3", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="HIR3", D=results$D)))
dev.off()

png(filename="output/HMS1.loc.png", width=300, height=300)
dat <- read.table(file="output/HMS1.loc", header=T)
results <- plot.hist.modular(dat, main="HMS1", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="HMS1", D=results$D)))
dev.off()

png(filename="output/HMS2.loc.png", width=300, height=300)
dat <- read.table(file="output/HMS2.loc", header=T)
results <- plot.hist.modular(dat, main="HMS2", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="HMS2", D=results$D)))
dev.off()

png(filename="output/HOG1.loc.png", width=300, height=300)
dat <- read.table(file="output/HOG1.loc", header=T)
results <- plot.hist.modular(dat, main="HOG1", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="HOG1", D=results$D)))
dev.off()

png(filename="output/HSF1.loc.png", width=300, height=300)
dat <- read.table(file="output/HSF1.loc", header=T)
results <- plot.hist.modular(dat, main="HSF1", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="HSF1", D=results$D)))
dev.off()

png(filename="output/IFH1.loc.png", width=300, height=300)
dat <- read.table(file="output/IFH1.loc", header=T)
results <- plot.hist.modular(dat, main="IFH1", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="IFH1", D=results$D)))
dev.off()

png(filename="output/IME4.loc.png", width=300, height=300)
dat <- read.table(file="output/IME4.loc", header=T)
results <- plot.hist.modular(dat, main="IME4", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="IME4", D=results$D)))
dev.off()

png(filename="output/INO2.loc.png", width=300, height=300)
dat <- read.table(file="output/INO2.loc", header=T)
results <- plot.hist.modular(dat, main="INO2", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="INO2", D=results$D)))
dev.off()

png(filename="output/INO4.loc.png", width=300, height=300)
dat <- read.table(file="output/INO4.loc", header=T)
results <- plot.hist.modular(dat, main="INO4", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="INO4", D=results$D)))
dev.off()

png(filename="output/IXR1.loc.png", width=300, height=300)
dat <- read.table(file="output/IXR1.loc", header=T)
results <- plot.hist.modular(dat, main="IXR1", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="IXR1", D=results$D)))
dev.off()

png(filename="output/KRE33.loc.png", width=300, height=300)
dat <- read.table(file="output/KRE33.loc", header=T)
results <- plot.hist.modular(dat, main="KRE33", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="KRE33", D=results$D)))
dev.off()

png(filename="output/KSS1.loc.png", width=300, height=300)
dat <- read.table(file="output/KSS1.loc", header=T)
results <- plot.hist.modular(dat, main="KSS1", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="KSS1", D=results$D)))
dev.off()

png(filename="output/LEU3.loc.png", width=300, height=300)
dat <- read.table(file="output/LEU3.loc", header=T)
results <- plot.hist.modular(dat, main="LEU3", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="LEU3", D=results$D)))
dev.off()

png(filename="output/MAC1.loc.png", width=300, height=300)
dat <- read.table(file="output/MAC1.loc", header=T)
results <- plot.hist.modular(dat, main="MAC1", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="MAC1", D=results$D)))
dev.off()

png(filename="output/MATA1.loc.png", width=300, height=300)
dat <- read.table(file="output/MATA1.loc", header=T)
results <- plot.hist.modular(dat, main="MATA1", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="MATA1", D=results$D)))
dev.off()

png(filename="output/MBF1.loc.png", width=300, height=300)
dat <- read.table(file="output/MBF1.loc", header=T)
results <- plot.hist.modular(dat, main="MBF1", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="MBF1", D=results$D)))
dev.off()

png(filename="output/MBP1.loc.png", width=300, height=300)
dat <- read.table(file="output/MBP1.loc", header=T)
results <- plot.hist.modular(dat, main="MBP1", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="MBP1", D=results$D)))
dev.off()

png(filename="output/MCM1.loc.png", width=300, height=300)
dat <- read.table(file="output/MCM1.loc", header=T)
results <- plot.hist.modular(dat, main="MCM1", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="MCM1", D=results$D)))
dev.off()

png(filename="output/MDS3.loc.png", width=300, height=300)
dat <- read.table(file="output/MDS3.loc", header=T)
results <- plot.hist.modular(dat, main="MDS3", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="MDS3", D=results$D)))
dev.off()

png(filename="output/MET18.loc.png", width=300, height=300)
dat <- read.table(file="output/MET18.loc", header=T)
results <- plot.hist.modular(dat, main="MET18", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="MET18", D=results$D)))
dev.off()

png(filename="output/MET28.loc.png", width=300, height=300)
dat <- read.table(file="output/MET28.loc", header=T)
results <- plot.hist.modular(dat, main="MET28", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="MET28", D=results$D)))
dev.off()

png(filename="output/MET31.loc.png", width=300, height=300)
dat <- read.table(file="output/MET31.loc", header=T)
results <- plot.hist.modular(dat, main="MET31", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="MET31", D=results$D)))
dev.off()

png(filename="output/MET32.loc.png", width=300, height=300)
dat <- read.table(file="output/MET32.loc", header=T)
results <- plot.hist.modular(dat, main="MET32", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="MET32", D=results$D)))
dev.off()

png(filename="output/MET4.loc.png", width=300, height=300)
dat <- read.table(file="output/MET4.loc", header=T)
results <- plot.hist.modular(dat, main="MET4", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="MET4", D=results$D)))
dev.off()

png(filename="output/MGA1.loc.png", width=300, height=300)
dat <- read.table(file="output/MGA1.loc", header=T)
results <- plot.hist.modular(dat, main="MGA1", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="MGA1", D=results$D)))
dev.off()

png(filename="output/MIG1.loc.png", width=300, height=300)
dat <- read.table(file="output/MIG1.loc", header=T)
results <- plot.hist.modular(dat, main="MIG1", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="MIG1", D=results$D)))
dev.off()

png(filename="output/MIG2.loc.png", width=300, height=300)
dat <- read.table(file="output/MIG2.loc", header=T)
results <- plot.hist.modular(dat, main="MIG2", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="MIG2", D=results$D)))
dev.off()

png(filename="output/MIG3.loc.png", width=300, height=300)
dat <- read.table(file="output/MIG3.loc", header=T)
results <- plot.hist.modular(dat, main="MIG3", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="MIG3", D=results$D)))
dev.off()

png(filename="output/MOT3.loc.png", width=300, height=300)
dat <- read.table(file="output/MOT3.loc", header=T)
results <- plot.hist.modular(dat, main="MOT3", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="MOT3", D=results$D)))
dev.off()

png(filename="output/MSN1.loc.png", width=300, height=300)
dat <- read.table(file="output/MSN1.loc", header=T)
results <- plot.hist.modular(dat, main="MSN1", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="MSN1", D=results$D)))
dev.off()

png(filename="output/MSN2.loc.png", width=300, height=300)
dat <- read.table(file="output/MSN2.loc", header=T)
results <- plot.hist.modular(dat, main="MSN2", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="MSN2", D=results$D)))
dev.off()

png(filename="output/MSN4.loc.png", width=300, height=300)
dat <- read.table(file="output/MSN4.loc", header=T)
results <- plot.hist.modular(dat, main="MSN4", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="MSN4", D=results$D)))
dev.off()

png(filename="output/MTH1.loc.png", width=300, height=300)
dat <- read.table(file="output/MTH1.loc", header=T)
results <- plot.hist.modular(dat, main="MTH1", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="MTH1", D=results$D)))
dev.off()

png(filename="output/NDD1.loc.png", width=300, height=300)
dat <- read.table(file="output/NDD1.loc", header=T)
results <- plot.hist.modular(dat, main="NDD1", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="NDD1", D=results$D)))
dev.off()

png(filename="output/NDT80.loc.png", width=300, height=300)
dat <- read.table(file="output/NDT80.loc", header=T)
results <- plot.hist.modular(dat, main="NDT80", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="NDT80", D=results$D)))
dev.off()

png(filename="output/NRG1.loc.png", width=300, height=300)
dat <- read.table(file="output/NRG1.loc", header=T)
results <- plot.hist.modular(dat, main="NRG1", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="NRG1", D=results$D)))
dev.off()

png(filename="output/OAF1.loc.png", width=300, height=300)
dat <- read.table(file="output/OAF1.loc", header=T)
results <- plot.hist.modular(dat, main="OAF1", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="OAF1", D=results$D)))
dev.off()

png(filename="output/OPI1.loc.png", width=300, height=300)
dat <- read.table(file="output/OPI1.loc", header=T)
results <- plot.hist.modular(dat, main="OPI1", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="OPI1", D=results$D)))
dev.off()

png(filename="output/PDC2.loc.png", width=300, height=300)
dat <- read.table(file="output/PDC2.loc", header=T)
results <- plot.hist.modular(dat, main="PDC2", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="PDC2", D=results$D)))
dev.off()

png(filename="output/PDR1.loc.png", width=300, height=300)
dat <- read.table(file="output/PDR1.loc", header=T)
results <- plot.hist.modular(dat, main="PDR1", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="PDR1", D=results$D)))
dev.off()

png(filename="output/PDR3.loc.png", width=300, height=300)
dat <- read.table(file="output/PDR3.loc", header=T)
results <- plot.hist.modular(dat, main="PDR3", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="PDR3", D=results$D)))
dev.off()

png(filename="output/PHD1.loc.png", width=300, height=300)
dat <- read.table(file="output/PHD1.loc", header=T)
results <- plot.hist.modular(dat, main="PHD1", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="PHD1", D=results$D)))
dev.off()

png(filename="output/PHO2.loc.png", width=300, height=300)
dat <- read.table(file="output/PHO2.loc", header=T)
results <- plot.hist.modular(dat, main="PHO2", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="PHO2", D=results$D)))
dev.off()

png(filename="output/PHO4.loc.png", width=300, height=300)
dat <- read.table(file="output/PHO4.loc", header=T)
results <- plot.hist.modular(dat, main="PHO4", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="PHO4", D=results$D)))
dev.off()

png(filename="output/PIP2.loc.png", width=300, height=300)
dat <- read.table(file="output/PIP2.loc", header=T)
results <- plot.hist.modular(dat, main="PIP2", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="PIP2", D=results$D)))
dev.off()

png(filename="output/PPR1.loc.png", width=300, height=300)
dat <- read.table(file="output/PPR1.loc", header=T)
results <- plot.hist.modular(dat, main="PPR1", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="PPR1", D=results$D)))
dev.off()

png(filename="output/PUT3.loc.png", width=300, height=300)
dat <- read.table(file="output/PUT3.loc", header=T)
results <- plot.hist.modular(dat, main="PUT3", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="PUT3", D=results$D)))
dev.off()

png(filename="output/RAP1.loc.png", width=300, height=300)
dat <- read.table(file="output/RAP1.loc", header=T)
results <- plot.hist.modular(dat, main="RAP1", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="RAP1", D=results$D)))
dev.off()

png(filename="output/RCO1.loc.png", width=300, height=300)
dat <- read.table(file="output/RCO1.loc", header=T)
results <- plot.hist.modular(dat, main="RCO1", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="RCO1", D=results$D)))
dev.off()

png(filename="output/RCS1.loc.png", width=300, height=300)
dat <- read.table(file="output/RCS1.loc", header=T)
results <- plot.hist.modular(dat, main="RCS1", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="RCS1", D=results$D)))
dev.off()

png(filename="output/RDR1.loc.png", width=300, height=300)
dat <- read.table(file="output/RDR1.loc", header=T)
results <- plot.hist.modular(dat, main="RDR1", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="RDR1", D=results$D)))
dev.off()

png(filename="output/RDS1.loc.png", width=300, height=300)
dat <- read.table(file="output/RDS1.loc", header=T)
results <- plot.hist.modular(dat, main="RDS1", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="RDS1", D=results$D)))
dev.off()

png(filename="output/REB1.loc.png", width=300, height=300)
dat <- read.table(file="output/REB1.loc", header=T)
results <- plot.hist.modular(dat, main="REB1", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="REB1", D=results$D)))
dev.off()

png(filename="output/RFX1.loc.png", width=300, height=300)
dat <- read.table(file="output/RFX1.loc", header=T)
results <- plot.hist.modular(dat, main="RFX1", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="RFX1", D=results$D)))
dev.off()

png(filename="output/RGM1.loc.png", width=300, height=300)
dat <- read.table(file="output/RGM1.loc", header=T)
results <- plot.hist.modular(dat, main="RGM1", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="RGM1", D=results$D)))
dev.off()

png(filename="output/RGT1.loc.png", width=300, height=300)
dat <- read.table(file="output/RGT1.loc", header=T)
results <- plot.hist.modular(dat, main="RGT1", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="RGT1", D=results$D)))
dev.off()

png(filename="output/RIM101.loc.png", width=300, height=300)
dat <- read.table(file="output/RIM101.loc", header=T)
results <- plot.hist.modular(dat, main="RIM101", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="RIM101", D=results$D)))
dev.off()

png(filename="output/RLM1.loc.png", width=300, height=300)
dat <- read.table(file="output/RLM1.loc", header=T)
results <- plot.hist.modular(dat, main="RLM1", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="RLM1", D=results$D)))
dev.off()

png(filename="output/RLR1.loc.png", width=300, height=300)
dat <- read.table(file="output/RLR1.loc", header=T)
results <- plot.hist.modular(dat, main="RLR1", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="RLR1", D=results$D)))
dev.off()

png(filename="output/RME1.loc.png", width=300, height=300)
dat <- read.table(file="output/RME1.loc", header=T)
results <- plot.hist.modular(dat, main="RME1", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="RME1", D=results$D)))
dev.off()

png(filename="output/ROX1.loc.png", width=300, height=300)
dat <- read.table(file="output/ROX1.loc", header=T)
results <- plot.hist.modular(dat, main="ROX1", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="ROX1", D=results$D)))
dev.off()

png(filename="output/RPH1.loc.png", width=300, height=300)
dat <- read.table(file="output/RPH1.loc", header=T)
results <- plot.hist.modular(dat, main="RPH1", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="RPH1", D=results$D)))
dev.off()

png(filename="output/RPN4.loc.png", width=300, height=300)
dat <- read.table(file="output/RPN4.loc", header=T)
results <- plot.hist.modular(dat, main="RPN4", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="RPN4", D=results$D)))
dev.off()

png(filename="output/RTG1.loc.png", width=300, height=300)
dat <- read.table(file="output/RTG1.loc", header=T)
results <- plot.hist.modular(dat, main="RTG1", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="RTG1", D=results$D)))
dev.off()

png(filename="output/RTG3.loc.png", width=300, height=300)
dat <- read.table(file="output/RTG3.loc", header=T)
results <- plot.hist.modular(dat, main="RTG3", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="RTG3", D=results$D)))
dev.off()

png(filename="output/SFP1.loc.png", width=300, height=300)
dat <- read.table(file="output/SFP1.loc", header=T)
results <- plot.hist.modular(dat, main="SFP1", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="SFP1", D=results$D)))
dev.off()

png(filename="output/SIP4.loc.png", width=300, height=300)
dat <- read.table(file="output/SIP4.loc", header=T)
results <- plot.hist.modular(dat, main="SIP4", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="SIP4", D=results$D)))
dev.off()

png(filename="output/SKN7.loc.png", width=300, height=300)
dat <- read.table(file="output/SKN7.loc", header=T)
results <- plot.hist.modular(dat, main="SKN7", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="SKN7", D=results$D)))
dev.off()

png(filename="output/SKO1.loc.png", width=300, height=300)
dat <- read.table(file="output/SKO1.loc", header=T)
results <- plot.hist.modular(dat, main="SKO1", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="SKO1", D=results$D)))
dev.off()

png(filename="output/SMK1.loc.png", width=300, height=300)
dat <- read.table(file="output/SMK1.loc", header=T)
results <- plot.hist.modular(dat, main="SMK1", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="SMK1", D=results$D)))
dev.off()

png(filename="output/SMP1.loc.png", width=300, height=300)
dat <- read.table(file="output/SMP1.loc", header=T)
results <- plot.hist.modular(dat, main="SMP1", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="SMP1", D=results$D)))
dev.off()

png(filename="output/SNF1.loc.png", width=300, height=300)
dat <- read.table(file="output/SNF1.loc", header=T)
results <- plot.hist.modular(dat, main="SNF1", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="SNF1", D=results$D)))
dev.off()

png(filename="output/SNT2.loc.png", width=300, height=300)
dat <- read.table(file="output/SNT2.loc", header=T)
results <- plot.hist.modular(dat, main="SNT2", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="SNT2", D=results$D)))
dev.off()

png(filename="output/SPT2.loc.png", width=300, height=300)
dat <- read.table(file="output/SPT2.loc", header=T)
results <- plot.hist.modular(dat, main="SPT2", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="SPT2", D=results$D)))
dev.off()

png(filename="output/SPT23.loc.png", width=300, height=300)
dat <- read.table(file="output/SPT23.loc", header=T)
results <- plot.hist.modular(dat, main="SPT23", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="SPT23", D=results$D)))
dev.off()

png(filename="output/SRD1.loc.png", width=300, height=300)
dat <- read.table(file="output/SRD1.loc", header=T)
results <- plot.hist.modular(dat, main="SRD1", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="SRD1", D=results$D)))
dev.off()

png(filename="output/STB1.loc.png", width=300, height=300)
dat <- read.table(file="output/STB1.loc", header=T)
results <- plot.hist.modular(dat, main="STB1", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="STB1", D=results$D)))
dev.off()

png(filename="output/STB2.loc.png", width=300, height=300)
dat <- read.table(file="output/STB2.loc", header=T)
results <- plot.hist.modular(dat, main="STB2", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="STB2", D=results$D)))
dev.off()

png(filename="output/STB4.loc.png", width=300, height=300)
dat <- read.table(file="output/STB4.loc", header=T)
results <- plot.hist.modular(dat, main="STB4", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="STB4", D=results$D)))
dev.off()

png(filename="output/STB5.loc.png", width=300, height=300)
dat <- read.table(file="output/STB5.loc", header=T)
results <- plot.hist.modular(dat, main="STB5", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="STB5", D=results$D)))
dev.off()

png(filename="output/STE12.loc.png", width=300, height=300)
dat <- read.table(file="output/STE12.loc", header=T)
results <- plot.hist.modular(dat, main="STE12", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="STE12", D=results$D)))
dev.off()

png(filename="output/STP1.loc.png", width=300, height=300)
dat <- read.table(file="output/STP1.loc", header=T)
results <- plot.hist.modular(dat, main="STP1", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="STP1", D=results$D)))
dev.off()

png(filename="output/STP2.loc.png", width=300, height=300)
dat <- read.table(file="output/STP2.loc", header=T)
results <- plot.hist.modular(dat, main="STP2", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="STP2", D=results$D)))
dev.off()

png(filename="output/STP4.loc.png", width=300, height=300)
dat <- read.table(file="output/STP4.loc", header=T)
results <- plot.hist.modular(dat, main="STP4", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="STP4", D=results$D)))
dev.off()

png(filename="output/SUM1.loc.png", width=300, height=300)
dat <- read.table(file="output/SUM1.loc", header=T)
results <- plot.hist.modular(dat, main="SUM1", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="SUM1", D=results$D)))
dev.off()

png(filename="output/SUT1.loc.png", width=300, height=300)
dat <- read.table(file="output/SUT1.loc", header=T)
results <- plot.hist.modular(dat, main="SUT1", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="SUT1", D=results$D)))
dev.off()

png(filename="output/SWI4.loc.png", width=300, height=300)
dat <- read.table(file="output/SWI4.loc", header=T)
results <- plot.hist.modular(dat, main="SWI4", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="SWI4", D=results$D)))
dev.off()

png(filename="output/SWI5.loc.png", width=300, height=300)
dat <- read.table(file="output/SWI5.loc", header=T)
results <- plot.hist.modular(dat, main="SWI5", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="SWI5", D=results$D)))
dev.off()

png(filename="output/SWI6.loc.png", width=300, height=300)
dat <- read.table(file="output/SWI6.loc", header=T)
results <- plot.hist.modular(dat, main="SWI6", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="SWI6", D=results$D)))
dev.off()

png(filename="output/TEC1.loc.png", width=300, height=300)
dat <- read.table(file="output/TEC1.loc", header=T)
results <- plot.hist.modular(dat, main="TEC1", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="TEC1", D=results$D)))
dev.off()

png(filename="output/THI2.loc.png", width=300, height=300)
dat <- read.table(file="output/THI2.loc", header=T)
results <- plot.hist.modular(dat, main="THI2", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="THI2", D=results$D)))
dev.off()

png(filename="output/TYE7.loc.png", width=300, height=300)
dat <- read.table(file="output/TYE7.loc", header=T)
results <- plot.hist.modular(dat, main="TYE7", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="TYE7", D=results$D)))
dev.off()

png(filename="output/UGA3.loc.png", width=300, height=300)
dat <- read.table(file="output/UGA3.loc", header=T)
results <- plot.hist.modular(dat, main="UGA3", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="UGA3", D=results$D)))
dev.off()

png(filename="output/UME1.loc.png", width=300, height=300)
dat <- read.table(file="output/UME1.loc", header=T)
results <- plot.hist.modular(dat, main="UME1", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="UME1", D=results$D)))
dev.off()

png(filename="output/UME6.loc.png", width=300, height=300)
dat <- read.table(file="output/UME6.loc", header=T)
results <- plot.hist.modular(dat, main="UME6", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="UME6", D=results$D)))
dev.off()

png(filename="output/UPC2.loc.png", width=300, height=300)
dat <- read.table(file="output/UPC2.loc", header=T)
results <- plot.hist.modular(dat, main="UPC2", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="UPC2", D=results$D)))
dev.off()

png(filename="output/USV1.loc.png", width=300, height=300)
dat <- read.table(file="output/USV1.loc", header=T)
results <- plot.hist.modular(dat, main="USV1", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="USV1", D=results$D)))
dev.off()

png(filename="output/WAR1.loc.png", width=300, height=300)
dat <- read.table(file="output/WAR1.loc", header=T)
results <- plot.hist.modular(dat, main="WAR1", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="WAR1", D=results$D)))
dev.off()

png(filename="output/WTM1.loc.png", width=300, height=300)
dat <- read.table(file="output/WTM1.loc", header=T)
results <- plot.hist.modular(dat, main="WTM1", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="WTM1", D=results$D)))
dev.off()

png(filename="output/YAP1.loc.png", width=300, height=300)
dat <- read.table(file="output/YAP1.loc", header=T)
results <- plot.hist.modular(dat, main="YAP1", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="YAP1", D=results$D)))
dev.off()

png(filename="output/YAP3.loc.png", width=300, height=300)
dat <- read.table(file="output/YAP3.loc", header=T)
results <- plot.hist.modular(dat, main="YAP3", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="YAP3", D=results$D)))
dev.off()

png(filename="output/YAP5.loc.png", width=300, height=300)
dat <- read.table(file="output/YAP5.loc", header=T)
results <- plot.hist.modular(dat, main="YAP5", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="YAP5", D=results$D)))
dev.off()

png(filename="output/YAP6.loc.png", width=300, height=300)
dat <- read.table(file="output/YAP6.loc", header=T)
results <- plot.hist.modular(dat, main="YAP6", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="YAP6", D=results$D)))
dev.off()

png(filename="output/YBL054W.loc.png", width=300, height=300)
dat <- read.table(file="output/YBL054W.loc", header=T)
results <- plot.hist.modular(dat, main="YBL054W", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="YBL054W", D=results$D)))
dev.off()

png(filename="output/YDR026c.loc.png", width=300, height=300)
dat <- read.table(file="output/YDR026c.loc", header=T)
results <- plot.hist.modular(dat, main="YDR026c", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="YDR026c", D=results$D)))
dev.off()

png(filename="output/YDR049W.loc.png", width=300, height=300)
dat <- read.table(file="output/YDR049W.loc", header=T)
results <- plot.hist.modular(dat, main="YDR049W", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="YDR049W", D=results$D)))
dev.off()

png(filename="output/YDR266c.loc.png", width=300, height=300)
dat <- read.table(file="output/YDR266c.loc", header=T)
results <- plot.hist.modular(dat, main="YDR266c", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="YDR266c", D=results$D)))
dev.off()

png(filename="output/YDR520C.loc.png", width=300, height=300)
dat <- read.table(file="output/YDR520C.loc", header=T)
results <- plot.hist.modular(dat, main="YDR520C", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="YDR520C", D=results$D)))
dev.off()

png(filename="output/YER051w.loc.png", width=300, height=300)
dat <- read.table(file="output/YER051w.loc", header=T)
results <- plot.hist.modular(dat, main="YER051w", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="YER051w", D=results$D)))
dev.off()

png(filename="output/YER130C.loc.png", width=300, height=300)
dat <- read.table(file="output/YER130C.loc", header=T)
results <- plot.hist.modular(dat, main="YER130C", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="YER130C", D=results$D)))
dev.off()

png(filename="output/YER184C.loc.png", width=300, height=300)
dat <- read.table(file="output/YER184C.loc", header=T)
results <- plot.hist.modular(dat, main="YER184C", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="YER184C", D=results$D)))
dev.off()

png(filename="output/YFL044C.loc.png", width=300, height=300)
dat <- read.table(file="output/YFL044C.loc", header=T)
results <- plot.hist.modular(dat, main="YFL044C", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="YFL044C", D=results$D)))
dev.off()

png(filename="output/YHP1.loc.png", width=300, height=300)
dat <- read.table(file="output/YHP1.loc", header=T)
results <- plot.hist.modular(dat, main="YHP1", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="YHP1", D=results$D)))
dev.off()

png(filename="output/YJL206C.loc.png", width=300, height=300)
dat <- read.table(file="output/YJL206C.loc", header=T)
results <- plot.hist.modular(dat, main="YJL206C", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="YJL206C", D=results$D)))
dev.off()

png(filename="output/YKR064W.loc.png", width=300, height=300)
dat <- read.table(file="output/YKR064W.loc", header=T)
results <- plot.hist.modular(dat, main="YKR064W", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="YKR064W", D=results$D)))
dev.off()

png(filename="output/YML081W.loc.png", width=300, height=300)
dat <- read.table(file="output/YML081W.loc", header=T)
results <- plot.hist.modular(dat, main="YML081W", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="YML081W", D=results$D)))
dev.off()

png(filename="output/YOX1.loc.png", width=300, height=300)
dat <- read.table(file="output/YOX1.loc", header=T)
results <- plot.hist.modular(dat, main="YOX1", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="YOX1", D=results$D)))
dev.off()

png(filename="output/YPR196W.loc.png", width=300, height=300)
dat <- read.table(file="output/YPR196W.loc", header=T)
results <- plot.hist.modular(dat, main="YPR196W", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="YPR196W", D=results$D)))
dev.off()

png(filename="output/YRR1.loc.png", width=300, height=300)
dat <- read.table(file="output/YRR1.loc", header=T)
results <- plot.hist.modular(dat, main="YRR1", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="YRR1", D=results$D)))
dev.off()

png(filename="output/ZAP1.loc.png", width=300, height=300)
dat <- read.table(file="output/ZAP1.loc", header=T)
results <- plot.hist.modular(dat, main="ZAP1", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="ZAP1", D=results$D)))
dev.off()

png(filename="output/ZMS1.loc.png", width=300, height=300)
dat <- read.table(file="output/ZMS1.loc", header=T)
results <- plot.hist.modular(dat, main="ZMS1", ylim=c(0,30), bkgd.max=bkgd.max, all.results=all.results)
D.list <- c(D.list, list(list(cat="ZMS1", D=results$D)))
dev.off()

png(filename="Harbison2004_9.2_forpaper_YPD.1e-3.ORFlists.pvplot.png", width=400, height=250)
plot.pvalues("Harbison2004_9.2_forpaper_YPD.1e-3.ORFlists.ks-pvalues.tab", D.list, all.results)
dev.off()
