package org.cytoscape.webservice.psicquic;

import static cytoscape.data.webservice.CyWebServiceEvent.WSResponseType.SEARCH_FINISHED;

import java.net.URI;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.regex.Pattern;

import javax.swing.JPanel;

import org.cytoscape.webservice.psicquic.mapper.Mitab25Mapper;
import org.cytoscape.webservice.psicquic.ui.ResultDialog;
import org.hupo.psi.mi.psicquic.DbRef;
import org.hupo.psi.mi.psicquic.QueryResponse;
import org.hupo.psi.mi.psicquic.RequestInfo;

import cytoscape.CyNetwork;
import cytoscape.Cytoscape;
import cytoscape.data.webservice.CyWebServiceEvent;
import cytoscape.data.webservice.CyWebServiceException;
import cytoscape.data.webservice.DatabaseSearchResult;
import cytoscape.data.webservice.NetworkImportWebServiceClient;
import cytoscape.data.webservice.WebServiceClient;
import cytoscape.data.webservice.WebServiceClientImplWithGUI;
import cytoscape.data.webservice.CyWebServiceEvent.WSEventType;
import cytoscape.data.webservice.WebServiceClientManager.ClientType;
import cytoscape.layout.Tunable;
import cytoscape.logger.CyLogger;
import cytoscape.util.ModulePropertiesImpl;
import cytoscape.visual.VisualStyle;

public class PSICQUICUniversalClient extends
		WebServiceClientImplWithGUI<PSICQUICServiceRegistory, JPanel> implements
		NetworkImportWebServiceClient {

	private static final long serialVersionUID = 4485772700287524894L;

	private static final String[] IMPORT_MODE = { "Detection Method",
			"Interaction ID" };
	private static final String[] IMPORT_DATA_FORMAT = { "MITAB25",
			"PSI-MI XML 2.5" };
	private static final String[] SEARCH_MODE = { "Interactor ID(s)", "Query",
			"Interaction ID(s)", "Pipeline" };

	private enum Mode {
		SEARCH, IMPORT;
	}
	
	private enum QueryMode {
		GET_BY_INTERACTOR, GET_BY_QUERY;
	}

	private void setDescription() {
		description = "http://code.google.com/p/psicquic/";
	}
	
	private QueryMode qMode = QueryMode.GET_BY_INTERACTOR;

	private void setProperty() {
		props = new ModulePropertiesImpl(clientID, "wsc");

		// General setting
		props.add(new Tunable("block_size", "Block Size", Tunable.INTEGER,
				new Integer(100)));
		props.add(new Tunable("timeout", "Timeout (sec.)", Tunable.INTEGER,
				new Integer(6000)));
		props.add(new Tunable("active_only", "Active Services Only", Tunable.BOOLEAN,
				new Boolean(true)));
		
		final String[] modeArray = {QueryMode.GET_BY_INTERACTOR.name(), QueryMode.GET_BY_QUERY.toString()};
		props.add(new Tunable("query_mode", "Query Mode",
                Tunable.LIST, new Integer(0), 
                (Object) modeArray, (Object) null, 0));

	}

	// private static final Icon ABOUT_ICON = new ImageIcon(
	// PSICQUICUniversalClient.class.getResource("/images/psi.gif"));

	// Display name of this client.
	private static final String DISPLAY_NAME = "PSICQUIC Universal Web Service Client";

	// Client ID. This should be unique.
	private static final String CLIENT_ID = "psicquic";

	// // Instance of this client. This is a singleton.
	private static WebServiceClient<PSICQUICServiceRegistory> client;

	// Visual Style name for the networks generated by this client.
	private static final String DEF_VS_NAME = "PSI-MI 25 Style";
	private VisualStyle defaultVS = null;

	private Map<URI, QueryResponse> sResult;
	private List<DbRef> queryList;
	private String query;
	
	static {
		 try {
			client = new PSICQUICUniversalClient();
		} catch (Exception e) {
			CyLogger.getLogger().error("Could not initialize PSICQUIC Client.", e);
		}
	}

	private PSICQUICUniversalClient() throws Exception {
		super(CLIENT_ID, DISPLAY_NAME, new ClientType[] { ClientType.NETWORK },
				null, new PSICQUICServiceRegistory(), null);

		setDescription();
		// Set properties for this client.
		setProperty();
	}

	public static WebServiceClient<PSICQUICServiceRegistory> getClient() {
		return client;
	}

	public VisualStyle getDefaultVisualStyle() {
		return PSI25VisualStyleBuilder.getDefVS();
	}

	@Override
	public void executeService(CyWebServiceEvent e)
			throws CyWebServiceException {

		if (e.getSource().equals(CLIENT_ID)) {
			if (e.getEventType().equals(WSEventType.IMPORT_NETWORK)) {
				importNetwork(e.getParameter(), null);
			} else if (e.getEventType().equals(WSEventType.EXPAND_NETWORK)) {
				importNetwork(e.getParameter(), Cytoscape.getCurrentNetwork());
			} else if (e.getEventType().equals(WSEventType.SEARCH_DATABASE)) {
				search(e.getParameter().toString(), e);
			}
		}

	}

	
	
	private void search(String queryString, CyWebServiceEvent<?> e)
			throws CyWebServiceException {

		final PSICQUICServiceRegistory searchClient = ((PSICQUICServiceRegistory) clientStub);
		sResult = null;
		int blockSize = 100;
		try{
			blockSize = Integer.parseInt(props.getValue("block_size"));
		} catch( Exception exp ) {
			blockSize = 100;
		}
		
		this.query = queryString;
		final RequestInfo info = new RequestInfo();
		info.setResultType(PSICQUICReturnType.COUNT.getTypeName());
		info.setBlockSize(blockSize);
		try {
			System.out.println("** Submit Search Query: " + query);
			
			Tunable mode = props.get("query_mode");
			System.out.println("QueryMode ====> " + mode.getValue());
			
			
			if(mode.getValue().equals(QueryMode.GET_BY_INTERACTOR.ordinal())) {
				System.out.println("QueryMode ====> " + mode.getValue());
				queryList = buildInteractorList(query);
				sResult = searchClient.getCount(queryList, info, "OR");
			} else {
				// Get by Query (MIQL)
				sResult = searchClient.getCount(query, info);
			}
			
			
		} catch (Exception ex) {
			ex.printStackTrace();
			throw new CyWebServiceException(
					CyWebServiceException.WSErrorCode.REMOTE_EXEC_FAILED);
		}

		if (sResult == null)
			return;

		WSEventType nextMove = e.getNextMove();
		if (nextMove == null)
			nextMove = WSEventType.IMPORT_NETWORK;

		Integer total = 0;
		for (URI key : sResult.keySet())
			total = total + sResult.get(key).getResultInfo().getTotalResults();

		Cytoscape.firePropertyChange(SEARCH_FINISHED.toString(), this.clientID,
				new DatabaseSearchResult<Map<URI, QueryResponse>>(total,
						sResult, nextMove));

	}
	
	private void importNetwork(Object result, CyNetwork e)
			throws CyWebServiceException {
		
		PSICQUICServiceRegistory importClient = ((PSICQUICServiceRegistory) clientStub);
		Map<URI, List<QueryResponse>> importResult = null;
		final RequestInfo info = new RequestInfo();

		info.setResultType(PSICQUICReturnType.MITAB25.getTypeName());
		info.setBlockSize(100);
		try {
			if(queryList != null) {
				System.out.println("========Get by List");
				importResult = importClient.getByInteractorList(queryList, info, "OR");
			} else {
				System.out.println("========Get by Query");
				importResult = importClient.getByQuery(query, info);
			}
		} catch (Exception ex) {
			ex.printStackTrace();
			throw new CyWebServiceException(
					CyWebServiceException.WSErrorCode.REMOTE_EXEC_FAILED);
		}

		if (importResult == null)
			return;
		
		// Ask user to display names
		final List<String> defNetworkNames = new ArrayList<String>();
		final Date time = new Date(System.currentTimeMillis());
		final Map<URI, String> nameMap = importClient.getServiceNames();
		Map<URI, String> newNameMap = new HashMap<URI, String>();
		String netName = null;
		for(URI name: importResult.keySet()) {
			netName = nameMap.get(name);
			defNetworkNames.add(netName);
			newNameMap.put(name, netName);
		}
		
		ResultDialog report = new ResultDialog(Cytoscape.getDesktop(), true, newNameMap);
		report.setLocationRelativeTo(Cytoscape.getDesktop());
		report.setVisible(true);

		newNameMap = report.getNewNames();
		
		final Mitab25Mapper mapper = new Mitab25Mapper();
		List<CyNetwork> target = new ArrayList<CyNetwork>();
		
		// Create parent empty network
		final String parentName;
		if(query != null) {
			parentName = "PSICQUIC Query Result: " + time.toString() + " (" + query +")";
		} else {
			parentName = "PSICQUIC Query Result: " + time.toString();
		}
		final CyNetwork parentNetwork = Cytoscape.createNetwork(parentName, false);
		
		for (URI key : importResult.keySet()) {

			System.out.println("========Import Finished2!!!!!!!!!!!!!!!!!!!\n"
					+ importResult.get(key).size());
			
			StringBuilder builder = new StringBuilder();
			List<QueryResponse> res = importResult.get(key);
			for(QueryResponse qr: res) {
				builder.append(qr.getResultSet().getMitab());
			}
			final CyNetwork net = mapper.map(builder.toString(), newNameMap.get(key), parentNetwork); 
			if(net != null)
				target.add(net);
		}
		if (Cytoscape.getVisualMappingManager().getCalculatorCatalog()
				.getVisualStyle(PSI25VisualStyleBuilder.getDefVS().getName()) == null)
			Cytoscape.getVisualMappingManager().getCalculatorCatalog()
					.addVisualStyle(PSI25VisualStyleBuilder.getDefVS());
		
		for(CyNetwork net: target) {
			Cytoscape.getVisualMappingManager().setVisualStyle(
					PSI25VisualStyleBuilder.getDefVS());
			Cytoscape.getNetworkView(net.getIdentifier()).setVisualStyle(PSI25VisualStyleBuilder.getDefVS().getName());
			Cytoscape.getNetworkView(net.getIdentifier()).redrawGraph(true, false);
		}
		
		query = null;
		queryList = null;
	}

	// Build interactor list
	private List<DbRef> buildInteractorList(String query) {
		List<DbRef> interactorList = new ArrayList<DbRef>();

		Pattern pattern2 = Pattern.compile(" +|\n|\t+");
		String[] interactorNames = pattern2.split(query);

		for (String name : interactorNames) {
			System.out.println("==> " + name);
			final DbRef dbRef = new DbRef();
			dbRef.setId(name);
			interactorList.add(dbRef);
		}
		return interactorList;
	}

}
