#!/usr/bin/env python
import exceptions
import getopt
import glob
import os
import re
import sys
import xml.etree.ElementTree


verbose = False
loop_count = 20
temp_pom_name = "temp_pom.xml"


def PrintUsage():
    print "usage: ctrt [--verbose] maven_project_directory"
    exit(-1)


# Returns a list of triples (groupId,artifactId,version) upon success or None upon failure.
def ReadBaselineFile(maven_project_directory):
    try:
        file = open(maven_project_directory + "/baseline.xml", "r")
        tree = xml.etree.ElementTree.parse(file)
        root = tree.getroot()
        replacements = []
        for replace in root.getiterator("replace"):
            groupId = replace.find("groupId")
            if groupId == None:
                return None
            artifactId = replace.find("artifactId")
            if artifactId == None:
                return artifactId
            version = replace.find("version")
            if version == None:
                return None
            replacements.append((groupId.text,artifactId.text,version.text))
        return replacements
    except:
        return None


def RunMavenTest(pom_file_name):
    command = "mvn --quiet --file " + pom_file_name + " clean test"
    if verbose:
        print "ctrt: Info: About to run \"" + command + "\"."
    if os.system(command) != 0:
    	return False
    return True


# Returns a dictonary upon success or None upon failure.  The dictionary has the test names as the
# keys and the test execution times (in seconds) as the values.
def ExtractTimingInfoFromSurefireReports(maven_project_directory):
    dict = {}
    for file in glob.glob(maven_project_directory + "/target/surefire-reports/*.xml"):
        tree = xml.etree.ElementTree.parse(file)
        root = tree.getroot()
        for testcase in root.getiterator("testcase"):
            time = testcase.get("time")
            classname = testcase.get("classname")
            name = testcase.get("name")
            dict[classname + "." + name] = float(time)
            if verbose:
                print "ctrt: Info: test " + classname + "." + name + " took " + time + "sec"
    return dict


# Returns None if no match was found or the replacement (groupId,artifactId,version) if a match was found
def foundGroupAndArtifactIdMatch(dependency, groupId_artifactId_version_list):
    groupId = dependency.find("{http://maven.apache.org/POM/4.0.0}groupId")
    if groupId == None:
        return None
    artifactId = dependency.find("{http://maven.apache.org/POM/4.0.0}artifactId")
    if artifactId == None:
        return None
    for groupId_artifactId_version in groupId_artifactId_version_list:
        if groupId.text != groupId_artifactId_version[0] or artifactId.text != groupId_artifactId_version[1]:
            continue
        return groupId_artifactId_version
    return None


def SwapBundleVersionNumbers(maven_project_directory, groupId_artifactId_version_list):
    effective_pom_file_name = maven_project_directory + "/effective.pom"
    os.system("mvn --quiet help:effective-pom -Doutput='" + effective_pom_file_name + "'")
    tree = xml.etree.ElementTree.parse(effective_pom_file_name)
    os.remove(effective_pom_file_name)
    root = tree.getroot()
    dependencies = root.find("{http://maven.apache.org/POM/4.0.0}dependencies")
    expected_replacement_count = len(groupId_artifactId_version_list)
    actual_replacement_count = 0
    for dependency in dependencies.getiterator("{http://maven.apache.org/POM/4.0.0}dependency"):
        replacement_groupId_artifactId_version = \
            foundGroupAndArtifactIdMatch(dependency, groupId_artifactId_version_list)
        if replacement_groupId_artifactId_version == None:
            continue
        version = dependency.find("{http://maven.apache.org/POM/4.0.0}version")
        if version == None:
            print "ctrt: Error: \"version\" tag missing for " + replacement_groupId_artifactId_version[1] \
                + ":" + replacement_groupId_artifactId_version[1] + "!"
            return False
        if verbose:
            print "About to replace " + version.text + " with " + replacement_groupId_artifactId_version[2] + \
                " for " + replacement_groupId_artifactId_version[0] + ":" + replacement_groupId_artifactId_version[1]
        version.text = replacement_groupId_artifactId_version[2]
        ++actual_replacement_count

    if actual_replacement_count == actual_replacement_count:
        file = open(maven_project_directory + "/" + temp_pom_name, "w+")
        xml.etree.ElementTree._namespace_map["http://maven.apache.org/POM/4.0.0"] = "XYZ_ABC"
        xml.etree.ElementTree._namespace_map["http://www.w3.org/2001/XMLSchema-instance"] = "xsi"
        tree.write(file, encoding="UTF-8")
        file.seek(0)
        temp_pom = file.read()
        temp_pom = re.sub("XYZ_ABC:", "", temp_pom)
        temp_pom = re.sub(":XYZ_ABC", "", temp_pom, 1)
        file.truncate(0)
        file.seek(0)
        file.write(temp_pom)
        return True
    print "ctrt: Error: Not all version number replacements could be carried out!"
    return False


def GenerateTimingReport(current_version, baseline_version):
    max_deviation = 10.0 # in percent
    print "---------------------------------------- Timing Comparison --------------------------------------------"
    failure_count = 0
    for key in baseline_version.keys():
        baseline_time = baseline_version[key]
        current_time  = current_version[key]
        if baseline_time == 0.0:
            percent_deviation = current_time * 100.0
        else:
            percent_deviation = 100.0 * (current_time - baseline_time) / baseline_time
        print str("Test " + key + " ran %.5f" + "%% slower than the baseline.") % percent_deviation
    if failure_count > 0:
        print str(failure_count) + " failed because current tests were running too slow!"
        exit(1)
    print "-------------------------------------------------------------------------------------------------------"
    return


def PrintUsage():
    print "usage: ctrt [--verbose|-v] [[--loop-count=|-l] loop_count] maven_project_directory"
    print "       (Default for loop count is 20.)"
    exit(1)


# Returns the Maven project directory upon success and does not return upon failure.
# Also updates global variables "verbose" and "loop_count".
def ProcessArgs():
    try:
        opts, args = getopt.getopt(sys.argv[1:], "hvl:", ["help", "verbose", "loop-count="])
    except getopt.GetoptError, err:
        print str(err)
        exit(2)
    for opt, arg in opts:
        if opt in ("-v", "--verbose"):
            verbose = True
        elif opt in ("-h", "--help"):
            PrintUsage()
        elif opt in ("-l", "--loop-count"):
            try:
                loop_count = int(arg)
            except exceptions.ValueError:
                print "ctrt: " + arg + " is not a valid loop count!"
                PrintUsage()
        else:
            assert False, "unhandled option"
    if len(args) != 1:
        PrintUsage()
    return args[0]


def main():
    maven_project_directory = ProcessArgs()

    if verbose:
        print "ctrt: About to parse baseline version file."
    groupId_artifactId_version_list = ReadBaselineFile(maven_project_directory)
    if groupId_artifactId_version_list == None:
        print "ctrt: Failed to read baseline version from file!"
        exit(-2)

    if verbose:
        print "ctrt: About to run Maven with the current version."
    if not RunMavenTest("pom.xml"):
        print "ctrt: Failed to run Maven with the current version!"
        exit(-3)

    timing_current_version = ExtractTimingInfoFromSurefireReports(maven_project_directory)

    if not SwapBundleVersionNumbers(maven_project_directory, groupId_artifactId_version_list):
        print "ctrt: Failed to replace the current version with the baseline version!"
        exit(-4)

    if verbose:
        print "ctrt: About to run Maven with the baseline version."
    if not RunMavenTest(temp_pom_name):
        print "ctrt: Failed to run Maven with the baseline version!"
        exit(-6)

    if verbose:
        print "ctrt: About to delete temporary POM."
    os.remove(maven_project_directory + "/" + temp_pom_name)

    timing_baseline_version = ExtractTimingInfoFromSurefireReports(maven_project_directory)

    GenerateTimingReport(timing_current_version, timing_baseline_version)


main()
