package edu.ucsd.bioeng.idekerlab.PathwayWalkingPlugin;

import giny.model.Node;
/*
 * GUI.java
 *
 * Created on February 4, 2008, 11:38 AM
 */
 
/**
 *
 * @author  Administrator
 */
import cytoscape.Cytoscape;
import cytoscape.data.CyAttributes;

public class GUI extends javax.swing.JFrame {
 
    /** Creates new form GUI */
    public GUI(Node nd) {
    	node = nd;
    	cyAtts = Cytoscape.getNodeAttributes();
    	nodeId = node.getIdentifier();
        initComponents();
    }
 
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">
    private void initComponents() {
        titleText = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nodeIDText = new javax.swing.JLabel();
        databaseNameText = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        jProgressBar2 = new javax.swing.JProgressBar();
        jProgressBar3 = new javax.swing.JProgressBar();
        jProgressBar4 = new javax.swing.JProgressBar();
        jProgressBar5 = new javax.swing.JProgressBar();
        jProgressBar6 = new javax.swing.JProgressBar();
        jLabel10 = new javax.swing.JLabel();
        jProgressBar7 = new javax.swing.JProgressBar();
 
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        titleText.setFont(new java.awt.Font("Tahoma", 1, 18));
        titleText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleText.setText("Pathway Walking Plugin");
 
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel2.setText("Current Node ID:");
 
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel3.setText("Database Name:");
 
        nodeIDText.setText(nodeId);
 
        databaseNameText.setText("default");
 
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel1.setText("Available Databases");
 
        jCheckBox1.setText("IntAct");
        jCheckBox1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jCheckBox1.setMargin(new java.awt.Insets(0, 0, 0, 0));
 
        jCheckBox2.setText("MINT");
        jCheckBox2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jCheckBox2.setMargin(new java.awt.Insets(0, 0, 0, 0));
 
        jCheckBox3.setText("HPRD");
        jCheckBox3.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jCheckBox3.setMargin(new java.awt.Insets(0, 0, 0, 0));
 
        jCheckBox4.setText("BioCyc");
        jCheckBox4.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jCheckBox4.setMargin(new java.awt.Insets(0, 0, 0, 0));
 
        jCheckBox5.setText("PUMA2");
        jCheckBox5.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jCheckBox5.setMargin(new java.awt.Insets(0, 0, 0, 0));
 
        jCheckBox6.setText("Reactome");
        jCheckBox6.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jCheckBox6.setMargin(new java.awt.Insets(0, 0, 0, 0));
 
        jCheckBox7.setText("KEGG");
        jCheckBox7.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jCheckBox7.setMargin(new java.awt.Insets(0, 0, 0, 0));
 
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel4.setText("Progress");
 
        jLabel6.setText("0");
 
        jLabel7.setText("0");
 
        jLabel8.setText("0");
 
        jLabel9.setText("0");
 
        jLabel11.setText("0");
 
        jLabel12.setText("0");
 
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel5.setText("Nodes");
        
        jList1.setListData(cyAtts.getAttributeNames()) ;
 
        jScrollPane1.setViewportView(jList1);
 
        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel13.setText("Results:");
 
        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel14.setText("Name");
 
        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel15.setText("Database");
 
        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel16.setText("Name");
 
        jButton1.setText("Start Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
 
        jButton2.setText("Add to Existing Network");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
 
        jButton3.setText("Advanced");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
 
        jLabel10.setText("0");
 
        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                        .addContainerGap())
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel1)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                    .add(layout.createSequentialGroup()
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(jLabel2)
                                            .add(jLabel3))
                                        .add(14, 14, 14)
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                            .add(org.jdesktop.layout.GroupLayout.LEADING, databaseNameText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 172, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(org.jdesktop.layout.GroupLayout.LEADING, nodeIDText, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE))
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED))
                                    .add(layout.createSequentialGroup()
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(jCheckBox2)
                                            .add(jCheckBox1)
                                            .add(jCheckBox3)
                                            .add(jCheckBox4)
                                            .add(jCheckBox5)
                                            .add(jCheckBox7))
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 132, Short.MAX_VALUE)
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(jProgressBar5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(jProgressBar4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(jLabel4)
                                            .add(jProgressBar1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(jProgressBar3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(jProgressBar2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(jProgressBar6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(jProgressBar7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                        .add(19, 19, 19)))
                                .add(28, 28, 28)))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel6)
                                    .add(jLabel7)
                                    .add(jLabel8)
                                    .add(jLabel11)
                                    .add(jLabel9)
                                    .add(jLabel12)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel10))
                                .add(19, 19, 19))
                            .add(layout.createSequentialGroup()
                                .add(jLabel5)
                                .addContainerGap())))
                    .add(layout.createSequentialGroup()
                        .add(39, 39, 39)
                        .add(titleText, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                        .addContainerGap())
                    .add(layout.createSequentialGroup()
                        .add(jCheckBox6)
                        .addContainerGap(312, Short.MAX_VALUE))
                    .add(layout.createSequentialGroup()
                        .add(jLabel13)
                        .addContainerGap(328, Short.MAX_VALUE))
                    .add(layout.createSequentialGroup()
                        .add(jLabel14)
                        .add(75, 75, 75)
                        .add(jLabel15)
                        .add(70, 70, 70)
                        .add(jLabel16)
                        .add(97, 97, 97))
                    .add(layout.createSequentialGroup()
                        .add(jButton1)
                        .add(21, 21, 21)
                        .add(jButton2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 25, Short.MAX_VALUE)
                        .add(jButton3)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(titleText)
                .add(30, 30, 30)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(nodeIDText))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(databaseNameText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(19, 19, 19)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(jLabel5)
                    .add(jLabel4))
                .add(17, 17, 17)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jCheckBox1)
                    .add(jLabel6)
                    .add(jProgressBar1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(12, 12, 12)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jCheckBox2)
                    .add(jLabel7)
                    .add(jProgressBar2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(14, 14, 14)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jCheckBox3)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                        .add(jProgressBar3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jLabel8)))
                .add(16, 16, 16)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel9)
                    .add(jCheckBox4)
                    .add(jProgressBar4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(16, 16, 16)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel11)
                            .add(jCheckBox5))
                        .add(15, 15, 15)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(layout.createSequentialGroup()
                                .add(jCheckBox6)
                                .add(3, 3, 3))
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                    .add(jProgressBar6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jLabel12))
                                .add(4, 4, 4))))
                    .add(jProgressBar5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(13, 13, 13)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jCheckBox7)
                            .add(jLabel10))
                        .add(17, 17, 17)
                        .add(jLabel13))
                    .add(layout.createSequentialGroup()
                        .add(10, 10, 10)
                        .add(jProgressBar7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel14)
                    .add(jLabel15)
                    .add(jLabel16))
                .add(3, 3, 3)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 154, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton1)
                    .add(jButton3)
                    .add(jButton2))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        pack();
    }// </editor-fold>
 
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
// TODO add your handling code here:
        System.out.println("Advanced");
        AdvancedGUI advG = new AdvancedGUI();
        advG.openGUI();
    }
 
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
// TODO add your handling code here:
        System.out.println("Start Search Button Pressed");
    }
 
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        System.out.println("Add to existing network");
    }
 
    /**
     * @param args the command line arguments
     */
    public void loadGui(Node nd) {
    	final Node node = nd;
        java.awt.EventQueue.invokeLater(new Runnable() {
        	public void run() {
                new GUI(node).setVisible(true);
            }
        });
    }
 
    // Variables declaration - do not modify
    private javax.swing.JLabel databaseNameText;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JProgressBar jProgressBar3;
    private javax.swing.JProgressBar jProgressBar4;
    private javax.swing.JProgressBar jProgressBar5;
    private javax.swing.JProgressBar jProgressBar6;
    private javax.swing.JProgressBar jProgressBar7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nodeIDText;
    private javax.swing.JLabel titleText;
    private String nodeId;
    private Node node;
    private CyAttributes cyAtts;
    // End of variables declaration
 
}


//import giny.model.Node;
///*
// * GUI.java
// *
// * Created on February 4, 2008, 11:38 AM
// */
// 
///**
// *
// * @author  Administrator
// */
//import cytoscape.Cytoscape;
//import cytoscape.data.CyAttributes;
//
//public class GUI extends javax.swing.JFrame {
//   
//    /** Creates new form GUI */
//    public GUI(Node nd) {
//    	node = nd;
//    	cyAtts = Cytoscape.getNodeAttributes();
//    	nodeId = node.getIdentifier();
//        initComponents();
//    }
//   
//    /** This method is called from within the constructor to
//     * initialize the form.
//     * WARNING: Do NOT modify this code. The content of this method is
//     * always regenerated by the Form Editor.
//     */
//    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">                         
//    private void initComponents() {
//        titleText = new javax.swing.JLabel();
//        jLabel2 = new javax.swing.JLabel();
//        jLabel3 = new javax.swing.JLabel();
//        nodeIDText = new javax.swing.JLabel();
//        databaseNameText = new javax.swing.JLabel();
//        jLabel1 = new javax.swing.JLabel();
//        jCheckBox1 = new javax.swing.JCheckBox();
//        jCheckBox2 = new javax.swing.JCheckBox();
//        jCheckBox3 = new javax.swing.JCheckBox();
//        jCheckBox4 = new javax.swing.JCheckBox();
//        jCheckBox5 = new javax.swing.JCheckBox();
//        jCheckBox6 = new javax.swing.JCheckBox();
//        jCheckBox7 = new javax.swing.JCheckBox();
//        IntActProgress = new javax.swing.JProgressBar();
//        MINTProgress = new javax.swing.JProgressBar();
//        HPRDProgress = new javax.swing.JProgressBar();
//        BioCycProgress = new javax.swing.JProgressBar();
//        PUMA2Progress = new javax.swing.JProgressBar();
//        ReactomeProgress = new javax.swing.JProgressBar();
//        KEGGProgress = new javax.swing.JProgressBar();
//        jLabel4 = new javax.swing.JLabel();
//        jLabel6 = new javax.swing.JLabel();
//        jLabel7 = new javax.swing.JLabel();
//        jLabel8 = new javax.swing.JLabel();
//        jLabel9 = new javax.swing.JLabel();
//        jLabel10 = new javax.swing.JLabel();
//        jLabel11 = new javax.swing.JLabel();
//        jLabel12 = new javax.swing.JLabel();
//        jLabel5 = new javax.swing.JLabel();
//        jScrollPane1 = new javax.swing.JScrollPane();
//        jList1 = new javax.swing.JList();
//        jLabel13 = new javax.swing.JLabel();
//        jLabel14 = new javax.swing.JLabel();
//        jLabel15 = new javax.swing.JLabel();
//        jLabel16 = new javax.swing.JLabel();
//        jButton1 = new javax.swing.JButton();
//        jButton2 = new javax.swing.JButton();
//        jButton3 = new javax.swing.JButton();
// 
//        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
//        titleText.setFont(new java.awt.Font("Tahoma", 1, 18));
//        titleText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
//        titleText.setText("Pathway Walking Plugin");
// 
//        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12));
//        jLabel2.setText("Current Node ID:");
// 
//        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12));
//        jLabel3.setText("Database Name:");
// 
//        nodeIDText.setText(nodeId);
// 
//        databaseNameText.setText("default");
// 
//        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12));
//        jLabel1.setText("Available Databases");
// 
//        jCheckBox1.setText("IntAct");
//        jCheckBox1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
//        jCheckBox1.setMargin(new java.awt.Insets(0, 0, 0, 0));
// 
//        jCheckBox2.setText("MINT");
//        jCheckBox2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
//        jCheckBox2.setMargin(new java.awt.Insets(0, 0, 0, 0));
// 
//        jCheckBox3.setText("HPRD");
//        jCheckBox3.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
//        jCheckBox3.setMargin(new java.awt.Insets(0, 0, 0, 0));
// 
//        jCheckBox4.setText("BioCyc");
//        jCheckBox4.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
//        jCheckBox4.setMargin(new java.awt.Insets(0, 0, 0, 0));
// 
//        jCheckBox5.setText("PUMA2");
//        jCheckBox5.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
//        jCheckBox5.setMargin(new java.awt.Insets(0, 0, 0, 0));
// 
//        jCheckBox6.setText("Reactome");
//        jCheckBox6.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
//        jCheckBox6.setMargin(new java.awt.Insets(0, 0, 0, 0));
// 
//        jCheckBox7.setText("KEGG");
//        jCheckBox7.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
//        jCheckBox7.setMargin(new java.awt.Insets(0, 0, 0, 0));
// 
//        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12));
//        jLabel4.setText("Progress");
// 
//        jLabel6.setText("0");
// 
//        jLabel7.setText("0");
// 
//        jLabel8.setText("0");
// 
//        jLabel9.setText("0");
// 
//        jLabel10.setText("0");
// 
//        jLabel11.setText("0");
// 
//        jLabel12.setText("0");
// 
//        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12));
//        jLabel5.setText("Nodes");
//        
//        jList1.setListData(cyAtts.getAttributeNames()) ;
//        
//        jScrollPane1.setViewportView(jList1);
// 
//        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12));
//        jLabel13.setText("Results:");
// 
//        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12));
//        jLabel14.setText("Name");
// 
//        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12));
//        jLabel15.setText("Database");
// 
//        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12));
//        jLabel16.setText("Name");
// 
//        jButton1.setText("Start Search");
// 
//        jButton2.setText("Add to Existing Network");
// 
//        jButton3.setText("Advanced");
// 
//        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
//        getContentPane().setLayout(layout);
//        layout.setHorizontalGroup(
//            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
//            .add(layout.createSequentialGroup()
//                .addContainerGap()
//                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
//                    .add(layout.createSequentialGroup()
//                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
//                        .addContainerGap())
//                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
//                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
//                            .add(jLabel1)
//                            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
//                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
//                                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
//                                        .add(jCheckBox7)
//                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 136, Short.MAX_VALUE)
//                                        .add(KEGGProgress, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 119, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
//                                    .add(layout.createSequentialGroup()
//                                        .add(jCheckBox5)
//                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 128, Short.MAX_VALUE)
//                                        .add(PUMA2Progress, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 119, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
//                                    .add(layout.createSequentialGroup()
//                                        .add(jCheckBox4)
//                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 130, Short.MAX_VALUE)
//                                        .add(BioCycProgress, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 119, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
//                                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
//                                        .add(jCheckBox3)
//                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 134, Short.MAX_VALUE)
//                                        .add(HPRDProgress, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 119, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
//                                    .add(layout.createSequentialGroup()
//                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
//                                            .add(jLabel2)
//                                            .add(jLabel3))
//                                        .add(14, 14, 14)
//                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
//                                            .add(org.jdesktop.layout.GroupLayout.LEADING, databaseNameText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 172, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
//                                            .add(org.jdesktop.layout.GroupLayout.LEADING, nodeIDText, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
//                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED))
//                                    .add(layout.createSequentialGroup()
//                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
//                                            .add(jCheckBox2)
//                                            .add(jCheckBox1))
//                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 132, Short.MAX_VALUE)
//                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
//                                            .add(IntActProgress, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                                            .add(MINTProgress, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
//                                            .add(jLabel4)))
//                                    .add(ReactomeProgress, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 119, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
//                                .add(28, 28, 28)))
//                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
//                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
//                            .add(layout.createSequentialGroup()
//                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
//                                    .add(jLabel6)
//                                    .add(jLabel7)
//                                    .add(jLabel8)
//                                    .add(jLabel11)
//                                    .add(jLabel9)
//                                    .add(jLabel12)
//                                    .add(jLabel10))
//                                .add(19, 19, 19))
//                            .add(layout.createSequentialGroup()
//                                .add(jLabel5)
//                                .addContainerGap())))
//                    .add(layout.createSequentialGroup()
//                        .add(39, 39, 39)
//                        .add(titleText, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
//                        .addContainerGap())
//                    .add(layout.createSequentialGroup()
//                        .add(jCheckBox6)
//                        .addContainerGap(308, Short.MAX_VALUE))
//                    .add(layout.createSequentialGroup()
//                        .add(jLabel13)
//                        .addContainerGap(324, Short.MAX_VALUE))
//                    .add(layout.createSequentialGroup()
//                        .add(jLabel14)
//                        .add(75, 75, 75)
//                        .add(jLabel15)
//                        .add(70, 70, 70)
//                        .add(jLabel16)
//                        .add(97, 97, 97))
//                    .add(layout.createSequentialGroup()
//                        .add(jButton1)
//                        .add(21, 21, 21)
//                        .add(jButton2)
//                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 21, Short.MAX_VALUE)
//                        .add(jButton3)
//                        .addContainerGap())))
//        );
//        layout.setVerticalGroup(
//            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
//            .add(layout.createSequentialGroup()
//                .add(titleText)
//                .add(30, 30, 30)
//                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
//                    .add(jLabel2)
//                    .add(nodeIDText))
//                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
//                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
//                    .add(jLabel3)
//                    .add(databaseNameText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
//                .add(19, 19, 19)
//                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
//                    .add(jLabel1)
//                    .add(jLabel5)
//                    .add(jLabel4))
//                .add(17, 17, 17)
//                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
//                    .add(jCheckBox1)
//                    .add(IntActProgress, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
//                    .add(jLabel6))
//                .add(12, 12, 12)
//                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
//                    .add(jCheckBox2)
//                    .add(MINTProgress, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
//                    .add(jLabel7))
//                .add(14, 14, 14)
//                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
//                    .add(jCheckBox3)
//                    .add(HPRDProgress, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
//                    .add(jLabel8))
//                .add(13, 13, 13)
//                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
//                    .add(BioCycProgress, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
//                    .add(jLabel9)
//                    .add(jCheckBox4))
//                .add(16, 16, 16)
//                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
//                    .add(PUMA2Progress, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
//                    .add(jLabel11)
//                    .add(jCheckBox5))
//                .add(16, 16, 16)
//                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
//                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
//                        .add(ReactomeProgress, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
//                        .add(jCheckBox6))
//                    .add(jLabel12))
//                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
//                    .add(layout.createSequentialGroup()
//                        .add(13, 13, 13)
//                        .add(jCheckBox7))
//                    .add(layout.createSequentialGroup()
//                        .add(17, 17, 17)
//                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
//                            .add(KEGGProgress, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
//                            .add(jLabel10))))
//                .add(17, 17, 17)
//                .add(jLabel13)
//                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
//                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
//                    .add(jLabel14)
//                    .add(jLabel15)
//                    .add(jLabel16))
//                .add(3, 3, 3)
//                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 154, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
//                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
//                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
//                    .add(jButton1)
//                    .add(jButton3)
//                    .add(jButton2))
//                .addContainerGap(38, Short.MAX_VALUE))
//        );
//        pack();
//    }// </editor-fold>                       
//   
//    /**
//     * @param args the command line arguments
//     */
//    public void loadGui(Node nd) {
//    	final Node node = nd;
//        java.awt.EventQueue.invokeLater(new Runnable() {
//        	public void run() {
//                new GUI(node).setVisible(true);
//            }
//        });
//    }
//   
//    // Variables declaration - do not modify                    
//    private javax.swing.JProgressBar BioCycProgress;
//    private javax.swing.JProgressBar HPRDProgress;
//    private javax.swing.JProgressBar IntActProgress;
//    private javax.swing.JProgressBar KEGGProgress;
//    private javax.swing.JProgressBar MINTProgress;
//    private javax.swing.JProgressBar PUMA2Progress;
//    private javax.swing.JProgressBar ReactomeProgress;
//    private javax.swing.JLabel databaseNameText;
//    private javax.swing.JButton jButton1;
//    private javax.swing.JButton jButton2;
//    private javax.swing.JButton jButton3;
//    private javax.swing.JCheckBox jCheckBox1;
//    private javax.swing.JCheckBox jCheckBox2;
//    private javax.swing.JCheckBox jCheckBox3;
//    private javax.swing.JCheckBox jCheckBox4;
//    private javax.swing.JCheckBox jCheckBox5;
//    private javax.swing.JCheckBox jCheckBox6;
//    private javax.swing.JCheckBox jCheckBox7;
//    private javax.swing.JLabel jLabel1;
//    private javax.swing.JLabel jLabel10;
//    private javax.swing.JLabel jLabel11;
//    private javax.swing.JLabel jLabel12;
//    private javax.swing.JLabel jLabel13;
//    private javax.swing.JLabel jLabel14;
//    private javax.swing.JLabel jLabel15;
//    private javax.swing.JLabel jLabel16;
//    private javax.swing.JLabel jLabel2;
//    private javax.swing.JLabel jLabel3;
//    private javax.swing.JLabel jLabel4;
//    private javax.swing.JLabel jLabel5;
//    private javax.swing.JLabel jLabel6;
//    private javax.swing.JLabel jLabel7;
//    private javax.swing.JLabel jLabel8;
//    private javax.swing.JLabel jLabel9;
//    private javax.swing.JList jList1;
//    private javax.swing.JScrollPane jScrollPane1;
//    private javax.swing.JLabel nodeIDText;
//    private javax.swing.JLabel titleText;
//    private String nodeId;
//    private Node node;
//    private CyAttributes cyAtts;
//    // End of variables declaration                  
//   
//}